### ISSUE TITLE
Card attachment: Adding a photo from camera fails

### ISSUE THREAD

**Issue by roboticsalign** [stefan-niedermann/nextcloud-deck#1003]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Adding an attachment to a card works. But choosing camera as source fails.

1. Open a card
2. Go to attachments and add a new one
3. Select gallery and camera
4. Take a picture and the exception happens

**Expected behavior**
The new picture should be added in Deck

**Screenshots**
-

**Versions**
 - Nextcloud: 21.0.2
 - Nextcloud Deck: 1.4.2
 - Nextcloud Android: 3.16.0
 - Nextcloud Android Deck: 1.18.2

**Smartphone (please complete the following information):**
- Device: Galaxy S10
- Android-Version: 11
- App-Store:
  - [ x ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

```

App Version: 1.18.2
App Version Code: 1018002
Server App Version: 1.4.2
App Flavor: play

Files App Version Code: 30160090

---

OS Version: 4.14.113-21644994(G973FXXUAFUE3)
OS API Level: 30
Device: beyond1
Manufacturer: samsung
Model (and Product): SM-G973F (beyond1lteeea)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.lambda$onError$1$CardAttachmentsFragment$5(CardAttachmentsFragment.java:486)
	at it.niedermann.nextcloud.deck.ui.card.attachments.-$$Lambda$CardAttachmentsFragment$5$hVot0UsiBJTsFqXfls7GpMVJ05Q.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: {"status":500,"message":"Die hochgeladene Datei \u00fcberschreitet die upload_max_filesize-Vorgabe in php.ini"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1195)
	at android.os.Binder.execTransact(Binder.java:1159)

```

**Comment by stefan-niedermann** [comment]
Hello @roboticsalign 👋 

quoting from the error message:

> Die hochgeladene Datei \u00fcberschreitet die upload_max_filesize-Vorgabe in php.ini

So you should check your Nextcloud server configuration and increase the limit of uploaded file sizes.

We already have [an issue](https://github.com/stefan-niedermann/nextcloud-deck/issues/830) to display a better error message, this won't change the fact that we can't upload too big files when the server forbids it 🤷

**Comment by roboticsalign** [comment]
Thanks for the quick answer!

I'll check that, because everything else works well since years.

**Comment by roboticsalign** [comment]
In Nextcloud the max. upload size is not shown. Could this be the issue?


![Screenshot_20210530-202234_Chrome.jpg](https://user-images.githubusercontent.com/23562360/120115662-fbd7cd80-c184-11eb-95fa-963c41e4c398.jpg)

**Comment by desperateCoder** [comment]
@roboticsalign in case you're using a shared hosting service, you could maybe look it up in your plan details or ask the provider. If your instance is self-hosted, just look it up in your php.ini file. If the value is empty or missing, you can look up the default value by simply googling it. Quick Google search said: it is 2MB, which a modern phone camera easily exceedes.

**Comment by stefan-niedermann** [comment]
No, you posted an image about the amount of RAM which your Nextcloud has available.

You need to configure the maximum file size in the `php.ini` file. This is nothing Deck related though (and for sure not related to the Android Deck app 😄) but maybe you can find some information about how to configure your Nextcloud in the [administration manual](https://docs.nextcloud.com/server/20/admin_manual/configuration_files/big_file_upload_configuration.html).

I don't know much about web servers and their configuration though, as hard as i'd like to help you here, i am afraid i can't...

**Comment by stefan-niedermann** [comment]
If i am not completely wrong, i think this is the same limitation also affects file uploads via Browser (Deck, but also normal files).

You could also try to search https://help.nextcloud.com/ - i think you are not the first one with a question regarding the configuration 🙂

**Comment by roboticsalign** [comment]
Thanks for your suggestions.

I checked the php.ini and phpinfo. It is configured with 16GB as it suggested. Uploading large files is not an issue via browser, sync client (win, linux, android, ios) or Talk. I use this since years with ~10 users and no issues regarding upload filesize...

The last point in the screenshot adresses "maximale Größe zum Hochladen", that means "max upload size". But the value is not shown. Could be, that it is not imortant so lets forget it.

Du you have suggestion for further research?

**Comment by stefan-niedermann** [comment]
> sync client (win, linux, android, ios) or Talk (browser, android, ios).

Yep, the sync clients upload files in small chunks, while the Deck server API does not provide such a feature. That's why i explicitly asked for the Browser upload which has the same limitation.

> The last point in the screenshot adresses "maximale Größe zum Hochladen", that means "max upload size". But the value is not shown. Could be, that it is not imortant so lets forget it.

You are right, i didn't read this. Interesting that it apparently doesn't have a value set...



Can you please check / confirm that you are able to upload large attachments ([Here is a big sample image](https://nextcloud.niedermann.it/index.php/s/yZFbfCDgTNeToCT/download/SamplePNGImage_30mbmb.png)) via browser to a Deck card? Depending on whether you are using the modal view or the sidebar, i mean either this

![grafik](https://user-images.githubusercontent.com/4741199/120118895-15811100-c195-11eb-8b0a-0b22d03d27f9.png)

or this button:

![grafik](https://user-images.githubusercontent.com/4741199/120118937-46f9dc80-c195-11eb-9c7a-1f37859b77fd.png)

**Comment by roboticsalign** [comment]
I tested the upload of the proposed image with Android Smartphone and Chrome:

- files-app: ok
- talk-app: ok
- deck-app: upload error

Then, I checked it with a small txt file ([https://filesamples.com/samples/document/txt/sample1.txt](https://filesamples.com/samples/document/txt/sample1.txt) < 1kb)

- files-app: ok
- talk-app: ok
- deck-app: upload error

So I'll check the deck-installation on server side since it does not allow any upload. 

The problem seems not to related to the Android App so I'll report my findings and then will close this issue. Thanks for your support!

**Comment by desperateCoder** [comment]
Well, that's odd... But yeah, I think your conclusion is absolutely valid. I'd suggest linking this issue to the new one in the server repository, so @juliushaertl can see what you already tried.

**Comment by stefan-niedermann** [comment]
Okay, you can open issues for the Deck server app here: https://github.com/nextcloud/deck/issues/new?assignees=&labels=&template=Bug_report.md

Ideally post a link to your new issue here so other people who stumble upon the same issue can follow your steps.

Sorry that we couldn't help more and good luck with the issue!

**Comment by roboticsalign** [comment]
The solution is described in this issue: https://github.com/nextcloud/deck/issues/573#issuecomment-414052070
It seems to be an error in my php.ini, that was not identified before.

I do not understand, why everything worked as expected - exept deck.
