### ISSUE TITLE
[Bug Report] When I click on the "Delete column" option, the application crashes.

### ISSUE THREAD

**Issue by sargoon** [stefan-niedermann/nextcloud-deck#102]
**Describe the bug**
When I click on the "Delete column" option, the application crashes immediately.

**To Reproduce**
1. Open the Nextcloud Deck 
2. Click on the "Delete column" option.
3. And you will see the application crashes and appears the error codes.

**Expected behavior**
When I click on the "Delete column" option, the application should delete any existing columns properly. if the column does not exist, it should display a message box that says "Column (or columns) not found."

**Actual behavior**

The "Delete column" option doesn't work, when I click on it, the application crashes and appears the error codes.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 7
 - Android-Version: 9.0

**Recording Of The Bug**
![AnimatedWatchfulIguana-size_restricted](https://user-images.githubusercontent.com/34961616/60596941-a9cc7880-9db2-11e9-8768-203b72386541.gif)

**Logcat**
`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at it.niedermann.nextcloud.deck.ui.stack.StackAdapter.getItem(StackAdapter.java:22)
	at it.niedermann.nextcloud.deck.ui.MainActivity.onOptionsItemSelected(MainActivity.java:299)
	at android.app.Activity.onMenuItemSelected(Activity.java:3608)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1192)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3184)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4182)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3896)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:129)
	at android.view.View.dispatchTouchEvent(View.java:12527)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2407)
	at android.view.View.dispatchPointerEvent(View.java:12768)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5230)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5030)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4598)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4564)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4704)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4572)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4761)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4598)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4564)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4572)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4545)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7263)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7232)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7193)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7369)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

**Comment by desperateCoder** [comment]
Hi @sargoon,
Thanks for your report! This feature is not implemented yet, but the app at least schouldn't crash, maybe even show a toast to inform the user...

@stefan-niedermann maybe you could fix that real quick?
