### ISSUE TITLE
Deck crashed due to bold format was applied

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1044]
**Describe the bug**
See steps to reproduce field below

1. The access to the internet on android device has been closed. 
2. Create a card in Deck 
3. Added header and description in the relevant fields
4. Saved card and close app itself. 
5. Then open created card once again. Open editing mode then marked some word (by finger holding on device screen) then open three vertical dots menu (in popup field) then put on bold format
6. After 5 point the app has been crashed with error message (see below in stacktrace)
7. Then I've tried to reproduce 5 point once again and met the same situation/issue
8. To reproduce that issue once again, I've tried to open another one cards which one already were created earlier and synchronized with server - the issue/error didn't appear. 

**Expected behavior**
-

**Screenshots**
-

**Versions**
 - Nextcloud: 20.0.2
 - Nextcloud Deck: 1.4.2
 - Nextcloud Android: 3.16.1 
 - Nextcloud Android Deck: 1.18.3

**Smartphone (please complete the following information):**
- Device: Honor 10 Light
- Android-Version: 10
- App-Store:
  - [x] Google Play Store

**Stacktrace**

```
Full Crash:

App Version: 1.18.3
App Version Code: 1018003
App Flavor: play

Files App Version Code: 30160190

---

OS Version: 4.14.116(10.0.0.221C10)
OS API Level: 29
Device: HWHRY-H
Manufacturer: HUAWEI
Model (and Product): HRY-LX1 (HRY-LX1RU)

---

java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1338)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:692)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
	at android.text.Selection.setSelection(Selection.java:94)
	at android.text.Selection.setSelection(Selection.java:78)
	at android.text.Selection.setSelection(Selection.java:153)
	at android.widget.EditText.setSelection(EditText.java:136)
	at it.niedermann.android.markdown.markwon.format.ContextBasedRangeFormattingCallback.onActionItemClicked(ContextBasedRangeFormattingCallback.java:80)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4271)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2936)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:99)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:164)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:124)
	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.lambda$createOverflowPanel$2$FloatingToolbar$FloatingToolbarPopup(FloatingToolbar.java:1629)
	at com.android.internal.widget.-$$Lambda$FloatingToolbar$FloatingToolbarPopup$E8FwnPCl7gZpcTlX_UaRPIBRnT0.onItemClick(Unknown Source:8)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1259)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3306)
	at android.widget.AbsListView$3.run(AbsListView.java:4296)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by stefan-niedermann** [comment]
Thanks for the report and sorry for the inconveniences.

Can you share a minimal sample of the text in your description and tell us from where to where exactly you selected the text before you toggled `bold`?

We have some enhancements for the editor for version `1.19.0` in the pipeline which likely will also solve this issue, but it would be great if we can ensure that this bug will also be fixed with the new release.

For example:

```
This is some sample Text.

It requires to be multiple lines and have one *italic* word
```

> Selecting "requires" and toggling bold will lead to the crash.

**Comment by stefan-niedermann** [comment]
`1.19.0` is getting rolled out starting today in stages. We assume that also this bug *should* be addressed.
Feel free to reopen this issue if it still occurs with `1.19.0` or later or alternatively provide a crashing sample from `1.18.3`, which will also allow us to verify whether this behavior still occurs.
