### ISSUE TITLE
Exception in StackFaragment

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#106]
**Describe the bug**
While randomly doing pull-down-syncs, opening card details and pushing the back button, somtimes i see the following logcat entries (at least on **upsync-branch**):
```
2019-07-14 12:27:25.326 28500-29007/it.niedermann.nextcloud.deck D/deck: runOnUiThread() (StackFragment.java:136) -> java.lang.Exception: Activity is null
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment.runOnUiThread(StackFragment.java:136)
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment.refreshView(StackFragment.java:110)
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment.access$000(StackFragment.java:28)
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment$1.onResponse(StackFragment.java:88)
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment$1.onResponse(StackFragment.java:85)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$1$1.onResponse(SyncManager.java:77)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$1$1.onResponse(SyncManager.java:72)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:225)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:109)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:106)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:90)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$1.lambda$onResponse$0(SyncManager.java:85)
        at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$1$sy1r3klzPK3UdZB5T0drzwhw2Oc.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
2019-07-14 12:27:25.326 28500-29007/it.niedermann.nextcloud.deck D/deck: runOnUiThread() (StackFragment.java:136) -> java.lang.Exception: Activity is null
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment.runOnUiThread(StackFragment.java:136)
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment.access$100(StackFragment.java:28)
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment$1.onResponse(StackFragment.java:89)
        at it.niedermann.nextcloud.deck.ui.stack.StackFragment$1.onResponse(StackFragment.java:85)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$1$1.onResponse(SyncManager.java:77)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$1$1.onResponse(SyncManager.java:72)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:225)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:109)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:106)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:90)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$1.lambda$onResponse$0(SyncManager.java:85)
        at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$1$sy1r3klzPK3UdZB5T0drzwhw2Oc.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by stefan-niedermann** [comment]
not reproducable (maybe fixed??)
