### ISSUE TITLE
Unexpected behavior of android app for different scenarios

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1064]
**First scenario**
---
**Describe the bug and steps to reproduce**
So in this case I have good and strong internet connection on android device and access to my server/instance and synchronization capability. Open my android deck app then open existing deck, I wanna renew my synchronizations and put my finger on device screen then pull down. And after then I saw the window with next error message. 

**Expected behavior**
Just renew synchronization both server and android deck. 

**Stacktrace**

```
App Version: 1.19.0
App Version Code: 1019000
Server App Version: 1.4.3
App Flavor: play

Files App Version Code: 30160190

---

OS Version: 4.14.116(10.0.0.221C10)
OS API Level: 29
Device: HWHRY-H
Manufacturer: HUAWEI
Model (and Product): HRY-LX1 (HRY-LX1RU)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Connection reset
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Second scenario**
---

**Describe the bug and steps to reproduce**
All access to server/instance and internet on android were reachable and I have good and strong internet connection on android device and access to my server/instance and synchronization capability.
I've tried to add a new card in an existing deck on android. Pushed on plus in right down corner then started enter the name of card. After that, I've tried to save card and I saw the next error. After that I closed the window with error and saw field for entering name of card once again including previous entered name. Pushed to save once again and I saw double similar cards. 

**Expected behavior**
Simple implementation of steps for final goal achievement.

**Stacktrace**

```
App Version: 1.19.0
App Version Code: 1019000
Server App Version: 1.4.3
App Flavor: play

Files App Version Code: 30160190

---

OS Version: 4.14.116(10.0.0.221C10)
OS API Level: 29
Device: HWHRY-H
Manufacturer: HUAWEI
Model (and Product): HRY-LX1 (HRY-LX1RU)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "cloud.website.net": No address associated with hostname
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Versions**
    - Nextcloud: 20.0.3
    - Nextcloud Deck: 1.4.2
    - Nextcloud Android: 3.16.1
    - Nextcloud Android Deck: 1.19.0

**Smartphone (please complete the following information):**
- Device: Honor 10 Light
- Android-Version: 10
- App-Store: Google Play Store

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-deck/issues/1063#issuecomment-888232487
