### ISSUE TITLE
HTTP 403 when creating a card

### ISSUE THREAD

**Issue by alexanderdd** [stefan-niedermann/nextcloud-deck#1072]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Tried to create a card, crash report (below) was shown. Tried two times, same. The cards were there though.

````
App Version: 1.19.0
App Version Code: 1019000
Server App Version: 1.2.8
App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 3.10.84-perf-g51b663cc723-04742-g5bcfaca9e61(1631208121)
OS API Level: 26
Device: F5321
Manufacturer: Sony
Model (and Product): F5321 (F5321)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 403
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: {"status":403,"message":"Permission denied"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:674)

````

**Comment by stefan-niedermann** [comment]
Hi @alexanderdd,

so first of all this does not look like a "crash", this looks like the card was created successfully on your device and it just did not get *synchronized* to your server and you therefore got this notification that something went wrong. This is an important difference, so tell me if my assumption is wrong here.

From the error message i can see a `HTTP 403` which basically means `Not authorized` or `Permission denied`, so it seems like your server does not allow you to create this card in this place. So please check whether you are able to create cards in this place with a web browser. Maybe you are on a shared board and someone withdrew your permissions?

PS.: Please fill in the issue template next time, it [is there for a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).

**Comment by desperateCoder** [comment]
Also please check if your credentials are still valid. If you changed your password or something, please correct it in the Nextcloud FILES app. Maybe you'll also need to reconnect the account in the deck app afterwards.

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback. Please feel free to reopen this issue with additional information, especially

> So please check whether you are able to create cards in this place with a web browser. Maybe you are on a shared board and someone withdrew your permissions?

**Comment by alexanderdd** [comment]
I think it was due to unstable connection or something. I had the necessary persmission all the time, and my credentials always worked.

Thanks for the quick replies. 

It did not happen again.
