### ISSUE TITLE
Need action ASAP with Deck server app

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1076]
I know that is not your branch but since I've updated to nextcloud version 22.1.0 I have no possibility to log in my cloud server from "cold" start (non cached). So I have been forced to disable my server deck app and as consequence I can't use android deck with server version (when server deck is off access to cloud server works fine). And I'm not alone, as I can see. Nextcloud deck issue [#3248](https://github.com/nextcloud/deck/issues/3248)

**Comment by stefan-niedermann** [comment]
I am aware of the problem (i am watching the deck server repository as well), but what exactly are you expecting from us Android devs? We don't know the code of the deck server app nor can we push any bugfix there (or even publish new versions).

Why are you not able to contiue using the Deck Android app? Even not when being offline?

**Comment by neerro** [comment]
> 
> 
> I am aware of the problem (i am watching the deck server repository as well), but what exactly are you expecting from us Android devs? We don't know the code of the deck server app nor can we push any bugfix there (or even publish new versions).
> 
Yes, I know it, but I've made notice about in the hope of you could sort things out issue with developers server deck.
>
> Why are you not able to continue using the Deck Android app? Even not when being offline?
>
Yes, I can't use as after I tried to add a new card I've got one more error with code 302

```
App Version: 1.19.3
App Version Code: 1019003
Server App Version: 1.4.3
App Flavor: play

Files App Version Code: 30160190

---

OS Version: 4.14.116(10.0.0.221C10)
OS API Level: 29
Device: HWHRY-H
Manufacturer: HUAWEI
Model (and Product): HRY-LX1 (HRY-LX1RU)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: Ошибка выполнения запроса HTTP. Код состояния: 302
    at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
    at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
    at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
    at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
    at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
    at io.reactivex.Observable.subscribe(Observable.java:12284)
    at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
    at io.reactivex.Observable.subscribe(Observable.java:12284)
    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
    at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: 
    at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
    at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
    at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
    at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
    at android.os.Binder.execTransactInternal(Binder.java:1028)
    at android.os.Binder.execTransact(Binder.java:1001)
```

**Comment by stefan-niedermann** [comment]
> Yes, I can't use as after I tried to add a new card I've got one more error with code 302

Does this also happen when you are in mobile data and enable the `Sync only on Wi-Fi` setting? Or when you put yiur device in aero plane mode?

**Comment by neerro** [comment]
> 
> 
> > Yes, I can't use as after I tried to add a new card I've got one more error with code 302
> 
> Does this also happen when you are in mobile data and enable the `Sync only on Wi-Fi` setting? Or when you put yiur device in aero plane mode?
>
The second one, in airplane mode.

**Comment by neerro** [comment]
The same error in wi-fi mode as I've described above. And also I can see new added card after error window closed.

**Comment by stefan-niedermann** [comment]
Well, the Deck Android client was never meant to be a standalone app and requires a server to synchronize with. It can handle offline state of the device as you noticed ("I saw the new card in list"). I will check why the app tries to perform network requests in aero plane mode while it shouldn't. When the server which it is connected to, doesn't have an enabled Deck app though it is correct to display the error message.

The `302` seems a bit odd form my point of view as the error message should be more something like `Deck node is missing in capabilities endpoint` - at least i get this when i just tested to disable the Deck server app on my instance. Since i don't know your environment and what you just did on your server, i'd recommend to not do too much stuff in case there is something else broken and you end in a state where the app is no longer able to upsync your local changes (for example if the authentication token is invalid or in an inconsistent state).

It *might* be possible that the Deck Android app recovers successfully after your server nightmare and upsyncs all local changes. My recommendation to ensure that you are not losing your changes though (after seeing the `302`) is to revert your Nextcloud server instance to a clean backup. If the Android app does synchronize then, fine, otherwise remove your Account from the Android app and reimport it (or [clear the storage](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error)). You can also try to install the last known Deck server app version that worked.

The server app maintainer @juliushaertl is watching his repository and  therefore notified. Apart from that there is not much we can do on our side, sorry.
