### ISSUE TITLE
App can no longer reach server?

### ISSUE THREAD

**Issue by deathblade666** [stefan-niedermann/nextcloud-deck#1098]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Hi I just setup nginx to provide ssl cert for my nextcloud instance. I have configured the nextcloud app and have no problema connecting there. Everything else is working but deck doesn't connect gives a 301 error. This is while on and off the same network the instance is. 

1. Open app
2. Sign in using the existing account from the nextcloud app
3. See error

**Expected behavior**

Connect like everything else

**Screenshots**

**Versions**

 - Nextcloud: 21.0.2
 - Nextcloud Deck: 1.4.3
 - Nextcloud Android: 3.17.0
 - Nextcloud Android Deck: 1.19.3

**Smartphone (please complete the following information):**

Please see below
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [x] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

This is the error log provided by the app

```
App Version: 1.19.3
App Version Code: 1019003
Server App Version: 0.6.4
App Flavor: play

Files App Version Code: 30170090

---

OS Version: 4.4.223-g52750b8f2138-ab6846512(6934943)
OS API Level: 30
Device: taimen
Manufacturer: Google
Model (and Product): Pixel 2 XL (taimen)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 301
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: <html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

```

Please let me know if there is more info needed

**Comment by desperateCoder** [comment]
Hi @deathblade666, thanks for your report!

Just a wild guess: is the deck server app actually installed in your new instance? 😄 

Alterntatively you could try reconnecting the app by deleting the apps storage, if you don't have non synchronized local changes on your phone.

The call is actually done by the files app, so there isn't much we can do about it.

Can you use deck via browser?

**Comment by deathblade666** [comment]
Hi yes it is installed on my instance. Its the same instance ive been using just now have an external address. I have tried clearing app data as well as uninstall and reinstall same thing. I did notice that there is an update for my NC instance. I'll update it and try again

Also yes I can use deck via browser just fine

**Comment by desperateCoder** [comment]
Ok, thats kind of wild... uhm... are you sure the files app works properly? Is a newly added file uploaded to the server?

If yes, could you please try accessing your server via `curl`? Thats pretty much the call our app is making.
Like this:
`curl -X GET 'https://<username>:<password>@<domain>/index.php/apps/deck/api/v1.0/boards?verbose=true' -H 'Accept: application/json' -H 'OCS-APIRequest: true' -H 'Content-Type: application/json;charset=utf-8' ` 
(make sure to replace the placeholders :stuck_out_tongue_winking_eye: )

**Comment by desperateCoder** [comment]
Oh, i also found this in the interwebz:

https://help.nextcloud.com/t/nextcloud-client-not-working-with-proxy-redirects/70117

And

https://github.com/nextcloud/android/issues/6465

The second one also has @stefan-niedermann involved, our fellow maintainer. Seems to be an issue with https-redirects. The notes app also uses the files app for the requests (surprise! Same maintainer). Maybe you could dig into this? 

Is your files app configured to access your instance via http or https?

**Comment by deathblade666** [comment]
Thanks I'll take a look at those links. I assume by the files app you mean the standard next cloud app. Interesting so I just tested uploading a file it failed with the same error "permanently moved".  So it would seem it is an issue with the main app and how it handles redirects. Thank you for the information and your time! I will move my issue over to their repo. 

Since this is an issue with the next cloud app I will close this issue

Please let me know if there is anything else you would like for me to still try.

**Comment by deathblade666** [comment]
Just FYI. I have tried various things I have found on line to fix this  none have worked. I have re-signed in under my non public address for my server and everything is working as expected.

Thanks again for pointing me to the actual issue.

**Comment by desperateCoder** [comment]
You're very welcome! 😊 

I'm glad it worked out, at least sort of 😅

**Comment by deathblade666** [comment]
Sorry just another FYI for anyone who might run come here for assistance. I have found a solution (at least for me) and have posted it in the Nextcloud android repo issue mentioned above.

**Comment by desperateCoder** [comment]
Sharing is caring, thanks for that! :heart:
