### ISSUE TITLE
App crash while login into account

### ISSUE THREAD

**Issue by alexminder** [stefan-niedermann/nextcloud-deck#1117]
**Describe the bug**
When I try to login in to Nextcloud account app crashes at import cards step.

1. Go to the Deck app
2. Click on login and select Nextcoud account
3. grant access to Nextcloud account

**Expected behavior**

No errors. Work with deck cards and sync it with cloud.

**Versions**

 - Nextcloud: 20.0.9
 - Nextcloud Deck: 1.2.7
 - Nextcloud Android: 3.17.0.30170090
 - Nextcloud Android Deck: 1.19.4.1019004

**Smartphone (please complete the following information):**
- Device: Google Pixel 4a
- Android-Version: 11 (graphene os)
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

```
App Version: 1.19.4
App Version Code: 1019004
Server App Version: 1.2.7
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.14.212-ga2b622b19d70(2021092612)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---


android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.StackDao_Impl.insert(StackDao_Impl.java:183)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.StackDao_Impl.insert(StackDao_Impl.java:33)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.createStack(DataBaseAdapter.java:632)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.createInDB(StackDataProvider.java:44)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.createInDB(StackDataProvider.java:20)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:62)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:47)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:66)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by stefan-niedermann** [comment]
Just as a quick-shot until @desperateCoder has time to look into the actual issue: Have you already tried to clear the storage of the app as explained [in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error)?

**Comment by alexminder** [comment]
> Just as a quick-shot until @desperateCoder has time to look into the actual issue: Have you already tried to clear the storage of the app as explained [in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error)?

Yes. Clearing storage does not help.

**Comment by desperateCoder** [comment]
Hi @alexminder, thanks for your report!

Honestly, I have no idea how this could happen, this part isn't critical at all and should run just fine, never had something like that before. 

But anyways, i have built a special debug version of our app, you can install it along with your current app from fdroid. But this time, as it crashes, it will provide a bunch of details helping me to understand what is going on with your sync.

Please take [this APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/3939744238/artifacts/98744585), try to sync and send us the new crash report as you did above.

**Comment by desperateCoder** [comment]
Ok, here's another one to test, this time I explicitly check, if the account and the board (the two constraints on `stacks`) are present: [Download (≧︿≦)](https://github.com/stefan-niedermann/nextcloud-deck/suites/3978633259/artifacts/100089965)

Please make sure to uninstall the current DEV app before installing this one. Most probably this one will crash as well, but you know the procedure: copy the crash report and post it here please. 

To be honest, this one triggers me. This shouldn't be possible to happen. I have two bets on this:

It will:
* state the board wasn't created (thats what i hope for)
* state the same thing as you already posted

In both cases further investigation will be required (sorry for that in advance!), but I refuse to give up on this. Thanks for your help!

**Comment by alexminder** [comment]
```
App Version: 1.19.4
App Version Code: 1019004
Server App Version: 1.4.5
App Flavor: dev

Files App Version Code: 30170090

---

OS Version: 4.14.234-ga05a5d05bc29(2021100606)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---

java.lang.RuntimeException: (WTF?!) Unable to create Stack FullStack{stack=Stack{title='Надо сделать', boardId=3, deletedAt=1970-01-01T00:00:00Z, order=1, localId=null, accountId=1, id=3, status=1, lastModified=2020-09-14T03:10:29Z, lastModifiedLocal=null, etag='a86368c718b6ba11bf5fb70d50f730fc'} it.niedermann.nextcloud.deck.model.Stack@bac40646, cards=[Card{title='Д.з. Новоселова с72/629', description='', stackId=3, type='text', createdAt=2018-12-23T07:19:55Z, deletedAt=1970-01-01T00:00:00Z, attachmentCount=0, userId=null, order=0, archived=false, dueDate=null, notified=false, overdue=0, commentsUnread=0, localId=null, accountId=0, id=4, status=1, lastModified=2019-05-28T08:14:33Z, lastModifiedLocal=null}, Card{title='Compex Performance EMS', description='', stackId=3, type='plain', createdAt=2020-09-14T03:10:07Z, deletedAt=1970-01-01T00:00:00Z, attachmentCount=0, userId=null, order=999, archived=false, dueDate=null, notified=false, overdue=0, commentsUnread=0, localId=null, accountId=0, id=49, status=1, lastModified=2020-09-14T03:10:07Z, lastModifiedLocal=null}, Card{title='Functional Movements workout', description='', stackId=3, type='plain', createdAt=2020-09-14T03:10:29Z, deletedAt=1970-01-01T00:00:00Z, attachmentCount=0, userId=null, order=999, archived=false, dueDate=null, notified=false, overdue=0, commentsUnread=0, localId=null, accountId=0, id=50, status=1, lastModified=2020-09-14T03:10:29Z, lastModifiedLocal=null}]} on Board FullBoard{board=Board{title='Личное', ownerId=1, color=-16777216, archived=false, shared=0, deletedAt=1970-01-01T00:00:00Z, permissionRead=true, permissionEdit=true, permissionManage=true, permissionShare=true, localId=3, accountId=1, id=2, status=1, lastModified=2020-09-14T03:10:29Z, lastModifiedLocal=null, etag='a86368c718b6ba11bf5fb70d50f730fc'} it.niedermann.nextcloud.deck.model.Board@2caae7cf, labels=[], owner=User{primaryKey='alex', uid='alex', displayname='Alexander Miroshnichenko', localId=1, accountId=1, id=null, status=1, lastModified=null, lastModifiedLocal=null} it.niedermann.nextcloud.deck.model.User@1f6fec95, participants=[], stacks=[]}
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.createInDB(StackDataProvider.java:60)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.createInDB(StackDataProvider.java:23)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:62)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:47)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:66)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:111)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.RuntimeException: Board wasn't created properly! ID: 3
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.createInDB(StackDataProvider.java:50)
	... 21 more

```

**Comment by desperateCoder** [comment]
@alexminder thanks for your response! Sorry for bothering you again, but we get closer. I need to make these baby-steps, so I won't miss anything here.

So "fortunately" it was my expectation, the board wasn't created properly, and that's weird. But ok, I guess we'll need to dive deeper in.

Here is another one: [APK (ノ ゜Д゜)ノ ︵ ┻━┻](https://github.com/stefan-niedermann/nextcloud-deck/suites/4011786514/artifacts/101288952)

Sorry again for taking your time, I hope I get a hint soon and can fix this for you.

**Comment by stefan-niedermann** [comment]
@KSH-codes your error message seems to be unrelated to this issue. Could you please open a new issue filling the issue template? The more information you can provide, the better can we help. For exaple: Did this only appear after the last update? Did you just install the app and it directly failed? Did you already try to clear the storage of both apps [as described in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) and did or did it not work after doing that?

**Comment by desperateCoder** [comment]
Hi @alexminder, sorry for the delay!

I managed to get each and every database query into the error message now.

WARNING: The error message will contain ALL the data in your boards the app was able to sync before it died (**but no credentials**)! So if you have very private data in there, maybe remove them from the logs before providing them. I promise I'm not interested in your actual data, but their constellation, so no need to remove each and every bit of data here, if you're fine with it.

I'd also suggest mailing the  error message to @stefan-niedermann (info@niedermann.it) rather than posting it here. We'll keep the data private and use it to solve this damn problem here.

You can download the more verbose version of the app here: [APK: ( ╥﹏╥) ノシ](https://github.com/stefan-niedermann/nextcloud-deck/suites/4345107622/artifacts/113980281)

**Comment by desperateCoder** [comment]
Thanks for your mail @alexminder,

unfortunately the log you sent wasn't even related to this issue, the server didn't provide a proper order of the card, which is weird. But anyways, I fixed that and made it more fault tolerant. It should now get to the point it failed before. Sorry for that, but good catch though, another problem fixed! Sorry for bothering you again :disappointed: 

Here is a fixed version: [APK: (҂◡_◡) ᕤ](https://github.com/stefan-niedermann/nextcloud-deck/suites/4359882870/artifacts/114528512)

I'm really, really sorry! Thanks for being that patient with us!

**Comment by alexminder** [comment]
@desperateCoder Last debug version success imported decks without errors. No changes on servers side was.

**Comment by desperateCoder** [comment]
@alexminder maybe I should also mention this:
> yes, we always recommend to clear thw storage of the Deck app in favor of uninstalling it, because Google (middle_finger) decided to keep some data when uninstalling an app. You can achieve this (depending on your manufacturer) by going to your Android settings -> Apps -> Deck -> Storage -> Clear storage.

As stated here: https://github.com/stefan-niedermann/nextcloud-deck/issues/1135#issuecomment-974676964

I wasn't aware of this to be honest, so I'll just leave it here in case this could cause other problems... You can also check the linked issue, there are a couple of versions linked, you could also try if you want.

By the way: If you could use a couple of voucher codes for the play-store version of this app as a "thank you", just hit us up, you already well deserved it!

Looking forward to your feedback!

**Comment by alexminder** [comment]
> This is the latest master the last test-build based on. 

Imported without errors

**Comment by alexminder** [comment]
> Android settings -> Apps -> Deck -> Storage -> Clear storage.

I have deleted the app with all data before install every debug version. Nothing to clear.

**Comment by desperateCoder** [comment]
> Imported without errors

Great! :partying_face: 

>  Nothing to clear.

As long as it works I'm fine with it!

As mentioned, if you could need some PlayStore vouchers for this app, just tell us any time, HUGE THANKS man, you helped us a lot here!

Can we close this issue then? I'll talk to @stefan-niedermann, I think we should release a new version soon

**Comment by desperateCoder** [comment]
@alexminder @TtuxX  sorry for the (huge) delay. I almost lost my mind on this, until I even found the lines that might be causing this. Concurrency is great as long as it works, but when it doesn't, it is a hell of a debug session.

Could you please test the following version and confirm it either still working (@alexminder) or still faulty (@TtuxX )?

[(≧︿≦) APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/6595843800/artifacts/247583160)

You can safely install it along your productive version, it will show up as a second app with a "dev" label.

**Comment by TtuxX** [comment]
Dear @desperateCoder, thank you so much for your update on this thread ! I was missing the latest updates from your great app and refrained a lot from pinging you haha

I tried your app (stopping the app and deleting all the data and so on). However the app does not load all the boards like the previous debug version you sent me in this issue.

It now stalls trying to import the large board that always fails (board 3/29), but the app does not crash or fail anymore. It now just stalls forever.

**Comment by desperateCoder** [comment]
@TtuxX thanks for your feedback! As saidy it was pure hell and to be honest it still is. I did further tests and had different outcomes. The good thing: cloning boards seems to work fine now, even with bigger boards. 

The bad thing: the devices still seem to be overwhelmed with big board trees and I still had quite some difficulties in my tests. The final word isn't spoken here yet, I'll keep working on this and update you as soon as I have something better. Just wanted to know if it's just my shitty server or you guys still have issues as well. 

As said, sorry for the delay! If You feel like it takes too long, sometimes a friendly reminder is helpful as well, so feel free to ping. Having such an asshole problem invites to procraste pretty badly 😅 

But as I was fixing the clone-boards feature, i discovered a whole new spectrum of possibilities, and I am willing to take ilthem to the fullest to get this working. It's getting kind of personal now, human vs. machines. 

In the next two weeks it could get a little busy, but be assured: I'm on it and motivated more than the last months. I'll let you know as soon as I have something better.

Btw: did you update your instance to a newer release of nextcloud and/or deck in the meantime? If yes: which versions are you running currently? Could help for testing purposes...

**Comment by TtuxX** [comment]
Haha thank you very much for not letting this issue down ! 

I would like to start coding android apps but I am a bit worried about how complex debuging this issue seems to be, I didn't think that the code and the way of operating of an android app could be so obscure and difficult to trace :0
I remember reading you or Stefan say that "android is a bitch" haha

I sent to info@niedermann.it further logs from the latest apk debug version :)

One message that keeps appearing in this new debug version is the following one:
```
05-24 10:33:13.801 17741 17871 I zygote64: Rejecting re-init on previously-failed class java.lang.Class<it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider>: java.lang.NoSuchMethodError: No static method newKeySet()Lj$/util/concurrent/ConcurrentHashMap$KeySetView; in class Lj$/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'j$.util.concurrent.ConcurrentHashMap' appears in /data/app/it.niedermann.nextcloud.deck.dev-i0aoz1v_ELXdJvGAEfKqwg==/base.apk:classes19.dex)
05-24 10:33:13.801 17741 17871 I zygote64:   at void it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.<clinit>() (CardDataProvider.java:38)
05-24 10:33:13.801 17741 17871 I zygote64:   at void it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeper(it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper, it.niedermann.nextcloud.deck.model.full.FullStack, it.niedermann.nextcloud.deck.model.full.FullStack, it.niedermann.nextcloud.deck.api.ResponseCallback) (StackDataProvider.java:70)
05-24 10:33:13.801 17741 17871 I zygote64:   at void it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeper(it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper, it.niedermann.nextcloud.deck.model.interfaces.IRemoteEntity, it.niedermann.nextcloud.deck.model.interfaces.IRemoteEntity, it.niedermann.nextcloud.deck.api.ResponseCallback) (StackDataProvider.java:20)
05-24 10:33:13.801 17741 17871 I zygote64:   at void it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(java.util.List) (SyncHelper.java:77)
05-24 10:33:13.801 17741 17871 I zygote64:   at void it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(java.lang.Object) (SyncHelper.java:47)
05-24 10:33:13.801 17741 17871 I zygote64:   at void it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.accept(java.lang.Object) (RequestHelper.java:56)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.internal.observers.LambdaObserver.onNext(java.lang.Object) (LambdaObserver.java:63)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(java.lang.Object) (ObservableSubscribeOn.java:58)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(java.lang.Object) (ObservableMap.java:62)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(java.lang.Object) (ObservableFromPublisher.java:56)
05-24 10:33:13.801 17741 17871 I zygote64:   at void com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(com.nextcloud.android.sso.aidl.NextcloudRequest, java.lang.reflect.Type, org.reactivestreams.Subscriber) (NextcloudAPI.java:130)
05-24 10:33:13.801 17741 17871 I zygote64:   at void com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(org.reactivestreams.Subscriber) (D8$$SyntheticClass:-1)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(io.reactivex.Observer) (ObservableFromPublisher.java:31)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.Observable.subscribe(io.reactivex.Observer) (Observable.java:12284)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(io.reactivex.Observer) (ObservableMap.java:32)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.Observable.subscribe(io.reactivex.Observer) (Observable.java:12284)
05-24 10:33:13.801 17741 17871 I zygote64:   at void io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run() (ObservableSubscribeOn.java:96)
05-24 10:33:13.801 17741 17871 I zygote64:   at java.lang.Void io.reactivex.internal.schedulers.ScheduledDirectTask.call() (ScheduledDirectTask.java:38)
05-24 10:33:13.801 17741 17871 I zygote64:   at java.lang.Object io.reactivex.internal.schedulers.ScheduledDirectTask.call() (ScheduledDirectTask.java:26)
05-24 10:33:13.801 17741 17871 I zygote64:   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
05-24 10:33:13.801 17741 17871 I zygote64:   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
05-24 10:33:13.801 17741 17871 I zygote64:   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
05-24 10:33:13.801 17741 17871 I zygote64:   at void java.lang.Thread.run() (Thread.java:784)
05-24 10:33:13.801 17741 17871 I zygote64: 
05-24 10:33:13.812  3850 17881 D InputStreamBinder: Done sending result
05-24 10:33:13.812  3850 17881 I com.nextcloud.android.sso.aidl.ParcelFileDescriptorUtil.TransferThread: releaseConnection
```

I updated my server and apps and their current versions are the following ones:
- Nextcloud server version: 24.0.0
- Nextcloud Deck server app version: 1.7.0

**Comment by desperateCoder** [comment]
Yep android can be a diva, but it also has its advantages.

It's not android making it so hard to debug, it's my own implementation. Sure, i could work synchronously call after call, but it would make everything super slow, so I contact the server in multiple simultaneous calls to speed the sync up. 

Having all that offline capabilities, so you don't always rely on the server, makes everything even more complex. 

So don't be afraid of coding for Android, be afraid of yourself. Or of *my* code 🤣

**Comment by wargreen** [comment]
Hi,
We have the same issue here.
Server : NC 27.1.1, Deck 1.11.0

Android : NC 3.25.0, Deck 1.23.3 (F-droid)

Smartphone : samsung SM-A032F with stock OS

We have two bug report, one first :
`App Version: 1.23.3
App Version Code: 1023003
Server App Version: 1.11.0
App Flavor: fdroid

Files App Version Code: 30250090 (PROD)

---

OS Version: 4.14.199-26139528-abA032FXXU3BWF2(A032FXXU3BWF2)
OS API Level: 31
Device: a3core
Manufacturer: samsung
Model (and Product): SM-A032F (a3corexx)

---

android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Card.accountId, Card.id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:940)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.kt:102)
	at it.niedermann.nextcloud.deck.database.dao.CardDao_Impl.insert(CardDao_Impl.java:263)
	at it.niedermann.nextcloud.deck.database.dao.CardDao_Impl.insert(CardDao_Impl.java:43)
	at it.niedermann.nextcloud.deck.database.DataBaseAdapter.createCardDirectly(DataBaseAdapter.java:744)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider.createInDB(CardDataProvider.java:84)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider.createInDB(CardDataProvider.java:34)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:62)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:47)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:63)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:58)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:52)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:123)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)`

And some seconds after, plenty of :
`App Version: 1.23.3
App Version Code: 1023003
Server App Version: 1.11.0
App Flavor: fdroid

Files App Version Code: 30250090 (PROD)

---

OS Version: 4.14.199-26139528-abA032FXXU3BWF2(A032FXXU3BWF2)
OS API Level: 31
Device: a3core
Manufacturer: samsung
Model (and Product): SM-A032F (a3corexx)

---

android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:940)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.kt:42)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.kt:102)
	at it.niedermann.nextcloud.deck.database.dao.UserDao_Impl.insert(UserDao_Impl.java:177)
	at it.niedermann.nextcloud.deck.database.dao.UserDao_Impl.insert(UserDao_Impl.java:29)
	at it.niedermann.nextcloud.deck.database.DataBaseAdapter.createUser(DataBaseAdapter.java:393)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider.fixRelations(CardDataProvider.java:100)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider.createInDB(CardDataProvider.java:83)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider.createInDB(CardDataProvider.java:34)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:62)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:47)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:63)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:58)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:52)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:123)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)`
