### ISSUE TITLE
Error uploading File in Deck

### ISSUE THREAD

**Issue by MaRitt89** [stefan-niedermann/nextcloud-deck#1137]
```
App Version: 1.19.4
App Version Code: 1019004
Server App Version: 1.5.3
App Flavor: play

Files App Version Code: 30170190

---

OS Version: 4.14.113-22340613(N975FXXS7FUI7)
OS API Level: 30
Device: d2s
Manufacturer: samsung
Model (and Product): SM-N975F (d2seea)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.lambda$onError$1$CardAttachmentsFragment$5(CardAttachmentsFragment.java:484)
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: {"status":500,"message":"Sharing is disabled","exception":{"\u0000*\u0000message":"Sharing is disabled","\u0000Exception\u0000string":"","\u0000*\u0000code":0,"\u0000*\u0000file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/lib\/private\/Share20\/Manager.php","\u0000*\u0000line":699,"\u0000Exception\u0000trace":[{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/lib\/private\/Share20\/Manager.php","line":717,"function":"canShare","class":"OC\\Share20\\Manager","type":"-\u003E","args":[{}]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/apps\/deck\/lib\/Service\/FilesAppService.php","line":206,"function":"createShare","class":"OC\\Share20\\Manager","type":"-\u003E","args":[{}]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/apps\/deck\/lib\/Service\/AttachmentService.php","line":200,"function":"create","class":"OCA\\Deck\\Service\\FilesAppService","type":"-\u003E","args":[{"cardId":43,"type":"file","data":null,"lastModified":1635492251,"createdAt":1635492251,"createdBy":"MaRitt","deletedAt":0,"extendedData":[],"id":null}]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/apps\/deck\/lib\/Controller\/AttachmentApiController.php","line":72,"function":"create","class":"OCA\\Deck\\Service\\AttachmentService","type":"-\u003E","args":["43","file",null]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":217,"function":"create","class":"OCA\\Deck\\Controller\\AttachmentApiController","type":"-\u003E","args":["43","file",null]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"-\u003E","args":[{},"create"]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/lib\/private\/AppFramework\/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"-\u003E","args":[{},"create"]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/lib\/private\/Route\/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\AttachmentApiController","create",{},{"apiVersion":"1.0","boardId":"4","stackId":"8","cardId":"43","_route":"deck.attachment_api.create"}]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"-\u003E","args":["\/apps\/deck\/api\/v1.0\/boards\/4\/stacks\/8\/cards\/43\/attachments"]},{"file":"\/home\/.sites\/783\/site2045994\/web\/cat\/sc\/cloud\/index.php","line":48,"function":"handleRequest","class":"OC","type":"::","args":[]}],"\u0000Exception\u0000previous":null}}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1195)
	at android.os.Binder.execTransact(Binder.java:1159)

```

**Comment by stefan-niedermann** [comment]
ping @MaRitt89 - please answer [my questions above](https://github.com/stefan-niedermann/nextcloud-deck/issues/1137#issuecomment-954786193).

**Comment by stefan-niedermann** [comment]
[Closing due to missing feedback](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed). Feel free to reopen answering [my questions](https://github.com/stefan-niedermann/nextcloud-deck/issues/1137#issuecomment-954786193) so we can provide support.
