### ISSUE TITLE
Test Deck Android `master` branch (= SSO `0.6.0`) with Files `3.17.1` on Android `5.1`

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#1167]
On my local emulator i am experiencing issues with the combination mentioned in the title.

Android `11` and `12` work properly, but the exceptions seem to be unrelated to the Android version.

I already catched the exceptions and display a hint, that Files `3.18.x` should be used, but i'd like to
1. verify that there actually *is* an issue
2. understand the cause
3. know the exact Android versions that behave odd

before we can release a new version of Deck Android.

**Comment by desperateCoder** [comment]
Just tested it, here we go:

```
App Version: 1.19.6
App Version Code: 1019006
Server App Version: 0.6.4
App Flavor: dev

Files App Version Code: 30170190

---

OS Version: 3.10.0+(6695563)
OS API Level: 22
Device: generic_x86
Manufacturer: unknown
Model (and Product): Android SDK built for x86 (sdk_google_phone_x86)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: com.nextcloud.android.sso.QueryParam
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by stefan-niedermann** [comment]
Well, this leads to the question:
- Why does this work on newer Android versions?
- What is the latest supported Android Version for a SSO `0.6.0` / Files `3.17.1` combination?

**Comment by stefan-niedermann** [comment]
Deck Android  `1.20.x` will require Nextcloud Android `3.18.x` or higher. Since this version has already been released, this issue is obsolete.
