### ISSUE TITLE
Crash after account selection on Nexus 5X

### ISSUE THREAD

**Issue by raumneun** [stefan-niedermann/nextcloud-deck#12]
First of all, thanks for the effort and I'm looking forward to your app! I just cloned the master branch and compiled in android studio, however, it does not work for me as I get an FC after account selection on my Nexus 5X. I know, it's far from productive state, but I thought I'd let you know anyway.
I have Android 6.0.1 (SDK 23) on my phone (rather old cyanogenmod installation...) and NC14 with Deck 0.50 (newest release) running and the nextcloud files app from f-droid installed (v 3.3.2).
This is the logcat output:
```
11-21 21:24:19.906 31831-31831/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.client, PID: 31831
    Theme: themes:{default=overlay:it.lucci.cm.greyscaletheme, iconPack:system, com.android.systemui=overlay:it.lucci.cm.greyscaletheme, com.android.systemui.navbar=overlay:it.lucci.cm.greyscaletheme}
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
        at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:106)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5461) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
Privacy guard is turned off for both files app and deck, also firewall is currently deactivated for testing.
Actually, the files app seems to be crashing with a NPE.

**Comment by desperateCoder** [comment]
Hi @raumneun,
thanks for your feedback! 

According to the stacktrace, i guess it is an issue with Nextcloud SSO, maybe in the communication between the SSO-code and the files app. Maybe @David-Development or @AndyScherzinger could have a look at this?

Sorry for the slow progress btw, I'd wish, we could have more spare time for this...

**Comment by raumneun** [comment]
Just a quick update: I changed from the old cyanogen mod install to newest lineage OS and it works now. After selecting the account, there was a dialog if Nextcloud Deck should be allowed to access accounts. On the old install, it crashed before that. Maybe that helps with finding the issue.
New android version is 8.1.0, API 27.

> Sorry for the slow progress btw, I'd wish, we could have more spare time for this...
I really appreciate that you guys spent your spare time on this, absolutely no need to apologize for giving your time for free to the community ;)

**Comment by tobiasKaminsky** [comment]
@raumneun what Android version was your "old cyanogenmod"?

**Comment by raumneun** [comment]
@tobiasKaminsky as stated in the first post, that was Android 6.0.1 (SDK 23)

**Comment by tobiasKaminsky** [comment]
@David-Development this should be working on 6.x, or?

**Comment by David-Development** [comment]
@tobiasKaminsky So sorry for the delay, completely missed this issue as I was on vacation at the time.

The single sign on should work on Android 6. 

I'm not sure what's happening here.. Looks like the account is not properly configured..?

```java
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.accounts.Account.name' on a null object reference
        at com.owncloud.android.ui.activity.SsoGrantPermissionActivity.onCreate(SsoGrantPermissionActivity.java:106)
```

This exception is thrown in the Nextcloud Files app and the exception is then passed on to the deck app where the stacktrace is printed. 

I don't know why the "android.accounts.Account.name" field should be `null`.. 

@raumneun you did setup an account in the files app first, right?

**Comment by raumneun** [comment]
@David-Development: Yes I did. Since the phone is reset, I cannot really reproduce the problem on that device anymore. However, my wife has a stock Samsung J5 duos and it shows the same behaviour. Since Android version, availability of GAPPS, device itself, absence/presence of privacy functions (privacy guard, trust,....) are different for my old phone and the J5, these things cannot really be a problem... Also, the files app was installed and used before even installing deck. Also tried out with fresh installs from files app and only one account, all leading to the same crash.
I'm happy to try out things and show you some stacktraces if you have any idea what to do to reproduce the problem ;)

**Comment by David-Development** [comment]
@raumneun Sorry for the delay. I'm glad to hear that it's working on your device now! 

About your wifes phone.. I have no idea what could cause this issue. I'm guessing you already updated to the latest version of both the files app and the deck app?

Does your wifes phone show the same stacktrace you provided? Or does it crash with a different stacktrace?

**Comment by stefan-niedermann** [comment]
@raumneun can you please retry with the latest master? Lots of changes have been made and the app should be more reliable and stable.

Feel free to reopen, if the issue still occurs.

**Comment by desperateCoder** [comment]
@raumneun we have also changed the complete persistence, so you would have to uninstall the app and reinstall it before testing. Thanks in advance!
