### ISSUE TITLE
Unexplanation app's behavior

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1242]
**Describe the bug**

In mobile app there are was created a new deck with new list and card. When I've tried to rename and save list the app showed window with error massage (see in Stacktrace below). After I closed the error's window the list was renamed but will not synced with Deck server.
And I couldn't do nothing at all to resolve this issue. As every time I had tried to rename I meet the same issue.
Then I was forsed to remove this deck and add another one over server app. So now it's work fine.

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Versions**

 - Nextcloud: 23.0.0
 - Nextcloud Deck: 1.6.1
 - Nextcloud Android: 3.19.1
 - Nextcloud Android Deck: 1.20.0

**Smartphone (please complete the following information):**
- Device: Honor 10L
- Android-Version: 10
- App-Store:
  - Google Play Store

**Stacktrace**
```
App Version: 1.20.0
App Version Code: 1020000
Server App Version: 1.6.1
App Flavor: play

Files App Version Code: 30190190

---

OS Version: 4.14.116(10.0.0.221C10)
OS API Level: 29
Device: HWHRY-H
Manufacturer: HUAWEI
Model (and Product): HRY-LX1 (HRY-LX1RU)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: Ошибка выполнения запроса HTTP. Код состояния: 403
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: {"status":403,"message":"Permission denied"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1028)
	at android.os.Binder.execTransact(Binder.java:1001)
```

**Comment by stefan-niedermann** [comment]
Hi @neerro

this is an issue of the Deck server app which also happens without using the Deck Android app (compare to https://github.com/nextcloud/deck/issues/3633#issuecomment-1066962981).
