### ISSUE TITLE
Assigning users and labels on creation causes exception

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#126]
The `card` has no `localId` since it has not been created at this point in time. Assigning tries to read the `localId`, gets a `null` and tries to pass it into a `long` which causes the app to crash.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$assignUserToCard$13$SyncManager(SyncManager.java:430)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$v3bloXkwNfvrNOB8QLodq4zL8x8.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by desperateCoder** [comment]
Uhm... Why don't you just trigger save before the assignment? I mean... What should I do? Persist the card on any assignment? This would break the propagation to the server...

Please just trigger save before label- and user assignment.

**Comment by stefan-niedermann** [comment]
yep. something like this. the issue is just a reminder.
