### ISSUE TITLE
Offline usage behavior

### ISSUE THREAD

**Issue by kuumaur** [stefan-niedermann/nextcloud-deck#1295]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
#1063 
In Android App with active internet connection, but with disconnected Nextcloud Server instance, Iam getting this message Window:

```
App Version: 1.20.0
App Version Code: 1020000
Server App Version: 1.7.0
App Flavor: fdroid

Files App Version Code: 30190190

---

OS Version: 4.4.177-22626479(T510XXU5CVB1)
OS API Level: 30
Device: gta3xlwifi
Manufacturer: samsung
Model (and Product): SM-T510 (gta3xlwifieea)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "nextcloud-prod.fritz.box": No address associated with hostname
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**
mmh, well I think I do not want to see an additinal Window that tells me, that my nextcloud server is not reachable. I know that the server is not reachable, because I need to establish a vpn to sync data.
I referenced to #1063. May be I wrong in the usage.
Thanks in advance

**Screenshots**

**Versions**

 - Nextcloud: 24.0.0
 - Nextcloud Deck: 1.7.1
 - Nextcloud Android: 3.19.1
 - Nextcloud Android Deck: 1.20.0

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by desperateCoder** [comment]
Hi @kuumaur, thanks for your message!

You're right, this shouldn't interrupt the workflow. We'll see how we can mitigate this by e.g. only showing a toast that states your status.

Well update the status of this issue here.

**Comment by kuumaur** [comment]
I have tested the dev version.
As mentioned, I have synced the Boards ans card while vpn was active.
Closing vpn connection,
cleared open nextcloud deck dev app in memory,
launched nextcloud deck dev,
created a new card,
still getting a popup window.

```
App Version: 1.20.1
App Version Code: 1020001
Server App Version: 1.7.1
App Flavor: dev

Files App Version Code: 30190190

---

OS Version: 4.4.177-22626479(T510XXU5CVB1)
OS API Level: 30
Device: gta3xlwifi
Manufacturer: samsung
Model (and Product): SM-T510 (gta3xlwifieea)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "nextcloud-prod.fritz.box": No address associated with hostname
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by desperateCoder** [comment]
@kuumaur Yep, I'm dumb. I really should read my own code more carefully. I found the problem, here is a fixed version:

[(≧︿≦) APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/7177186964/artifacts/286237604)

Uninstall the current DEV app, Install this version and retest just like the version before please. I'm quite confident that this one should work.

**Comment by kuumaur** [comment]
I have tested the dev version.
As mentioned, I have synced the Boards ans card while vpn was active.
Closing vpn connection,
cleared open nextcloud deck dev app in memory,
launched nextcloud deck dev,
created a new card,
still getting a popup window.

```
App Version: 1.20.1
App Version Code: 1020001
Server App Version: 1.7.1
App Flavor: dev

Files App Version Code: 30190190

---

OS Version: 4.4.177-22626479(T510XXU5CVB1)
OS API Level: 30
Device: gta3xlwifi
Manufacturer: samsung
Model (and Product): SM-T510 (gta3xlwifieea)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "nextcloud-prod.fritz.box": No address associated with hostname
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by kuumaur** [comment]
Mmmh, maybe Iam doing things wrong.
I have test my workflow again, but the window pops up again.
- wifi connection is established
- deinstalled old  dev version of nextcloud dev app
- installed new dev version of nextcloud dev app
- established vpn connection over wifi
- opened nexxtcloud deck dev app and imported account and board data
- killed/cleared nextcloud deck dev app
- disconnect vpn
- opened nextcloud deck dev app again
- created a card
- window pops up

```
App Version: 1.20.1
App Version Code: 1020001
Server App Version: 1.7.1
App Flavor: dev

Files App Version Code: 30190190

---

OS Version: 4.4.177-22626479(T510XXU5CVB1)
OS API Level: 30
Device: gta3xlwifi
Manufacturer: samsung
Model (and Product): SM-T510 (gta3xlwifieea)

---

it.niedermann.nextcloud.deck.exceptions.OfflineException: Connection refused
	at it.niedermann.nextcloud.deck.api.ServerCommunicationErrorHandler$Handler.handle(ServerCommunicationErrorHandler.java:50)
	at it.niedermann.nextcloud.deck.api.ServerCommunicationErrorHandler.translateError(ServerCommunicationErrorHandler.java:26)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer$1.accept(RequestHelper.java:41)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer$1.accept(RequestHelper.java:38)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onError(ObservableFromPublisher.java:51)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:133)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

> @kuumaur Yep, I'm dumb. I really should read my own code more carefully. I found the problem, here is a fixed version:
> 
> [(≧︿≦) APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/7177186964/artifacts/286237604)
> 
> Uninstall the current DEV app, Install this version and retest just like the version before please. I'm quite confident that this one should work.

Mmmh, maybe Iam doing things wrong.
I have test my workflow again, but the window pops up again.
- wifi connection is established
- deinstalled old  dev version of nextcloud dev app
- installed new dev version of nextcloud dev app
- established vpn connection over wifi
- opened nexxtcloud deck dev app and imported account and board data
- killed/cleared nextcloud deck dev app
- disconnect vpn
- opened nextcloud deck dev app again
- created a card
- window pops up

```
App Version: 1.20.1
App Version Code: 1020001
Server App Version: 1.7.1
App Flavor: dev

Files App Version Code: 30190190

---

OS Version: 4.4.177-22626479(T510XXU5CVB1)
OS API Level: 30
Device: gta3xlwifi
Manufacturer: samsung
Model (and Product): SM-T510 (gta3xlwifieea)

---

it.niedermann.nextcloud.deck.exceptions.OfflineException: Connection refused
	at it.niedermann.nextcloud.deck.api.ServerCommunicationErrorHandler$Handler.handle(ServerCommunicationErrorHandler.java:50)
	at it.niedermann.nextcloud.deck.api.ServerCommunicationErrorHandler.translateError(ServerCommunicationErrorHandler.java:26)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer$1.accept(RequestHelper.java:41)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer$1.accept(RequestHelper.java:38)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onError(ObservableFromPublisher.java:51)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:133)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by desperateCoder** [comment]
@kuumaur nope, the second output is kind of expected and shows that my changes worked. Instead of an `UnknownErrorException` we now get an `OfflineException`, which is exactly what i wanted to happen.

BUT: The UI should handle this one slightly differently, you shouldn't get the crash window. Instead, a small toast should have been shown. So we're getting some progress, I'll look deeper into this, and maybe @stefan-niedermann can have a look as well, since it might be UI related.

We'll update here as soon as we have any news. Thanks so far for testing! Hopefully the next version mitigates this issue once and for all.

**Comment by desperateCoder** [comment]
Hi @kuumaur, thanks for your patience! And sorry for falsely closing this issue :rofl: 

@stefan-niedermann had a look and we changed the behavior in this case. Now you should get a proper toast message instead of an exception dialog.

Please try the following version and report back. I guess you know how to test :wink: 

[ (ﾉ◕ヮ◕)ﾉ*:・ﾟ✧ APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/7288546420/artifacts/293815740)

**Comment by desperateCoder** [comment]
ping @kuumaur

**Comment by stefan-niedermann** [comment]
Closing due to missing response.
