### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by aquananu** [stefan-niedermann/nextcloud-deck#1341]
```
App Version: 1.20.2
App Version Code: 1020002
Server App Version: 1.7.1
App Flavor: fdroid

Files App Version Code: 30210290

---

OS Version: 4.14.117-perf-g02abc55(V12.5.1.0.QFHINXM)
OS API Level: 29
Device: violet
Manufacturer: Xiaomi
Model (and Product): Redmi Note 7 Pro (violet)

---

java.lang.IllegalStateException: failed to build request-body
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.bodyToStream(NextcloudRetrofitServiceMethod.java:231)
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.invoke(NextcloudRetrofitServiceMethod.java:170)
	at retrofit2.NextcloudRetrofitApiBuilder.lambda$create$0$retrofit2-NextcloudRetrofitApiBuilder(NextcloudRetrofitApiBuilder.java:30)
	at retrofit2.NextcloudRetrofitApiBuilder$$ExternalSyntheticLambda0.invoke(Unknown Source:2)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy1.uploadAttachment(Unknown Source)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.lambda$uploadAttachment$30$it-niedermann-nextcloud-deck-persistence-sync-adapters-ServerAdapter(ServerAdapter.java:282)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter$$ExternalSyntheticLambda27.getObservableFromCall(Unknown Source:12)
	at it.niedermann.nextcloud.deck.api.RequestHelper.request(RequestHelper.java:25)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.uploadAttachment(ServerAdapter.java:282)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:71)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:20)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:125)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:108)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:349)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:129)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:211)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:129)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:108)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$2$1.lambda$onResponse$0(SyncManager.java:241)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$2$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: /data/user/0/it.niedermann.nextcloud.deck/files/attachments/account-1/card-847/1662977723609.jpg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at okio.Okio.source(Okio.java:168)
	at okhttp3.RequestBody$3.writeTo(RequestBody.java:170)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.bodyToStream(NextcloudRetrofitServiceMethod.java:227)
	... 25 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7491)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 31 more

```

**Comment by desperateCoder** [comment]
Please see here: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed
