### ISSUE TITLE
Text '2022-10-14 05:00:00' could not be parsed at index 10

### ISSUE THREAD

**Issue by nickvergessen** [stefan-niedermann/nextcloud-deck#1355]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
```
App Version: 1.20.3
App Version Code: 1020003
Server App Version: 1.8.0-beta.2
App Flavor: play

Files App Version Code: 30210290

---

OS Version: 4.14.186-g7c18952d3c68(V12.5.8.0.RGGMIXM)
OS API Level: 30
Device: begonia
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8 Pro (begonia)

---

it.niedermann.nextcloud.deck.exceptions.TraceableException: Sorry, a wild error appeared!

⚠️ If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ⚠️

Failed to run traceable code with arguments:
{"id":4367,"title":"Follow up","description":"https://github.com/…/issues/273\n\nhttps://github.com/…/issues/274","stackId":91,"type":"plain","lastModified":1665581487,"lastEditor":null,"createdAt":1665398958,"labels":[{"id":133,"title":"Later","color":"F1DB50","boardId":32,"cardId":4367,"lastModified":0,"ETag":"cfcd208495d565ef66e7dff9f98764da"},{"id":1526,"title":"…","color":"FFFFFF","boardId":32,"cardId":4367,"lastModified":1655217355,"ETag":"c7810578b3f7a8b33a783c6419efdf26"}],"assignedUsers":[],"attachments":null,"attachmentCount":0,"owner":{"primaryKey":"…","uid":"…","displayname":"…","type":0},"order":0,"archived":false,"duedate":"2022-10-14 05:00:00","deletedAt":0,"commentsUnread":0,"commentsCount":0,"ETag":"2f0959791fb15f9b115c62082e5c2d86","overdue":0}
Cause: Text '2022-10-14 05:00:00' could not be parsed at index 10
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseCard(JsonToEntityParser.java:401)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseStack$13(JsonToEntityParser.java:613)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser$$ExternalSyntheticLambda11.run(Unknown Source:6)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseStack(JsonToEntityParser.java:597)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:55)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:36)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:1058)
	at com.google.gson.Gson.fromJson(Gson.java:1016)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: j$.time.format.DateTimeParseException: Text '2022-10-14 05:00:00' could not be parsed at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(SourceFile:0)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:2)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.getTimestampFromString(JsonToEntityParser.java:681)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseCard$10(JsonToEntityParser.java:454)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser$$ExternalSyntheticLambda7.run(Unknown Source:6)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	... 25 more

```

1. Go to the app and set up a new account you are using on the web interface since a long time
2. Click on avatar top right to switch to it

**Expected behavior**
List with items

**Screenshots**

**Versions**

 - Nextcloud: 25.0.0-rc.4
 - Nextcloud Deck: 1.8.0-beta.2
 - Nextcloud Android: 30210290
 - Nextcloud Android Deck: 1020003

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [x] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment]
@nickvergessen `duedate` used to be a timestamp in the past. Can you ask @juliushaertl whether this is a bug or a breaking change?

**Comment by stefan-niedermann** [comment]
Update: `duedate` had the format `2021-03-09T18:35:00+00:00"` in version `1.7.1`, while Deck `1.8.0-beta.2` returns a date with format `2022-10-20 22:00:00`.

Can this be fixed in the next Deck beta / rc?

**Comment by stefan-niedermann** [comment]
Reported in https://github.com/nextcloud/deck/issues/4112

**Comment by stefan-niedermann** [comment]
Fixed in the Deck server app
