### ISSUE TITLE
NullPointerException on creating card

### ISSUE THREAD

**Issue by kai11** [stefan-niedermann/nextcloud-deck#137]
**Describe the bug**

**To Reproduce**
1. Open App
2. Choose account
3. Clicl on floating + button
4. Write text for new card
5. See exception

**Expected behavior**
New card created

**Smartphone (please complete the following information):**
 - Device: Moto Z Play
 - Android-Version: 8.0.0
 - App version: 0.0.8

**Stacktrace**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'it.niedermann.nextcloud.deck.model.Card it.niedermann.nextcloud.deck.model.full.FullCard.getCard()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.EditActivity.saveAndFinish(EditActivity.java:150)
	at it.niedermann.nextcloud.deck.ui.EditActivity.onOptionsItemSelected(EditActivity.java:143)
	at android.app.Activity.onMenuItemSelected(Activity.java:3440)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1030)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:6259)
	at android.view.View$PerformClick.run(View.java:24732)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by kai11** [comment]
BTW it creates empty cards

**Comment by kai11** [comment]
After few updates it works fine and creates 
I had this prpb'em when on Create card dialog I saw only title text,
Now, when I see title and tabs below, it works fine

**Comment by stefan-niedermann** [comment]
Thanks dor reporting. The cards have to be created while you did not save so you can assign labels and users during the creation - but of course the should be cleaned up on error - or in the first place there should not even be an error of course :)

**Comment by kai11** [comment]
Aby idea why after fresh install on Create dialog I saw only text box, but after few data refreshes I saw full dialog with text box and tabs?

**Comment by stefan-niedermann** [comment]
The tabs and everything below are only shown as soon as the empty card has been created successfully (because otherwise assigning labels and users would result in an error since the card does not exist yet). for this reason it takes some time until the tabs are displayed. The soultion is not final yet, we are looking for better solutions which respect that assigning currently needs an existing card.

TBH i have no idea why it took you some data refreshes...

**Comment by desperateCoder** [comment]
However we need a better solution for this @stefan-niedermann. 

@kai11 can you confirm it is much faster when you are offline?

**Comment by kai11** [comment]
![Screenshot_20190920-115432](https://user-images.githubusercontent.com/5407282/65317830-36622800-dba5-11e9-93c0-c4692a0752b8.png)
![Screenshot_20190920-115426](https://user-images.githubusercontent.com/5407282/65317831-36622800-dba5-11e9-8f9c-15c9dc68638c.png)

**Comment by kai11** [comment]
First screen - after data refresh, second - immediately after install without data refresh

**Comment by desperateCoder** [comment]
So @stefan-niedermann and me decided, we will change this as follows:
@stefan-niedermann will hold all data in the UI until the user decides to save the card. No DB/Server interaction until this point. I will then take the created card and all assignments and save it to the DB and, if online, propagate it to the server as well. 

This way you should'nt have to wait and sync anymore.

**Comment by stefan-niedermann** [comment]
Fixed on master (except some minor bugs regarding labels) - Thank you for reporting and as always: Please be patient until 0.0.9 gets released :)
