### ISSUE TITLE
Error on connecting account 

### ISSUE THREAD

**Issue by gpopesc** [stefan-niedermann/nextcloud-deck#1387]
**Describe the bug**
I get an Error while trying to connect nextcloud account .
I have 2 android devices, I get the same error 

1. Open app
2. Select an existing account
3. Click connect

```
App Version: 1.20.1
App Version Code: 1020001
Server App Version: 1.7.3
App Flavor: fdroid

Files App Version Code: 30220390

---

OS Version: 4.14.116(102.0.0.255C432)
OS API Level: 29
Device: HWMRX
Manufacturer: HUAWEI
Model (and Product): MRX-W09 (MRX-W09NM)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: 105
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: Not a JSON Object: 105
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:35)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	... 13 more

```
**Expected behavior**

**Screenshots**

**Versions**

 - Nextcloud: 24.0.6
 - Nextcloud Deck:  1.7.3
 - Nextcloud Android: 3.22.3
 - Nextcloud Android Deck: 1.20.1

**Smartphone (please complete the following information):**
- Device: Huawei matepad pro and Huawei p40 oro
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Thank you for the report. This seems not to be an issue of the Deck Android app but maybe something more generic of the Nextcloud server itself. Please check out https://help.nextcloud.com/t/all-3rd-party-android-apps-stopped-working/150892 for staying up to date - unfortunately there is not much we can do on our side when the server replies an unexpected response.

Please also try opening the Deck app in the web browser and clear the storage of the Deck Android app [as described in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) - at least a Notes Android app user reported this to work.

**Comment by gpopesc** [comment]
Thank you. It the meantime I found the error: it should be full server access path under RewriteRule (s) in .htaccess file

**Comment by koug44** [comment]
@gpopesc Could you elaborate a little on your fix ?

**Comment by Aquariu** [comment]
> Thank you. It the meantime I found the error: it should be full server access path under RewriteRule (s) in .htaccess file

Can you please explain what you did in more details ? It looks weird to me that there would be a bug in the .htaccess file while I didn't even upgrade the NC version.

**Comment by Aquariu** [comment]
Dear all,
Pardon my ignorance, but I don't see the fix here and do not understand why the issue is closed. The workaround (modify .htaccess) is not described in full and if there's an explanation on why this suddenly popped up, then I failed to see it (and I apologise).

**Comment by stefan-niedermann** [comment]
This issue is closed because it is not caused by the Notes app: It can't be fixed here and it is not limited to the Notes Android app (as you can see in the linked forum thread on Nextcloud Help).

**Comment by gpopesc** [comment]
@koug44  and @Aquariu 

add in  .htaccess file from you nextcloud root your full server address.
as example in original file I have:

 _<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteCond %{HTTP_USER_AGENT} DavClnt
  RewriteRule ^$ /remote.php/webdav/ [L,R=302]
  RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]
  RewriteRule ^remote/(.*) remote.php [QSA,L]
  RewriteRule ^(?:build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
  RewriteRule ^\.well-known/(?!acme-challenge|pki-validation) /index.php [QSA,L]
  RewriteRule ^(?:\.(?!well-known)|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>_

then  modify with your full server path: 
_<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteCond %{HTTP_USER_AGENT} DavClnt
  RewriteRule ^$ https://your.server.address/remote.php/webdav/ [L,R=302]
  RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  RewriteRule ^\.well-known/carddav https://your.server.address/remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav https://your.server.address/remote.php/dav/ [R=301,L]
  RewriteRule ^remote/(.*) remote.php [QSA,L]
  RewriteRule ^(?:build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
  RewriteRule ^\.well-known/(?!acme-challenge|pki-validation) /index.php [QSA,L]
  RewriteRule ^(?:\.(?!well-known)|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>_


I hope it helps.  This was the solution in my case
