### ISSUE TITLE
IllegalStateException when adding text to description

### ISSUE THREAD

**Issue by reox** [stefan-niedermann/nextcloud-deck#1410]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

1. Use firefox and share a link to an existing card
2. Select add to description
3. Error occurs

**Expected behavior**

**Screenshots**

**Versions**

 - Nextcloud: 25.0.3
 - Nextcloud Deck: 1.8.3
 - Nextcloud Android: 
 - Nextcloud Android Deck: 

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

```
App Version: 1.20.3
App Version Code: 1020003
Server App Version: 1.8.3
App Flavor: play

Files App Version Code: 30230191

---

OS Version: 4.9.118-23733677(G960FXXUHFVG4)
OS API Level: 29
Device: starlte
Manufacturer: samsung
Model (and Product): SM-G960F (starltexx)

---

java.lang.IllegalStateException: failed to build request-body
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.bodyToStream(NextcloudRetrofitServiceMethod.java:231)
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.invoke(NextcloudRetrofitServiceMethod.java:170)
	at retrofit2.NextcloudRetrofitApiBuilder.lambda$create$0$retrofit2-NextcloudRetrofitApiBuilder(NextcloudRetrofitApiBuilder.java:30)
	at retrofit2.NextcloudRetrofitApiBuilder$$ExternalSyntheticLambda0.invoke(Unknown Source:2)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy0.uploadAttachment(Unknown Source)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.lambda$uploadAttachment$30$it-niedermann-nextcloud-deck-persistence-sync-adapters-ServerAdapter(ServerAdapter.java:282)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter$$ExternalSyntheticLambda5.getObservableFromCall(Unknown Source:12)
	at it.niedermann.nextcloud.deck.api.RequestHelper.request(RequestHelper.java:25)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.uploadAttachment(ServerAdapter.java:282)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:71)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:20)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:125)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:108)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:349)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$3.onResponse(SyncHelper.java:161)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$3.onResponse(SyncHelper.java:153)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:52)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: /data/user/0/it.niedermann.nextcloud.deck.play/files/attachments/account-1/card-1427/Screenshot_20230121-150139_Firefox.jpg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at okio.Okio.source(Okio.java:168)
	at okhttp3.RequestBody$3.writeTo(RequestBody.java:170)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.bodyToStream(NextcloudRetrofitServiceMethod.java:227)
	... 34 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8044)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 40 more

```

**Comment by reox** [comment]
Coming from  #1374, i disabled etags which seems to work (i.e. no error message) but in that case there happens nothing at after selecting the card and selecting add to description, and the apps just stays in the list view. But the link is added to the description.

**Comment by reox** [comment]
I just noticed, there is also a `FileNotFoundException` involved... i shared a couple of screenshots to a card and somehow the upload stalled in between. That might be one of the files. Could it be that this is the true issue?

**Comment by stefan-niedermann** [comment]
Yes, I also believe that the stacktrace you saw was just a symptom of a failed upload you tried earlier. The upload mechanism is not very robust yet, we have several issues about that though and will think how we can improve the attachment handling.

> there happens nothing at after selecting the card and selecting add to description, and the apps just stays in the list view. But the link is added to the description.

There should be a toast for a short time displaying "xyz was successfully added to the card description" - can you verify that you didn't just miss it?

**Comment by reox** [comment]
> There should be a toast for a short time displaying "xyz was successfully added to the card description" - can you verify that you didn't just miss it?

I already reset the app data, so now it works again flawlessly and I can no longer reproduce the issue. Maybe I missed the message back then, but I think there was no such message but just the error message. Or maybe both came at the same time and thus I missed the toast...
