### ISSUE TITLE
UNIQUE constraint failed when connecting to Nextcloud

### ISSUE THREAD

**Issue by beccon4** [stefan-niedermann/nextcloud-deck#1415]
When connecting to my Nextcloud instance I get an ### UNIQUE constraint failed error:

```
App Version: 1.21.7
App Version Code: 1021007
Server App Version: 0.6.4
App Flavor: fdroid

Files App Version Code: 30230190

OS Version: 4.4.153-perf+(16.2017.2009.087-20200826)
OS API Level: 28
Device: ASUS_X00T_6
Manufacturer: asus
Model (and Product): ASUS_X00TD (WW_X00TD)

android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Account.name (code 2067 SQLITE_CONSTRAINT_UNIQUE)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl.insert(AccountDao_Impl.java:190)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl.insert(AccountDao_Impl.java:27)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.createAccountDirectly(DataBaseAdapter.java:529)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createAccount$3$it-niedermann-nextcloud-deck-persistence-sync-SyncManager(SyncManager.java:328)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$$ExternalSyntheticLambda16.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by desperateCoder** [comment]
Is this the first account you are importing? Can you please try to delete the app data via Android App settings and retry?

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback. Please feel free to reopen answering the questions if you need further assistance.

**Comment by beccon4** [comment]
Works fine - thanks
