### ISSUE TITLE
Deck crashes after every start.

### ISSUE THREAD

**Issue by ZbyszekM** [stefan-niedermann/nextcloud-deck#1427]
````
Full Crash:

App Version: 1.19.3
App Version Code: 1019003
App Flavor: fdroid

Files App Version Code: 30230191

---

OS Version: 4.9.118-24343300(N960FXXU9FVH1)
OS API Level: 29
Device: crownlte
Manufacturer: samsung
Model (and Product): SM-N960F (crownltexx)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String it.niedermann.nextcloud.deck.model.Account.getUserDisplayName()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.accountswitcher.AccountSwitcherDialog.onCreateDialog(AccountSwitcherDialog.java:48)
	at androidx.fragment.app.DialogFragment.prepareDialog(DialogFragment.java:644)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:558)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1654)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:493)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

````

**Comment by desperateCoder** [comment]
Hi, thanks for your report. Can you please try clearing the apps storage? You then should be able to resync your account. See [here](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) how to do it.

Please report back If it worked

**Comment by ZbyszekM** [comment]
Hello,
Thanks for the reply.
I already did what you said but it didn't work. Same error appears.

**Comment by stefan-niedermann** [comment]
> I already did what you said but it didn't work.

Note that clearing the storage as described in the linked FAQ is *not* the same as un/reinstalling the app.

Is there any reason why you are using a version of the Deck Android app which is outdated since multiple **years**? Please update. If the issue persists, create a test account on your instance so we can reproduce and debug the issue.

Which version of the Deck server app are you using? (I wouldn't need to ask if you would have filled the issue template rather than deleting it. [It is there for a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).)

**Comment by ZbyszekM** [comment]
Well, I suppose that f-droid stuck in older version.
After cleaning storage in its settings, Deck installed properly and works great again.
Thank you for your help, sorry for bother you.

**Comment by stefan-niedermann** [comment]
Thank you for the feedback. Feel free to open a new issue in case the problem occurs again.
