### ISSUE TITLE
Frechheit! NC-API reagiert nicht! Batterie eingestellt

### ISSUE THREAD

**Issue by Schrgi** [stefan-niedermann/nextcloud-deck#1450]
Liebe Leud,

was mach ich falsch, Batterie, Neustart, Neuinstallation, nix hat was bracht...

Daaaaanke!!!

Grüße

![image](https://user-images.githubusercontent.com/40358405/225385108-328c0441-eec0-46ba-8433-3e68ed422f04.png)

```
App Version: 1.21.7
App Version Code: 1021007
Server App Version: 0.6.4
App Flavor: play

Files App Version Code: 30240190

---

OS Version: 4.14.186-gd5b54dace-dirty(root.20220810.192554)
OS API Level: 30
Device: Titan_Slim
Manufacturer: Unihertz
Model (and Product): Titan Slim (Titan_Slim_EEA)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die API der Nextcloud Dateien-App reagiert nicht. Dies ist höchstwahrscheinlich auf die Akkuoptimierungen Ihres Telefons zurückzuführen. Versuchen Sie, die Akkuoptimierung für beide Apps (Nextcloud Android und diese App) zu deaktivieren. In allen anderen Fällen versuchen Sie bitte, den Speicher beider Apps zu löschen.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:162)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:298)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:180)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
![f7304a95e03f510afc25dd86a9844ed70560529e6616deef67d9321d65320589](https://user-images.githubusercontent.com/40358405/225385197-4132ad60-ef29-4576-b6fe-32567a3eefdd.png)

**Comment by stefan-niedermann** [comment]
Hallo @Schrgi,

ja, das ist leider ein [bekanntes Problem der von der Nextcloud GmbH bereitgestellten Single-Sign-On-Lösung](https://github.com/nextcloud/Android-SingleSignOn/issues/162). Einige Smartphone-Hersteller beenden oder verhindern die Brücke zwischen der Deck Android App und der Nextcloud Android App.

Weiterhin könnten Sie versuchen, der Deck Android App und der Nextcloud Android App die ["Autostart"-Berechtigung zu erteilen](https://github.com/stefan-niedermann/nextcloud-deck/issues/660#issuecomment-682002392) - sofern dies auf Ihrem Gerät möglich ist und im Anschluss den [Speicher der Deck Android App noch einmal zu leeren](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) (das ist **nicht** das selbe wie eine Deinstallation, da Google bei letzterem nicht alle Daten wirklich löscht).

Sofern Sie die Akku-"Optimierungen" auf Ihrem Smartphone für beide Android Apps, Deck und Nextcloud, bereits deaktiviert haben und das Problem bestehen bleibt können wir leider auch nicht viel mehr machen. Lustig, dass hier Fehler-Reports zu den immer gleichen Herstellern hereinkommen :-/

lch kann Ihnen natürlich gerne anbieten, den Kauf via Play Store zurückzuerstatten, wenn Sie mir per Mail Ihre GoogleMail-Adresse oder die Bestell-ID Ihres Kaufes zukommen lassen: info@niedermann.it

Viele Grüße
