### ISSUE TITLE
Login failed on Android

### ISSUE THREAD

**Issue by fkieling** [stefan-niedermann/nextcloud-deck#1514]
```
App Version: 1.23.3
App Version Code: 1023003
Server App Version: 0.6.4
App Flavor: fdroid

Files App Version Code: 30250090 (PROD)

---

OS Version: 4.4.205-perf+(00WW_3_690_SP07)
OS API Level: 30
Device: DDV_sprout
Manufacturer: HMD Global
Model (and Product): Nokia 7.2 (Daredevil_00EEA)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 401
 at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:197)
 at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:180)
 at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$0$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:122)
 at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
 at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
 at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
 at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: <?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>

 at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:454)
 at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:127)
 at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:110)
 at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
 at android.os.Binder.execTransactInternal(Binder.java:1154)
 at android.os.Binder.execTransact(Binder.java:1123)

```

**Comment by stefan-niedermann** [comment]
401 = not authorized, check your main Nextcloud Android app, clear storages as described in the FAQ.

> Bug reports which do not fill the complete issue template will be closed.
