### ISSUE TITLE
Full crash when opening the app

### ISSUE THREAD

**Issue by Wurftaube** [stefan-niedermann/nextcloud-deck#1608]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Open the app
2. See error

### Expected behavior

Opening without error

### Deck Android version

1.24.1

### Deck server version

1.11.4

### Nextcloud Android version

3.28.0

### Nextcloud version

27.1.5 Enterprise

### Device

Samsung Galaxy Note 9

### Android Version

10

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30280090 (PROD)

---

OS Version: 4.9.118-24343300(N960FXXU9FVH1)
OS API Level: 29
Device: crownlte
Manufacturer: samsung
Model (and Product): SM-N960F (crownltexx)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'void it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsAdapter.applyTheme(int)' on a null object reference
	at it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsFragment.applyTheme(CardCommentsFragment.java:208)
	at it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsFragment$$ExternalSyntheticLambda6.onChanged(Unknown Source:8)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:258)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:294)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:143)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:126)
	at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:100)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3194)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:358)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7986)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

**Comment by blitzdesigner** [comment]
I second this with my error message
````
App Version: 4.2.0
App Version Code: 40020090
App Flavor: play

Files App Version Code: 30280090 (PROD)

---

OS Version: 4.19.278-g7b0944645172-ab10812814(11260668)
OS API Level: 34
Device: redfin
Manufacturer: Google
Model (and Product): Pixel 5 (redfin)

---

java.lang.RuntimeException: Unable to start receiver it.niedermann.owncloud.notes.widget.notelist.NoteListWidget: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4458)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.IllegalArgumentException: it.niedermann.owncloud.notes: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:6568)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:549)
	at android.app.PendingIntent.getActivity(PendingIntent.java:530)
	at android.app.PendingIntent.getActivity(PendingIntent.java:494)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.updateAppWidget(NoteListWidget.java:44)
	at it.niedermann.owncloud.notes.widget.notelist.NoteListWidget.onReceive(NoteListWidget.java:75)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4449)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5277)
	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5220)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3251)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
	at android.os.Binder.execTransactInternal(Binder.java:1339)


````
