### ISSUE TITLE
Deck (and Notes) apps stopped syncronizing after update - Offline exception

### ISSUE THREAD

**Issue by tezeb** [stefan-niedermann/nextcloud-deck#1619]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Open 'Nextcloud Deck' app
2. Pull down for sync
3. Offline exception show up

The issue seems related to #1604, but the resolution there does not help in my case.
It also happens in Nextcloud Notes app, but official Nextcloud client works fine.
I tried `curl` command from that issue and it works fine: `curl https://<username>:<passwod>@example.com/ocs/v2.php/cloud/capabilities?format=json -H 'OCS-APIRequest: true'`, response contains expected json.
I had Nextcloud Deck app installed previously (and working) and this started to happen with one of recent updates.
I don't remember if I ever switched 'Sync only on Wi-Fi', but I doubt it and it is currently switched off.

I've also tried updating Nextcloud server, but this did not change anything. I am using self-hosted instance without Cloudflare. 

### Expected behavior

Sync completes succesfully.

### Deck Android version

1.24.1

### Deck server version

1.9.2

### Nextcloud Android version

3.28.2

### Nextcloud version

26,28,29

### Device

Sony Xperia

### Android Version

12

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.9.2
App Flavor: fdroid

Files App Version Code: 30280290 (PROD)

---

OS Version: 4.4.302-gf0cba75d4546(eng.root.20240112.013109)
OS API Level: 32
Device: H4113
Manufacturer: Sony
Model (and Product): H4113 (H4113)

---

it.niedermann.nextcloud.deck.exceptions.OfflineException: Connection rejected
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler$Handler.handle(ServerCommunicationErrorHandler.java:52)
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler.translateError(ServerCommunicationErrorHandler.java:28)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onFailure(RequestHelper.java:95)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:920)

**Comment by stefan-niedermann** [comment]
Did you already try clearing the storage of the corresponding Android clients and reimport your account? If that does not help, please also try removing your account from the Nextcloud Android App (Not Deck nor Notes) and try setting it up again for the sake of completness. Keep in mind that un- and reinstalling apps is **not** the same.

If you don't have success please set up a temporary test account on your instance and send the credentials to info@niedermann.it

**Comment by tezeb** [comment]
I have not tried removing storage, because I didn't want to lose access to already synchronized items. But I did it afterall and while the error popup was no longer visible, the account was stuck waiting for synchronization to happen. This was the case for some time, but I didn't have time to report back with full logs.

And in the meantime, Nextcloud app has updated to version 3.29 and the issue has resolved itself.

In Notes app I also needed to clear storage for it to resolve.

Thanks for your help!
