### ISSUE TITLE
Can't load decks into Android app

### ISSUE THREAD

**Issue by erahhal** [stefan-niedermann/nextcloud-deck#1657]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Load freshly installed android app
2. Select already logged in Nextcloud account
3. 2-3 decks are imported, then an error is thrown

See [closed Deck Server issue](https://github.com/nextcloud/deck/issues/6160) for more details.

### Expected behavior

 All decks imported and the app loads

### Deck Android version

1.24.1

### Deck server version

1.13.1

### Nextcloud Android version

3.29.1

### Nextcloud version

Nextcloud Hub 8 (29.0.4)

### Device

OnePlus 11 5G, Pixel 7 Pro

### Android Version

14, LineageOS

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.13.1
App Flavor: fdroid

Files App Version Code: 30290190 (PROD)

---

OS Version: 5.15.149-gcf9863dbdbf6(ba3a229cd9)
OS API Level: 34
Device: OP594DL1
Manufacturer: OnePlus
Model (and Product): CPH2451 (CPH2449)

---

it.niedermann.nextcloud.deck.exceptions.OfflineException: Connection rejected
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler$Handler.handle(ServerCommunicationErrorHandler.java:52)
	at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler.translateError(ServerCommunicationErrorHandler.java:28)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onFailure(RequestHelper.java:95)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by desperateCoder** [comment]
Hi @erahhal, thanks for your report!

As the message states, the server has rejected the connection. Sounds like an infrastructure-issue to me. Since i saw you're running Nextcloud on Docker: Did you check your configurations on this side? I mean something like maximum-parallel-connections, PHP maximum execution time and so on? 

As you stated in the original issue, you don't get logs from nextcloud, but maybe you can check the ones of the NixOS and the PHP running inside it. I'm not too familiar with the whole Docker universe, so there also might be logs or settings regarding the connections? And did you try it more than once (which i'd recommend, since there might be server- and infrastructure-hickups any time)

All I can tell right now: We can't really do anything, if the server refuses to deliver the requested data.

**Comment by erahhal** [comment]
Yes, I've tried maybe 6-7 times. It always stops after about 3 decks.  I can look into the things you mentioned, thanks.

**Comment by erahhal** [comment]
Is it possible that there is a bug in the Android client or the sync protocol that causes a lot of duplicate or otherwise unnecessary traffic? I'm hosting Nextcloud behind HAProxy, and bumped it to 8 threads and a 100,000 connection limit, and the sync actually went farther, making it to 6 decks before it failed this time. But - it was at 15 MB/s for over a minute before this happened. I only have a few small decks, so no idea what all this traffic is.

**Comment by erahhal** [comment]
I spent an hour last night again trying to figure this out. For all gateways in the pipeline, I upped the request limit to 5 minutes. This includes haproxy at the front, and the nginx reverse proxy bundled with the docker image. I also updated the php max exec time, and fastcgi times as well. I confirmed that docker itself does not have any timing limits on network calls itself.

I don't think the timeout issue is coming from gateways. The failure happens in a minute or less after the last request to the backend. Looking at the nextcloud request log, each request takes a while, and the time between each subsequent request is longer. Before it fails, it's making like one request every few seconds, so something is getting clogged up. 

As mentioned before, Nextcloud is running perfectly fine, and none of the other dozens of apps have problems, including ones with Android clients, including the Nextcloud client itself, and the Nextcloud recipes app. Deck is doing something different.

**Comment by erahhal** [comment]
Also, after the error message on Android, requests to the deck API continue to come in when I tail the logs, so something is still happening.

**Comment by erahhal** [comment]
I think I found something. I cleaned up a lot of the stuff in the log, and found this around the time it was failing:

```
{"reqId":"O5Y68QpRaFOweRuH1ENs","level":0,"time":"2024-08-18T18:46:37+00:00","remoteAddr":"192.168.2.2","user":"erahhal","app":"no app in context","method":"GET","url":"/index.php/apps/deck/api/v1.1/boards/4/stacks/8/cards/131?","message":"Session token invalidated before logout","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.29.1","version":"29.0.4.1","data":{"user":"erahhal"}}
```

**Comment by desperateCoder** [comment]
> I think I found something

Well, looks like this might be it! Looks a lot like this one: https://github.com/nextcloud/deck/issues/5938

Might be a similar root cause as the issue above. I'd recommend opening a issue in the server project as above.

**Comment by erahhal** [comment]
Added [this issue](https://github.com/nextcloud/deck/issues/6227), thank you!

**Comment by schnillerman** [comment]
Is this the same issue as the causing this error:
```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.13.2
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 6.1.75-android14-11(S921BXXS4AXI8)
OS API Level: 34
Device: e1s
Manufacturer: samsung
Model (and Product): SM-S921B (e1sxeea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 500
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 500] for Call [GET http://localhost//index.php/apps/deck/api/v1.1/boards/105/stacks/473/cards/768] with Message:
[<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="de" data-locale="de_DE" translate="no" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
			KBC		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#021008">
		<link rel="icon" href="/themes/hetzner/core/img/favicon.ico">
		<link rel="apple-touch-icon" href="/themes/hetzner/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#021008">
		<link rel="manifest" href="/apps/theming/manifest?v=6e16d8c5" crossorigin="use-credentials">
		<link rel="stylesheet" href="/custom_apps/extract/css/style.css?v=7178aad2-14">
<link rel="stylesheet" href="/custom_apps/side_menu/css/sideMenu.css?v=dd6bfe9a-14">
<link rel="stylesheet" href="/custom_apps/sociallogin/css/styles.css?v=1df2b544-14">
<link rel="stylesheet" href="/core/css/styles.css?v=59b70a84-14">
<link rel="stylesheet" href="/core/css/header.css?v=59b70a84-14">
<link rel="stylesheet" href="/core/css/exception.css?v=59b70a84-14">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=0d6d4ea2-14">
<link rel="stylesheet" href="/core/css/guest.css?v=59b70a84-14">
		<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/extract/l10n/de.js?v=59b70a84-14"></script>
<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/extract/js/extraction.js?v=59b70a84-14"></script>
<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/side_menu/l10n/de.js?v=59b70a84-14"></script>
<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/side_menu/js/sideMenu.js?v=59b70a84-14"></script>
		<link rel="stylesheet" href="/apps/side_menu/css/stylesheet?v=3"></link><script defer nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" src="/apps/side_menu/js/script?v=3"></script>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Diese Anwendung benötigt JavaScript zum ordnungsgemäßen Betrieb. Bitte <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">aktiviere JavaScript</a> und lade die Seite neu.		</div>
	</div>
</noscript>
					<input type="hidden" id="initial-state-core-versionHash" value="IjU5YjcwYTg0Ig==">
					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
				<div class="wrapper">
			<div class="v-align">
									<header>
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						Kunterbunt Cloud					</h1>
					<div class="guest-box wide">
	<h2>Interner Serverfehler</h2>
	<p>Der Server konnte die Anfrage nicht fertig stellen.</p>
	<p>Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.</p>
	<p>Weitere Details können im Server-Protokoll gefunden werden.</p>

	<h3>Technische Details</h3>
	<ul>
		<li>Entfernte Adresse: xxx</li>
		<li>Anfragekennung: XaptpjMinNPudIHDljO5</li>
			</ul>

	</div>
				</main>
			</div>
		</div>
				<footer class="guest-box ">
			<p class="info">
				<a href="https://xxx" target="_blank" rel="noreferrer noopener" class="entity-name">KBC</a> – Krippe Kinderladen Hort<br/><span class="footer__legal-links"><a href="https://xxx/kontakt" class="legal" target="_blank" rel="noreferrer noopener">Impressum</a> · <a href="https://xxx/datenschutz" class="legal" target="_blank" rel="noreferrer noopener">Datenschutzerklärung </a></span>			</p>
		</footer>
	</body>
</html>
]
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more

```

**Comment by schnillerman** [comment]
Is this the same issue as the one causing this error?
```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.13.2
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 6.1.75-android14-11(S921BXXS4AXI8)
OS API Level: 34
Device: e1s
Manufacturer: samsung
Model (and Product): SM-S921B (e1sxeea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 500
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 500] for Call [GET http://localhost//index.php/apps/deck/api/v1.1/boards/105/stacks/473/cards/768] with Message:
[<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="de" data-locale="de_DE" translate="no" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
			KBC		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#021008">
		<link rel="icon" href="/themes/hetzner/core/img/favicon.ico">
		<link rel="apple-touch-icon" href="/themes/hetzner/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#021008">
		<link rel="manifest" href="/apps/theming/manifest?v=6e16d8c5" crossorigin="use-credentials">
		<link rel="stylesheet" href="/custom_apps/extract/css/style.css?v=7178aad2-14">
<link rel="stylesheet" href="/custom_apps/side_menu/css/sideMenu.css?v=dd6bfe9a-14">
<link rel="stylesheet" href="/custom_apps/sociallogin/css/styles.css?v=1df2b544-14">
<link rel="stylesheet" href="/core/css/styles.css?v=59b70a84-14">
<link rel="stylesheet" href="/core/css/header.css?v=59b70a84-14">
<link rel="stylesheet" href="/core/css/exception.css?v=59b70a84-14">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=0d6d4ea2-14">
<link rel="stylesheet" href="/core/css/guest.css?v=59b70a84-14">
		<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/extract/l10n/de.js?v=59b70a84-14"></script>
<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/extract/js/extraction.js?v=59b70a84-14"></script>
<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/side_menu/l10n/de.js?v=59b70a84-14"></script>
<script nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" defer src="/custom_apps/side_menu/js/sideMenu.js?v=59b70a84-14"></script>
		<link rel="stylesheet" href="/apps/side_menu/css/stylesheet?v=3"></link><script defer nonce="YzQ4OUx5Y1IzVG00blgyeGQ3V3BiZWx1R1dZZ2tYbWpZbGtpbUEzL3ZWWT06UXR0M0JFdGQ4bkxnc2hucE9QQ1FMNkFyY0ZCR3lVek5BUU5KckYyVTFXQT0=" src="/apps/side_menu/js/script?v=3"></script>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Diese Anwendung benötigt JavaScript zum ordnungsgemäßen Betrieb. Bitte <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">aktiviere JavaScript</a> und lade die Seite neu.		</div>
	</div>
</noscript>
					<input type="hidden" id="initial-state-core-versionHash" value="IjU5YjcwYTg0Ig==">
					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
				<div class="wrapper">
			<div class="v-align">
									<header>
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						KBC					</h1>
					<div class="guest-box wide">
	<h2>Interner Serverfehler</h2>
	<p>Der Server konnte die Anfrage nicht fertig stellen.</p>
	<p>Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.</p>
	<p>Weitere Details können im Server-Protokoll gefunden werden.</p>

	<h3>Technische Details</h3>
	<ul>
		<li>Entfernte Adresse: xxx</li>
		<li>Anfragekennung: XaptpjMinNPudIHDljO5</li>
			</ul>

	</div>
				</main>
			</div>
		</div>
				<footer class="guest-box ">
			<p class="info">
				<a href="https://xxx" target="_blank" rel="noreferrer noopener" class="entity-name">KBC</a> – Krippe Kinderladen Hort<br/><span class="footer__legal-links"><a href="https://xxx/kontakt" class="legal" target="_blank" rel="noreferrer noopener">Impressum</a> · <a href="https://xxx/datenschutz" class="legal" target="_blank" rel="noreferrer noopener">Datenschutzerklärung </a></span>			</p>
		</footer>
	</body>
</html>
]
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more

```

**Comment by desperateCoder** [comment]
Nope, definitely not.

Your server is actually responding, but not with the actual data in json format, but an HTML error page:

> Der Server konnte die Anfrage nicht fertig stellen.

You should check your server logs:

> Anfragekennung: XaptpjMinNPudIHDljO5

The issue is definitely on the servers side

**Comment by watchinofoye** [comment]
I have the same error, "Connection rejected", but when I go see the logs in the Nextcloud administration settings, I see this error : 

`Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1203] User xxxxxxxxxxxx already has more than 'max_user_connections' active connections at /home/xxxxxxxx/public_html/lib/private/DB/Connection.php#233 `

After some search, I've found that the solution given for that problem is to set the `max_user_connections` variable at a bigger value. Problem is I don't have permissions for editing this variable (and the service will probably not accept to modify it).

Anyway, the value for `max_user_connections` is set to 15 for me. How is it possible that it is overflowed just by getting the tables with only one connection (while other applications have not this problem) ? 
I tried to disconnect one of the other applications, but it does not change anything for the Deck application (and the other application can connect again to my account without problem).

**Comment by erahhal** [comment]
I'm noticing that if I show decks in the Tasks view, they show up, then disappear as the task count gets populated. Not sure if it's a related issue but I suspect it is.

**Comment by desperateCoder** [comment]
@erahhal Yep, probably unrelated. Might be a "database and UI out of sync" issue or something. If you have trouble with that, please file a new issue.

@watchinofoye @schnillerman @erahhal  and @NiksaVel (from https://github.com/stefan-niedermann/nextcloud-deck/issues/1703)

Can you please try the following DEV version for the initial sync:

[ᕕ(╭ರ╭ ͟ʖ╮•́)⊃¤=(————- (zipped) APK](https://github.com/stefan-niedermann/nextcloud-deck/actions/runs/12089076639/artifacts/2255028842)

see here [How to use the DEV app](https://github.com/stefan-niedermann/nextcloud-deck/blob/dupes-at-upsync/FAQ.md#using-the-dev-app)

In case you already have a DEV version installed: clear app data before trying.

**Comment by erahhal** [comment]
I'm able to load the decks with the dev build!

**Comment by NiksaVel** [comment]
I got this:

```
Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: dev

Files App Version Code: 30290290 (PROD)

---

OS Version: 6.1.68-android14-11-ge1e7d630d60a-ab11934653(8.0.0.206C431E4R2P2)
OS API Level: 34
Device: HNBVL
Manufacturer: HONOR
Model (and Product): BVL-N49 (BVL-N49EEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Card.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardUserRelationshipProvider.deleteAllExisting(CardUserRelationshipProvider.java:38)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper.fixRelations(SyncHelper.java:246)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider.goDeeper(CardDataProvider.java:166)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider.goDeeper(CardDataProvider.java:40)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:103)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:62)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:83)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:78)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:83)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:77)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$uMprfkVPCD6lUYcD_5EjkPsM_qs(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)

```

**Comment by desperateCoder** [comment]
@NiksaVel Ok, this shouldn't happen with this one anymore (although no problem on my setup :thinking:): 

[(≧︿≦) APK](https://github.com/stefan-niedermann/nextcloud-deck/actions/runs/12090287391/artifacts/2255336420)

**Comment by NiksaVel** [comment]
correct, no errors on this one

**Comment by desperateCoder** [comment]
Alright, this will be shipped in the next official update. If you run in trouble again, please let us know in a new issue. Thanks for testing!
