### ISSUE TITLE
Starting activity from TileService using an Intent is not allowed.

### ISSUE THREAD

**Issue by gnilebein** [stefan-niedermann/nextcloud-deck#1672]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

I can not create cards from TileService.

I reinstalled the deck app. But the error still a cour.

For more information see stacktrace. 

### Deck Android version

1.24.1

### Deck server version

1.13.1

### Nextcloud Android version

3.29.2

### Nextcloud version

29.0.6

### Device

Samsung Galaxy S23+

### Android Version

14

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.15.123-android13-8-28577312-abS916BXXS6CXGA(S916BXXS6CXGA)
OS API Level: 34
Device: dm2q
Manufacturer: samsung
Model (and Product): SM-S916B (dm2qxeea)

---

java.lang.UnsupportedOperationException: startActivityAndCollapse: Starting activity from TileService using an Intent is not allowed.
	at android.service.quicksettings.TileService.startActivityAndCollapse(TileService.java:501)
	at it.niedermann.nextcloud.deck.ui.tiles.EditCardTileService.lambda$onClick$0(EditCardTileService.java:24)
	at it.niedermann.nextcloud.deck.ui.tiles.EditCardTileService.$r8$lambda$tYj0jJ7M0x7Mh3eIwOvrudxHjcc(Unknown Source:0)
	at it.niedermann.nextcloud.deck.ui.tiles.EditCardTileService$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

**Comment by gnilebein** [comment]
startActivityAndCollapse(Intent intent) seems to be deprecated. You should use startActivityAndCollapse(PendingIntent):

https://developer.android.com/reference/android/service/quicksettings/TileService#startActivityAndCollapse(android.content.Intent)

**Comment by stefan-niedermann** [comment]
Yep, maybe you want to contribute a Pull Request? 🚀🙂

**Comment by gnilebein** [comment]
Unglücklicherweise bin ich kein Entwickler und mir fehlt die Entwicklungsumgebung. Daher kann ich vermutlich nichts dazu beitragen :(
