### ISSUE TITLE
Full Crash on opening App

### ISSUE THREAD

**Issue by SebastianV-2021** [stefan-niedermann/nextcloud-deck#1685]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

I clicked on the icon at my phone and was welcomed by a full Crash Message.

```
Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.10.198-android13-4-00050-g12f3388846c3-ab11920634(12235381)
OS API Level: 34
Device: bluejay
Manufacturer: Google
Model (and Product): Pixel 6a (bluejay)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'void it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsAdapter.applyTheme(int)' on a null object reference
	at it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsFragment.applyTheme(CardCommentsFragment.java:208)
	at it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsFragment$$ExternalSyntheticLambda6.onChanged(Unknown Source:8)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:258)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:294)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:143)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:126)
	at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:100)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3194)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:358)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1701)
	at android.app.Activity.performStart(Activity.java:9003)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4018)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

### Expected behavior

Open the App and show my Boards.

### Deck Android version

Keine Ahnung

### Deck server version

Keine Ahnung

### Nextcloud Android version

Keine Ahnung

### Nextcloud version

Keine Ahnung 

### Device

Google Pixel 6a

### Android Version

Aktuell

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [ ] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.10.198-android13-4-00050-g12f3388846c3-ab11920634(12235381)
OS API Level: 34
Device: bluejay
Manufacturer: Google
Model (and Product): Pixel 6a (bluejay)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'void it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsAdapter.applyTheme(int)' on a null object reference
	at it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsFragment.applyTheme(CardCommentsFragment.java:208)
	at it.niedermann.nextcloud.deck.ui.card.comments.CardCommentsFragment$$ExternalSyntheticLambda6.onChanged(Unknown Source:8)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:483)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:440)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:258)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:294)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:143)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:126)
	at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:100)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3194)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:628)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:290)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2959)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:358)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1701)
	at android.app.Activity.performStart(Activity.java:9003)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4018)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:327)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:307)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:279)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```

**Comment by stefan-niedermann** [comment]
Hello @SebastianV-2021 

sorry for experiencing such a hick up.

- Does this appear everytime you open the app?
- Or does it happen whenever you click on a (specific?) card?
- Did it happen before you actually imported your account for the first time?
- Did you already try to clear the storage and reimport your account [as described in the FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) you marked as read?

Sorry for all the questions, but given you apparently did not take a single minute to fill out the issue template we will have to ask to retrieve some more information. Without more information I can't reproduce the issue and therefore not fix it :wink: .

**Comment by SebastianV-2021** [comment]
It took me more than a minute to enter that Bug Report 🙄

I use the app since a while and didn't do anything specific. It happened once. After that I was able to open the app and use it like expected and like before.
Probably it happened because the theme of my phone changed from night mode to day mode.

Sorry if I tough you might be interested in a Bug.

**Comment by desperateCoder** [comment]
> Sorry if I tough you might be interested in a Bug.

That's why @stefan-niedermann was asking for more information. just look at the issue number: 1685. You know what that means? We had 1684 before. 

We write this app in our free time and appreciate every hint about whats wrong and try to fix everything we can. All we want in return is a little bit respect for our free time, so we don't need to ask thousand questions first, before we know whats actually the problem. That's exactly what the issue template is for. Please understand that its getting frustrating to ask the questions again, that are prepared in the issue template. 

> It took me more than a minute to enter that Bug Report 🙄 

Now imagine how long it took @stefan-niedermann to ask all these questions.  Or even to find the problem and fix it.

> I use the app since a while and didn't do anything specific. It happened once. After that I was able to open the app and use it like expected and like before.
> Probably it happened because the theme of my phone changed from night mode to day mode.

Now _**that's**_ helpful, thanks! We'll have a look and try to reproduce it. We'll reach out to you in case we have more questions.

Please don't consider this message as a front, I just want us to get along with each other, since our target seems to be the same.

**Comment by NiksaVel** [comment]
This happens to me occasionally. Both with the latest fdroid app version and the dev version you shared with me in another issue ...   It seems to happen only if I haven't accessed the app for a few hours.   I'll post the error log if/when it happens again.

**Comment by NiksaVel** [comment]
here is the same error with the fdroid app version

```
Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 6.1.68-android14-11-ge1e7d630d60a-ab11934653(8.0.0.206C431E4R2P2)
OS API Level: 34
Device: HNBVL
Manufacturer: HONOR
Model (and Product): BVL-N49 (BVL-N49EEA)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "HTTP"
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at it.niedermann.nextcloud.deck.repository.SyncRepository$3.onError(SyncRepository.java:307)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onFailure(RequestHelper.java:95)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "HTTP"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
	at it.niedermann.nextcloud.deck.remote.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 10 more

```
