### ISSUE TITLE
Cannot upload image

### ISSUE THREAD

**Issue by bege10** [stefan-niedermann/nextcloud-deck#1689]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
It looks similar to #1245 but the stack trace is different
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. Edit card
2. Tap on attachment button
3. Tap on upload button
4. select image from galery
5. Tap on add button
6. See error notification

``

### Expected behavior

Upload image

### Deck Android version

1.24.1

### Deck server version

1.12.4

### Nextcloud Android version

3.30.1

### Nextcloud version

cannot find version no. It is managed nextcloud at nextcloud.hosting.zone

### Device

Shiftphone 6mq

### Android Version

/e/OS Android 13

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.12.4
App Flavor: fdroid

Files App Version Code: 30300190 (PROD)

---

OS Version: 4.9.337-lineage+(eng.root.20241009.165926)
OS API Level: 33
Device: axolotl
Manufacturer: SHIFT
Model (and Product): SHIFT6mq (lineage_axolotl)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.onError(CardAttachmentsFragment.java:387)
	at it.niedermann.nextcloud.deck.remote.api.ResponseCallback$1.onError(ResponseCallback.java:76)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1.lambda$onError$1(DataPropagationHelper.java:70)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.util.ExecutorServiceProvider$RetryableRunnable.run(ExecutorServiceProvider.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 400
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	... 1 more
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 400] for Call [GET http://localhost//index.php/apps/deck/api/v1.0/boards/1/stacks/1/cards/4/attachments] with Message:
[{"status":400,"message":"type must be provided and must be not empty"}
]
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more

```

**Comment by NiksaVel** [comment]
I see, to have the identical error on my new phone.


`
```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.14.1
App Flavor: fdroid

Files App Version Code: 30300390 (PROD)

---

OS Version: 6.1.68-android14-11-ge1e7d630d60a-ab11934653(8.0.0.206C431E4R2P2)
OS API Level: 34
Device: HNBVL
Manufacturer: HONOR
Model (and Product): BVL-N49 (BVL-N49EEA)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.onError(CardAttachmentsFragment.java:387)
	at it.niedermann.nextcloud.deck.remote.api.ResponseCallback$1.onError(ResponseCallback.java:76)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1.lambda$onError$1(DataPropagationHelper.java:70)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.util.ExecutorServiceProvider$RetryableRunnable.run(ExecutorServiceProvider.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 400
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	... 1 more
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 400] for Call [GET http://localhost//index.php/apps/deck/api/v1.0/boards/5/stacks/18/cards/218/attachments] with Message:
]
[{"status":400,"message":"type must be provided and must be not empty"}
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more

```


I have the same setup on my old Fairphone 5 and everything (still) works okay. I've installed either the Gstore or F-droid versions of the deck app and neither will attach manually a file to a card or share to a card from another app. 
`

**Comment by desperateCoder** [comment]
Hi!
thank you for your reports!

To me, this doesn't seem to be on our side. We haven't even a parameter to provide a `type`, thus i'd suspect a weird data constellation on the servers side.

@AndyScherzinger @juliusknorr Do you have any idea, what could go wrong here? I had a quick look at the controller and services regarding Attachments in your code, but couldn't find the String in question:

> {"status":400,"message":"type must be provided and must be not empty"}

The call is the following:

> GET apps/deck/api/v1.0/boards/5/stacks/18/cards/218/attachments

**Comment by ultr41337h4xor** [comment]
Same error here, when uploading attachments through the Android app on a Fairphone 3.

**Comment by juliusknorr** [comment]
The check is performed here:

https://github.com/nextcloud/deck/blob/439c2b422e6e3055c04ca24192999116980aa155/lib/Service/AttachmentService.php#L180
https://github.com/nextcloud/deck/blob/main/lib/Validators/AttachmentServiceValidator.php#L14

The type parameter is documented in the API docs https://deck.readthedocs.io/en/latest/API/#post-boardsboardidstacksstackidcardscardidattachments-upload-an-attachment (should be set to `file` in all cases, we could probably just default to that on the server side). The error definitely indicates that the parameter is not sent along and seing it work on some devices would point to some issue on the client side then.

**Comment by NiksaVel** [comment]
Switched from fdroid to gplay store version of the main nextcloud app and everything seems to be working now. While searching the comments and forums, someone mentioned that only the gstore talk app gives notifications...   when I switched all apps to the gstore version, everything started working, both notifications and file uploads.

**Comment by desperateCoder** [comment]
Thanks @juliusknorr for clarifying!

Thats weird, we always send a type: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/remote/adapters/ServerAdapter.java#L240

@NiksaVel 

> Switched from fdroid to gplay store version of the main nextcloud app and everything seems to be working now

From the code's point of view, at least inside our app, this shouldn't make any difference. Its the same code for all releases. The only thing that might differ is the Nextcloud Files app (the main Nextcloud app), which does the actual network requests for us. And now this all starts to make sense!

@NiksaVel can you please post the versions of the F-Droid and Play Store apps, so we can compare?  @ultr41337h4xor  which version do you use? If F-Droid: does using the Play version fix it for you as well?

**Comment by NiksaVel** [comment]
Nextcloud app in play store is 3.29.2
Fdroid version is 3.30.4

Deck app in play store is 1.24.1
Fdroid is 1.24.1

**Comment by desperateCoder** [comment]
@NiksaVel thanks for the quick response! I asked our Nextcloud buddies, if there were breaking changes. Let's see what they say, I'll reach out to you as soon as I got news.

@ultr41337h4xor it would be still interesting, what version was breaking it for you ❤️

**Comment by AndyScherzinger** [comment]
Looping in @tobiasKaminsky @alperozturk96 @zetaTom then

**Comment by ultr41337h4xor** [comment]
The following combination does **not** work:

Deck app version - F-Droid, 1.24.1
Nextcloud app version - F-Droid, 3.30.4

The following combination **does** work:

Deck app version - F-Droid, 1.24.1
Nextcloud app version - Play Store, 3.29.2


However, I put a little bit of effort into this and it would seem there were indeed some breaking changes in the updates and they don't have to do with the store version of the app.

I tried the following F-Droid versions of the Nextcloud app, in combination with the 1.24.1 F-Droid version of the Nextcloud Deck app:

3.30.3
3.30.2
3.29.1

3.29.1 is the only one where uploading attachments worked. So, I'm guessing 3.29.2 (couldn't find F-Droid .apk to confirm) is the last version of the Nextcloud Android app where uploading attachments in the Android version of Nextcloud Deck works.

**Comment by tobiasKaminsky** [comment]
After long debugging session, I triggered it by manually setting type to "" in https://github.com/stefan-niedermann/nextcloud-deck/blob/148b13ad7f91df5f587e5dd44002b90b1c9fde98/app/src/main/java/it/niedermann/nextcloud/deck/remote/adapters/ServerAdapter.java#L244

It might be a wrong lead, but this way I get the exact same error message.
This obviously should not happen and is strange. 
I lack imagination how this can happen during normal app usage…

I will continue tomorrow.

**Comment by tobiasKaminsky** [comment]
> Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
> Got [HTTP 400] for Call [GET http://localhost//index.php/apps/deck/api/v1.0/boards/5/stacks/18/cards/218/attachments] with Message:
> ]
> [{"status":400,"message":"type must be provided and must be not empty"}

"GET" is something wrong on SSO library, when it catches exception.
I can see via debugger, that a correct POST is sent (and returning 400).

But still the question is, how retrofit/whatever sends an empty ("") type.

**Comment by desperateCoder** [comment]
@tobiasKaminsky 

> It might be a wrong lead, but this way I get the exact same error message.

yep, thats what i posted a few messages before, thats where things seem to go south

> "GET" is something wrong on SSO library, when it catches exception. 

it actually is. checked that just today, I'll see if i can find out why... you're right, it actually is a POST.

**Comment by tobiasKaminsky** [comment]
@bege10 @ultr41337h4xor @NiksaVel would one of you test a signed test-gplay version?
I would like to revert a change on Files app.

**Comment by NiksaVel** [comment]
I'll gladly help with any testing, just tell me what/how.

**Comment by tobiasKaminsky** [comment]
During my test I accidentally removed the stream that should be transferred and the exact same error appeared.
So I am unsure if it is about "type" or stream vs no-stream (aka data vs no-data).

Nevertheless, I have here one commit reverted, which I suspect to be the problem:
https://cloud.nextcloud.com/s/R8Y7Xk2LLD2koMx

@NiksaVel please give it a try and also test it with different files to upload, e.g. directly from camera, from files, from gallery.

Thank you!

**Comment by NiksaVel** [comment]
With this nextcloud app version I could not even log in to the deck app,
all kinds of errors popped up, even with the oldest available Fdroid deck
version.

After reverting to the play store nextcliud app version I can log in with
deck app (older version).

**Comment by tobiasKaminsky** [comment]
What kind of errors are those?
I tested it and locally it worked…

**Comment by wargreen** [comment]
> During my test I accidentally removed the stream that should be transferred and the exact same error appeared. So I am unsure if it is about "type" or stream vs no-stream (aka data vs no-data).
> 
> Nevertheless, I have here one commit reverted, which I suspect to be the problem: https://cloud.nextcloud.com/s/R8Y7Xk2LLD2koMx
> 
> @NiksaVel please give it a try and also test it with different files to upload, e.g. directly from camera, from files, from gallery.
> 
> Thank you!

I've try to install this apk.
It want to update the NC file app, then i fail.

**Comment by desperateCoder** [comment]
> I've try to install this apk.
It want to update the NC file app, then i fail.

Can you please elaborate on this? What exactly is failing?

**Comment by wargreen** [comment]
Sure, sorry for this very brief post, but i don't know what can help.

When i click on the apk, the installation of the apk start then fail.
![Screenshot_20250103-034848_Programme installation kit](https://github.com/user-attachments/assets/1c5c77c3-5c8c-4ca5-8f0c-3f1d06f2f2a7)
![Screenshot_20250103-035047_Programme installation kit](https://github.com/user-attachments/assets/9c502914-1978-438a-99ff-c6f00bf46895)

I"ve try to re-download it form your NC share but it don't exist anymore.

**Comment by kirelagin** [comment]
FTR, I am seeing this issue with Nextcloud app installed from Play Store, so that can’t be what makes the difference.

``` 
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.14.2
App Flavor: fdroid

Files App Version Code: 30300690 (PROD)

---

OS Version: 5.10.214-android13-4-00008-g62d26972ebb6-ab12324566(12657666)
OS API Level: 35
Device: panther
Manufacturer: Google
Model (and Product): Pixel 7 (panther)
 ```

**Comment by kirelagin** [comment]
Downgrading Nextcloud to 3.29.2 (from APKMirror) makes the error go away, so, yeah, there’s that. I’d gladly help test possible fixes, but the link above is dead.

**Comment by tobiasKaminsky** [comment]
> I guess, the one that seems to be the most relevant is [nextcloud/android#13452](https://github.com/nextcloud/android/pull/13452)?

Yes, this was, what I reverted. 
I created a new link: https://cloud.nextcloud.com/s/ecC55NAQWxQ2rfP

Can you give it a test?

**Comment by kirelagin** [comment]
Yes, file upload works with this apk.

Is reverting the planned long-term fix?

From reading the MR description and without being familiar with the APIs or the code, my wild guess was that maybe the type parameter never worked in the first place, and it was doing not only content length but also content type detection, but that change disabled both and revealed the issue...

**Comment by NiksaVel** [comment]
Hey guys, where are we with this, I still can't upload anything from my phone to any card. Is there a time line for a fix or a workaround in the meantime?

**Comment by stefan-niedermann** [comment]
If I understood @tobiasKaminsky correctly, this issue is/was caused by the Nextcloud Android app, *not* by Deck Android.

So why not wait for the fix of the Nextcloud Android App @tobiasKaminsky promised just one comment above and then retest?

**Comment by NiksaVel** [comment]
Yes I realise it's a problem with the nextcloud, I am posting the question
here because I am unfamiliar with the app release cycles and am using it to
run my business... I need it to work ASAP...  If we are talking about days
to weeks for fix than great, if longer I would rather try downgrading to
get functionality. Just asking for info, not pointing fingers or
complaining. Peace.

**Comment by tobiasKaminsky** [comment]
It will be in 3.30.8 RC1, so you can test soon.
