### ISSUE TITLE
Do not show already assigned users in search

### ISSUE THREAD

**Issue by nr458h** [stefan-niedermann/nextcloud-deck#170]
when I add a person to a task, it is already assigned, the app crashes with this error:

```
'android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: JoinCardWithUser.userId, JoinCardWithUser.cardId (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:832)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.JoinCardWithUserDao_Impl.insert(JoinCardWithUserDao_Impl.java:147)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.JoinCardWithUserDao_Impl.insert(JoinCardWithUserDao_Impl.java:20)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.createJoinCardWithUser(DataBaseAdapter.java:198)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$assignUserToCard$17$SyncManager(SyncManager.java:481)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$XrbnwmVO3lvX1tkdau_Q6G6nevs.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:764)
' 
```

**Comment by desperateCoder** [comment]
Hi @nr458h,
thanks for your report! 
Why would you even want to do this, if the user is already assigned?! Just kidding :yum:, that's quite embarrassing, we'll fix that asap! Thanks again!

**Comment by desperateCoder** [comment]
@stefan-niedermann the UI should maybe hide already assigned users, too. I thought, we already have that... strange.

**Comment by nr458h** [comment]
I'm on 0.0.8.8

**Comment by desperateCoder** [comment]
One more thing: i think it's quite confusing to the user, if we hide a already assigned user.
For instance:
* I have a card with @stefan-niedermann assigned.
* I am not a very smart person or i just didn't see that.
* I try to add @stefan-niedermann as an assignee.
* Why the hell wouldn't he show up? I **know** this user exists!
* This app is crap!

Status quo: you see @stefan-niedermann, select him to assign, and literally nothing changes.

To me this ticket is closed. What is your opinion on the example mentioned above @stefan-niedermann and @nr458h?

**Comment by stefan-niedermann** [comment]
No, its confusing to still see the already assigned user and it wastes space for more suggestions.

already assigned users should not be displayed in the suggestion box.

**Comment by desperateCoder** [comment]
This is something for a hacking session then. I looked it up, in the place, where the search is called, there is no card(-ID), so that's your construction site. If i change it, i'll break it. See the label (why haven't we had this label yet?)

**Comment by nr458h** [comment]
I agree to @stefan-niedermann for example Outlook handels it this way and it is clear to the user why an assigned user don't show up again.
But in-between I would be nice if I pick the user again the up doesn't crash.

**Comment by simonsan** [comment]
If the user is already assigned I would not show him in suggestions, but if the exact wording is given in search I would show the username and show a symbol (checkmark/checkboxes?) next to him that the person is already assigned. I would even propose to unassign a user by tapping the corresponding checkbox next to it or so.
