### ISSUE TITLE
Deck app for android stopped working today

### ISSUE THREAD

**Issue by NiksaVel** [stefan-niedermann/nextcloud-deck#1703]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

I have a managed nextcloud server on Ionos. Been using it for a week.
Android Deck app stopped syncing today. Cleared data and now I can not log in again.
When I select my account, I get swamped with 20 or so errors in rapid succession stating:

`App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.12.6
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 6.1.68-android14-11-ge1e7d630d60a-ab11934653(8.0.0.206C431E4R2P2)
OS API Level: 34
Device: HNBVL
Manufacturer: HONOR
Model (and Product): BVL-N49 (BVL-N49EEA)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 503
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 503] for Call [GET http://localhost//index.php/apps/deck/api/v1.1/boards/1/stacks/2/cards/76] with Message:
[<html>
<head>
<title>The page is temporarily unavailable</title>
<style>
body { font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body bgcolor="white" text="black">
<table width="100%" height="100%">
<tr>
<td align="center" valign="middle">
The page you are looking for is temporarily unavailable.<br/>
Please try again later.
<br />
fcd5346a3a5d52c266171d87e6ae677d
45211eca826e8fac9333beb17ef6486b
4a06c2a8bc2f41a9c0a3ff1b9a9dca22
</td>
</tr>
</table>
</body>
</html>
]
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more`

This also happened the first time I tried to connect to this server, but after 2 or 3 retries it just worked...    Now I've retried a dozen times and always the errors, and sometimes a crash with the following:

`Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 6.1.68-android14-11-ge1e7d630d60a-ab11934653(8.0.0.206C431E4R2P2)
OS API Level: 34
Device: HNBVL
Manufacturer: HONOR
Model (and Product): BVL-N49 (BVL-N49EEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List it.niedermann.nextcloud.deck.model.full.FullStack.getCards()' on a null object reference
	at it.niedermann.nextcloud.deck.remote.helpers.providers.StackDataProvider.goDeeper(StackDataProvider.java:64)
	at it.niedermann.nextcloud.deck.remote.helpers.providers.StackDataProvider.goDeeper(StackDataProvider.java:23)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:98)
	at it.niedermann.nextcloud.deck.remote.helpers.SyncHelper$1.onResponse(SyncHelper.java:57)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:68)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)`

I've tried clear data on the main nextcloud app and the deck app. Tried play and froid versions as well as a previous version from fdroid. Nothing changes.  Web deck works fine.

Help pls.

### Deck Android version

1.24.1

### Deck server version

1.12.6

### Nextcloud Android version

3.29.2

### Nextcloud version

28.0.7.5

### Device

Honor Magic 6 Pro

### Android Version

14

### App Store

- [X] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

Tested with my brothers local nextcloud install running the latest nextcloud version, works fine. 🤔

**Comment by desperateCoder** [comment]
Hi @NiksaVel, thanks for your report!

I'm suspecting this to be related to https://github.com/stefan-niedermann/nextcloud-deck/issues/1657#issuecomment-2495755715 

As mentioned there, I'll have a look as soon as I find some time. 

> Tested with my brothers local nextcloud install running the latest nextcloud version, works fine

This might be due to way smaller boards or just different configurations of both, apache/php and/or nextcloud. Things like maximum execution time, maximum concurrent connections and anti-flood mechanisms have a big impact to our app. Imagine how many constellations there are out there, its really hard for us to support all of them. we're not even aware about many of them... :sweat_smile:

**Comment by NiksaVel** [comment]
I have now installed the oldest deck app version from Fdroid and tried to
login. It only occasionally popped an error at first login (tried several
times), but it seems usable. Hope this helps.

**Comment by desperateCoder** [comment]
For what it's worth: I bet you can just update to the newest version now, as the initial sync is done. Should work just fine.

And yes, this information is also helpful for the further research!

**Comment by NiksaVel** [comment]
> For what it's worth: I bet you can just update to the newest version now, as the initial sync is done. Should work just fine.
> 
> And yes, this information is also helpful for the further research!

I've updated and yes, it works okay now. 
The issue that I see now is that every now and than when I open the android deck app I get an error like:
`Full Crash:

App Version: 1.24.1
App Version Code: 1024001
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

---

OS Version: 6.1.68-android14-11-ge1e7d630d60a-ab11934653(8.0.0.206C431E4R2P2)
OS API Level: 34
Device: HNBVL
Manufacturer: HONOR
Model (and Product): BVL-N49 (BVL-N49EEA)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "HTTP"
	at com.google.gson.Gson.fromJson(Gson.java:1238)
	at com.google.gson.Gson.fromJson(Gson.java:1137)
	at com.google.gson.Gson.fromJson(Gson.java:1047)
	at com.google.gson.Gson.fromJson(Gson.java:982)
	at it.niedermann.nextcloud.deck.repository.SyncRepository$3.onError(SyncRepository.java:307)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onFailure(RequestHelper.java:95)
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "HTTP"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101)
	at it.niedermann.nextcloud.deck.remote.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	... 10 more`

Which I close and reload the app and continue on my way.  Annoying but not horribly for now...

**Comment by desperateCoder** [comment]
> The issue that I see now is that every now and than when I open the android deck app I get an error

So is this fixed as well? If it is, feel free to close this ticket, we'll proceed in the other one or a new one if necessary.

**Comment by NiksaVel** [comment]
Yes, everything seems to work great now.  Thank you!
