### ISSUE TITLE
Cannot connect from a new mobile device 

### ISSUE THREAD

**Issue by sysprg1** [stefan-niedermann/nextcloud-deck#1705]
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

Cannot connect from a new mobile device. All OK in the web app. 
There are 3 boards, a new device got stuck on the 2nd board import. 
I noticed, that some new tasks hadn't been seen on the other mobile phone for a while. Opposite direction (from mobile phone to web) seemed to be always OK.
I have updated Nexcloud server from 3.0.1 to 3.0.2 recently.

### Deck Android version

1.24.1

### Deck server version

1.14.2

### Nextcloud Android version

3.29.2

### Nextcloud version

30.0.2

### Device

Samsung A52 and Samsung A54

### Android Version

14

### App Store

- [X] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.14.2
App Flavor: fdroid

Files App Version Code: 30290290 (PROD)

OS Version: 4.14.190-perf-28693687-abA525FXXSAFXJ2(A525FXXSAFXJ2)
OS API Level: 34
Device: a52q
Manufacturer: samsung
Model (and Product): SM-A525F (a52qnseea)

it.niedermann.nextcloud.deck.exceptions.OfflineException: Connection rejected
at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler$Handler.handle(ServerCommunicationErrorHandler.java:52)
at it.niedermann.nextcloud.deck.remote.api.ServerCommunicationErrorHandler.translateError(ServerCommunicationErrorHandler.java:28)
at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onFailure(RequestHelper.java:95)
at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
at java.lang.Thread.run(Thread.java:1012)

**Comment by desperateCoder** [comment]
Hi @sysprg1, thanks for your report!

Can you please try the current DEV version of the app: 

[(≧︿≦) (zipped) APK](https://github.com/stefan-niedermann/nextcloud-deck/actions/runs/12090287391/artifacts/2255336420)

Here's [how to use the DEV app](https://github.com/stefan-niedermann/nextcloud-deck/blob/dupes-at-upsync/FAQ.md#using-the-dev-app)

Please report back if this fixes the issues for you.

**Comment by sysprg1** [comment]
Hi, it looks perfect!

**Comment by desperateCoder** [comment]
Great! You can use this version for now, you'll get the dev version with the next update i guess.

I'll close this issue for now, feel free to open another one if you run into problems again! Stay safe! :relaxed:
