### ISSUE TITLE
Deck crashes: Device is currently offline

### ISSUE THREAD

**Issue by armaccloud** [stefan-niedermann/nextcloud-deck#258]
**Description**
When performing an operation in Deck, then close it (or switch to another app), it crashes.

**To Reproduce**
1. Go to a deck
2. Drag n drop a card from one stack to another
3. Close the app (background)
4. Wait a few seconds
5. A full screen error appears

**Expected behavior**
The app doesn't display an error.

**Additional information**
* The phone doesn't have a provider connection (out of reach of towers)
* The phone does have a WiFi connection with active internet
* Reproducible when using airplane mode + WiFi turned on
* When I reopen the app and close it again, the crash will reappear
* When I reopen the app and keep it open for a while (~15s), until its sync completed(?), then close it, the error does not appear anymore

**Screenshots**
![Screenshot_20200104-003624_Nextcloud_Deck](https://user-images.githubusercontent.com/9272078/71755341-72867380-2e8a-11ea-9397-b921f9a5872a.png)

**Smartphone:**
 - Device: Oneplus 5T
 - Android-Version: 9

**Stacktrace**
```
Version: 0.0.16

it.niedermann.nextcloud.deck.exceptions.OfflineException: Device is currently offline.
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.ensureInternetConnection(ServerAdapter.java:90)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.createCard(ServerAdapter.java:218)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.createOnServer(CardDataProvider.java:140)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.createOnServer(CardDataProvider.java:26)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:96)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:114)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:126)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:100)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$2.lambda$onResponse$0(SyncManager.java:142)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$2$HmLKcdr-Yq-c1o_jsLWXCec0AMo.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by desperateCoder** [comment]
Is it always an OfflineException?

Quite weird behavior... Tbh I never tried that. Yeah, we'll have a look at this. Thanks for reporting!

**Comment by armaccloud** [comment]
Yes, always an offline exception.
You're welcome, thanks for the work on this app!

**Comment by desperateCoder** [comment]
You're welcome as well! 😄

**Comment by stefan-niedermann** [comment]
@desperateCoder might this be caused by background sync? i noticed there is a bug in the UI which leads to an execution eben if it has been turned off in the settings, so it will get executed always.

**Comment by desperateCoder** [comment]
> @desperateCoder might this be caused by background sync? i noticed there is a bug in the UI which leads to an execution eben if it has been turned off in the settings, so it will get executed always.

I think it's similar. This depends on what Android does, when the app is hidden. In Theory, it could destroy the activity, but async execution is still running. as soon as it is done, it checks for the| activity not to be null, but it is. The exception is thrown without UI context and the app crashes. 

This needs further investigation, but I think it will be something like this

**Comment by armaccloud** [comment]
Doing some more testing, it seems to occur when I have the battery saver (standard android functionality) on. It blocks background processes, so sync cannot work then.

I must note however that I had background sync turned off for the test.
