### ISSUE TITLE
Crash if Label starts with a space

### ISSUE THREAD

**Issue by Nicos-git** [stefan-niedermann/nextcloud-deck#260]
**Describe the bug**
Deck crashes if you create a new card and put a space into the label field.

**To Reproduce**
1. Create a new card
2. Select label-field ("Schlagworte")
3. Enter space

**Expected behavior**
Find corresponding labels.

**Screenshots**
<img width="360" alt="Screenshot_20200109-223209" src="https://user-images.githubusercontent.com/23004061/72106690-1a3eee00-3330-11ea-86ca-f9ccf6c1b229.png">

**Smartphone (please complete the following information):**
 - Device: Sony Xperia Z3 Compact
 - Android-Version: 6.0.1

**Stacktrace**
```
Version: 0.0.16

java.lang.IllegalArgumentException: please provide a proper search term! " " doesn't seem right...
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.validateSearchTerm(DataBaseAdapter.java:515)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.searchLabelByTitle(DataBaseAdapter.java:463)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.searchNotYetAssignedLabelsByTitle(SyncManager.java:814)
	at it.niedermann.nextcloud.deck.ui.card.LabelAutoCompleteAdapter$1.lambda$performFiltering$1$LabelAutoCompleteAdapter$1(LabelAutoCompleteAdapter.java:124)
	at it.niedermann.nextcloud.deck.ui.card.-$$Lambda$LabelAutoCompleteAdapter$1$Cy3cUcWeH9yubR2OGNcJHXXRoPE.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by desperateCoder** [comment]
Ok, wow. Thanks for your report! Will be fixed in next release!

**Comment by Nicos-git** [comment]
Perfect! Thank you very much for your effort and your work!
