### ISSUE TITLE
NPE on Labels

### ISSUE THREAD

**Issue by AndyScherzinger** [stefan-niedermann/nextcloud-deck#29]
@desperateCoder maybe you have an idea :)

actual master keeps crashing for me every once in a while:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Label.getLocalId()' on a null object reference
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$3.onResponse(SyncManager.java:173)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$3.onResponse(SyncManager.java:123)
        at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.lambda$accept$0(RequestHelper.java:95)
        at it.niedermann.nextcloud.deck.api.-$$Lambda$RequestHelper$ResponseConsumer$bhqy13PaF1IbxLhOB_pn8whheHA.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by tobiasKaminsky** [comment]
How can you trigger this?
I do not even get any deck/column/card displayed in the app.

**Comment by desperateCoder** [comment]
@AndyScherzinger I guess this problem is already gone?

**Comment by AndyScherzinger** [comment]
I guess os, yes
