### ISSUE TITLE
rapidly moving cards makes app crash

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#329]
**Describe the bug**
Fastly move cards, no matter if cross or same stack

**Stacktrace**
```
App Version: 0.4.0
App Version Code: 4000
App ID: it.niedermann.nextcloud.deck.play
Files App Version Code: 30100190

---

OS Version: 3.18.71-perf-gb1fdd91-00485-gfd80c92(548)
OS API Level: 26
Device: ailsa_ii
Model (and Product): ZTE A2017G (P996A04_O)

---

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
 at java.util.ArrayList.get(ArrayList.java:437)
 at androidx.viewpager.widget.ViewPager.performDrag(ViewPager.java:2324)
 at androidx.viewpager.widget.ViewPager.onTouchEvent(ViewPager.java:2242)
 at android.view.View.dispatchTouchEvent(View.java:11786)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2955)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2961)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2650)
 at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:472)
 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1828)
 at android.app.Activity.dispatchTouchEvent(Activity.java:3338)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
 at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:434)
 at android.view.View.dispatchPointerEvent(View.java:12025)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4824)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4638)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4176)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4229)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4195)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4322)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4203)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4379)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4176)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4229)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4195)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4203)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4176)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6697)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6671)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6632)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6800)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(

MessageQueue.java:325)
 at android.os.Looper.loop(Looper.java:142)
 at android.app.ActivityThread.main(ActivityThread.java:6610)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

**Comment by desperateCoder** [comment]
possible solution: https://stackoverflow.com/questions/29246783/viewpager-fast-swipes-gives-indexoutofboundsexception
