### ISSUE TITLE
App-Crash when moving card right after unlock

### ISSUE THREAD

**Issue by nidomiro** [stefan-niedermann/nextcloud-deck#353]
**Describe the bug**
The App crashed while Moving a card right after unlocking the Screen (It was locked for some Time). 
My assumption (without looking at the code) is, that it was caused by a timing-problem with the Sync and drag and drop [Drag Started, then Sync, on Drop the reference was null, because of the Sync].

**To Reproduce**
As of now, I could not reproduce the crash.
I will edit this section if it is reproducable.

**Expected behavior**

**Stacktrace**
```
App Version: 0.5.2
App Version Code: 5002
App ID: it.niedermann.nextcloud.deck.play
Files App Version Code: 30100190

---

OS Version: 3.4.113-lineageos-g9fc6b38(486b2fc241)
OS API Level: 28
Device: klte
Model (and Product): SM-G900F (lineage_klte)

---

java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView it.niedermann.nextcloud.deck.databinding.FragmentStackBinding.recyclerView' on a null object reference
	at it.niedermann.nextcloud.deck.ui.stack.StackFragment.getRecyclerView(StackFragment.java:130)
	at it.niedermann.nextcloud.deck.ui.helper.dnd.DraggedCardLocalState.onDragStart(DraggedCardLocalState.java:32)
	at it.niedermann.nextcloud.deck.ui.helper.dnd.CrossTabDragAndDrop.lambda$register$0$CrossTabDragAndDrop(CrossTabDragAndDrop.java:58)
	at it.niedermann.nextcloud.deck.ui.helper.dnd.-$$Lambda$CrossTabDragAndDrop$U8QGj9I-evy-0XxmP2m0hN1g4dQ.onDrag(Unknown Source:6)
	at android.view.View.callDragEventHandler(View.java:24262)
	at android.view.View.dispatchDragEvent(View.java:24253)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1674)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewGroup.notifyChildOfDragStart(ViewGroup.java:1820)
	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1667)
	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:6348)
	at android.view.ViewRootImpl.access$1000(ViewRootImpl.java:132)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4236)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by stefan-niedermann** [comment]
Thank you for the report.

This might get fixed by #333 because we basically rewrote the whole part.
