### ISSUE TITLE
Crash when opening unsynchronised card

### ISSUE THREAD

**Issue by Nicos-git** [stefan-niedermann/nextcloud-deck#363]
**Describe the bug**
Well, I'm not sure if it's my OS or a bug in Deck.
When I try to open an unsyncronised card, Deck crashes with NullPointerException.

**To Reproduce**
1. Switch to airplane mode
2. Create a new card and insert any title
3. Save card (sync icon apears)
4. Reopen card

**Expected behavior**
To see my original card ;)

**Screenshots**
Will be provided if it helps.

**Smartphone (please complete the following information):**
 - Device: Xperia Z3 Compact
 - Android-Version: 9 / Lineage 16

**Stacktrace**
```
App Version: 0.5.2
App Version Code: 5002
App ID: it.niedermann.nextcloud.deck
Files App Version Code: 30110090

---

OS Version: 3.4.113-gbd06661(f73bfdef74)
OS API Level: 28
Device: z3c
Model (and Product): Xperia Z3 Compact (lineage_z3c)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.card.CardAttachmentsFragment.lambda$null$0$CardAttachmentsFragment(CardAttachmentsFragment.java:115)
	at it.niedermann.nextcloud.deck.ui.card.-$$Lambda$CardAttachmentsFragment$EKi0F_h1UrhMg-kOoZBOZRtOv68.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by desperateCoder** [comment]
Hi @Nicos-git, thanks for your report!
Nope, I guess that's our fault, gonna be fixed!

**Comment by stefan-niedermann** [comment]
Thanks for the report. Will be fixed in `0.6.0`. Please let us know if you stumble upon this issue again :)

**Comment by stefan-niedermann** [comment]
`0.6.0` has been tagged today and should be available on F-Droid in a few days.

**Comment by nicolas-it** [comment]
Perfectly fixed :)
Thanks for your work, I really appreciate it!

**Comment by stefan-niedermann** [comment]
You're welcome 🙂
