### ISSUE TITLE
Cleanup after failed upload of attachment

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#429]
When uploading the **exact same attachment 2 times** to the same card, the server starts burning and gets mad and returns status 500.

The problem is, that the attachment is still in our local database and everytime one tries to sync, the log is spammed with 500 errors.

Also this leads to the attachment being present in the card forever with a `DBStatus.LOCAL_EDITED`

See documentation in `SyncManager#addAttachmentToCard`.

Sample stacktrace:

```
2020-04-27 13:03:40.770 32460-1263/it.niedermann.nextcloud.deck.dev E/DeckLog: onError() (IResponseCallback.java:21) -> com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:202)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
        at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:98)
        at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
        at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: {"status":500,"message":"File already exists."}
    
        at com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:373)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:176)
        at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:64)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by stefan-niedermann** [comment]
Cleanest ways would probably be to ask @juliushaertl to return a clean `409 Conflict` http status code instead of a generic `500 Internal Server Error` in case that the "File already exists".

@juliushaertl if you agree, i will open an issue in your repository.

**Comment by juliushaertl** [comment]
Ah right, that will already be the case with 1.0, but please open an issue for the docs :wink:

**Comment by stefan-niedermann** [comment]
Thanks :) Another breaking change! :smiling_imp: Any further surprises? :laughing: 

@desperateCoder this is your turn now. Go catch whatever jus throws in this case now and delete the local attachment from the database. The UI should already give the user a hint, but the zombie-attachment is still there.

**Comment by desperateCoder** [comment]
@stefan-niedermann should i handle both versions (409 && 500) or only the new one?

I'd tend to handle both codes with the given message equally

**Comment by stefan-niedermann** [comment]
Since we did not support this error case yet, i am personally fine with only supporting the new message. It does not make the situation worse for users and we plan to raise the minimum supported server version to `1.0.0` in a few months.

But if you want to, you can handle both cases of course - But keep in mind to not forget to drop this support when we raise the version. Tip: for differences between versions, i add methods in `Version`-class like `supportsComments`, maybe this can be interesting for you to track the differences across version.

**Comment by desperateCoder** [comment]
done. i only handle 409.
