### ISSUE TITLE
Create boards

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#43]
# Remaining work

- [x] When selecting a color, the previous color has to be deselected
- [x] Depending on screen size and resolution, not all colors are displayed yet

# Current state

Creating new boards is already possible

![grafik](https://user-images.githubusercontent.com/4741199/54840208-c2fe5d00-4ccc-11e9-9c73-4b050299a519.png)

**Comment by stefan-niedermann** [comment]
fyi @desperateCoder creating boards with

```java
Board b = new Board();
b.setTitle(boardName);
syncManager.createBoard(account.getId(), b);
```

causes currently this exception:

```
2019-03-22 11:48:58.844 16513-16556/it.niedermann.nextcloud.deck E/AndroidRuntime: FATAL EXCEPTION: Thread-10
    Process: it.niedermann.nextcloud.deck, PID: 16513
    android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.BoardDao_Impl.insert(BoardDao_Impl.java:186)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.BoardDao_Impl.insert(BoardDao_Impl.java:32)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.createBoardDirectly(DataBaseAdapter.java:252)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.createInDB(BoardDataProvider.java:34)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.createInDB(BoardDataProvider.java:15)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:22)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createBoard$1(SyncManager.java:163)
        at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$Ck_yhv6TIQA6kbdYHFxUQiT27R8.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
2019-03-22 11:48:58.853 16513-16556/it.niedermann.nextcloud.deck I/Process: Sending signal. PID: 16513 SIG: 9

```

**Comment by desperateCoder** [comment]
The combination of Account ID and remote Id already exists. Do you set the remote Id? That would be a bad idea. Don't set any ID!

If this is not the case: what data exactly do you want to save? Post a json or stuff.

**Comment by AndyScherzinger** [comment]
Nice work 👍

**Comment by stefan-niedermann** [comment]
Iam not very happy with it, code-wise it's a bit dirty. But it works for now and we can refactor it at a later point...

**Comment by AndyScherzinger** [comment]
Sounds good, refactoring at a later time shouldn't be an issue :)

**Comment by stefan-niedermann** [comment]
Refactored in 7df89b45322fd23c5485d217a1635f7e35b851e7 4b40b781b2d749b020973f4a36f28a71fe21e9e1 7a8f47581fe6347daefcb44fc2891454ea2aec63 7a8f47581fe6347daefcb44fc2891454ea2aec63 476df50b4697d2ca1c476158f101a6614af8b9d5 b87d14021dfc7c70fe5c49c48207616bb7ca06e7 79aa5d90c6e54914adbdf2c3506c90c9c08915f7 80fffd440ed790f2d76cc6f7f03afdf864cffb86
