### ISSUE TITLE
Three sample tasks on fresh server setup cause sync errors

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#448]
Given you have a clean new server setup and sync the very first time with the android app
When you change one of the example tasks
Then it will cause sync errors until you delete the changed example task.

See `FIXME` hint in https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/helpers/providers/CardDataProvider.java#L75-L80

This might also be a server issue, i am not sure.

```
App Version: 1.0.2
App Version Code: 1000002
App Flavor: dev

Files App Version Code: 30110190

---

OS Version: 4.14.112+(5775370)
OS API Level: 29
Device: generic_x86_64
Manufacturer: unknown
Model (and Product): Android SDK built for x86_64 (sdk_phone_x86_64)

---

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.toCardUpdate(CardDataProvider.java:77)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.updateOnServer(CardDataProvider.java:155)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.updateOnServer(CardDataProvider.java:28)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:93)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:111)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:126)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:100)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$3$1.lambda$onResponse$0(SyncManager.java:183)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3$1$3iKicNZlgWASgTHun34YoNfq7LQ.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by desperateCoder** [comment]
Server Version? It should work on your server, mine is broken, jus knows.

**Comment by stefan-niedermann** [comment]
it was on a `1.0.0-beta2` (not yours).

**Comment by desperateCoder** [comment]
is this still a thing?

**Comment by stefan-niedermann** [comment]
Not sure, create a dummy account at your instance and try it 😉

**Comment by stefan-niedermann** [comment]
Not reproducible with client `1.4.2` and server `1.0.1`
