### ISSUE TITLE
Display activity

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#45]

**Comment by AndyScherzinger** [comment]
@nickvergessen @juliushaertl can you provide @desperateCoder with some hints how he can retrieve the activity items for a single card from the server? Thanks ❤️

**Comment by desperateCoder** [comment]
@juliushaertl would be great, that :heart:

**Comment by AndyScherzinger** [comment]
And also how we can post comments :smiley:

**Comment by juliushaertl** [comment]
For activity you can find some documentation here: https://github.com/nextcloud/activity/blob/master/docs/endpoint-v2.md

You can request the activity for a board with the object type `deck_board` and for a card with `deck_card`. The objectId is then the board or card id.

Comments: https://github.com/nextcloud/server/issues/7315#issuecomment-347468998
objectType: deckCard
objectId: the card id

**Comment by desperateCoder** [comment]
Thanks @juliushaertl!

**Comment by stefan-niedermann** [comment]
`SyncManager.syncActivitiesForCard` throws `NullPointerException`:

```
2019-09-26 21:24:09.500 4321-4321/it.niedermann.nextcloud.deck E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.niedermann.nextcloud.deck, PID: 4321
    java.lang.NullPointerException: Attempt to invoke virtual method 'void it.niedermann.nextcloud.deck.api.IResponseCallback.onError(java.lang.Throwable)' on a null object reference
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onError(SyncHelper.java:72)
        at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer$1.lambda$accept$0$RequestHelper$ResponseConsumer$1(RequestHelper.java:46)
        at it.niedermann.nextcloud.deck.api.-$$Lambda$RequestHelper$ResponseConsumer$1$pdGUKOypjSaz8W9wp-deyLX5HGQ.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by desperateCoder** [comment]
@stefan-niedermann are we done with this? close?
