### ISSUE TITLE
Error when clicking into new card title field

### ISSUE THREAD

**Issue by niccokunzmann** [stefan-niedermann/nextcloud-deck#451]
When clicking into the title field of the a new card, I got the following error message:

```
Version: 0.0.16

java.lang.NullPointerException: Attempt to invoke virtual method 'it.niedermann.nextcloud.deck.model.Card it.niedermann.nextcloud.deck.model.full.FullCard.getCard()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.EditActivity.onDescriptionChanged(EditActivity.java:277)
	at it.niedermann.nextcloud.deck.ui.card.CardDetailsFragment$2.onTextChanged(CardDetailsFragment.java:213)
	at com.yydcdut.markdown.MarkdownEditText.sendOnTextChanged(MarkdownEditText.java:246)
	at com.yydcdut.markdown.MarkdownEditText.access$300(MarkdownEditText.java:44)
	at com.yydcdut.markdown.MarkdownEditText$EditTextWatcher.onTextChanged(MarkdownEditText.java:168)
	at android.widget.TextView.sendOnTextChanged(TextView.java:9771)
	at android.widget.TextView.setText(TextView.java:5750)
	at android.widget.TextView.setText(TextView.java:5588)
	at android.widget.EditText.setText(EditText.java:122)
	at com.yydcdut.markdown.MarkdownEditText.setText(MarkdownEditText.java:393)
	at android.widget.TextView.setText(TextView.java:5545)
	at android.widget.TextView.onRestoreInstanceState(TextView.java:5413)
	at android.view.View.dispatchRestoreInstanceState(View.java:18608)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
	at android.view.View.restoreHierarchyState(View.java:18586)
	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:548)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:907)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7165)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by stefan-niedermann** [comment]
Excuse me? [I just told you in to please update the app to the latest version](https://github.com/nextcloud/deck/issues/1796#event-3302783489). `0.0.16` is **outdated** and not longer supported.

Current versions are:

- Google Play Store: `1.0.2`
- Google Play Store (Beta channel): `1.1.0`
- F-Droid: `1.0.1`

Feel free to open a new issue [using the issue template](https://github.com/stefan-niedermann/nextcloud-deck/issues/new?assignees=&labels=bug&template=bug_report.md&title=) if you encounter any bug in a current version.
