### ISSUE TITLE
Open card + backbutton crash

### ISSUE THREAD

**Issue by niccokunzmann** [stefan-niedermann/nextcloud-deck#461]
When I open a card and click the back button before the loading of the activity is complete, I received this error:

```
App Version: 1.0.1
App Version Code: 1000001
App Flavor: fdroid

Files App Version Code: com.nextcloud.client

---

OS Version: 3.0.101-lineage-g660d639(eng.rinand.20200320.082650)
OS API Level: 28
Device: GT-I9100
Manufacturer: samsung
Model (and Product): GT-I9100 (GT-I9100)

---

io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.InternalError: Thread starting during runtime shutdown
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:733)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1616)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:342)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:579)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:680)
	at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:145)
	at io.reactivex.internal.schedulers.NewThreadWorker.schedule(NewThreadWorker.java:51)
	at io.reactivex.Scheduler.scheduleDirect(Scheduler.java:203)
	at io.reactivex.Scheduler.scheduleDirect(Scheduler.java:179)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn.subscribeActual(ObservableSubscribeOn.java:36)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.Observable.subscribe(Observable.java:12270)
	at io.reactivex.Observable.subscribe(Observable.java:12198)
	at it.niedermann.nextcloud.deck.api.RequestHelper.runRequest(RequestHelper.java:31)
	at it.niedermann.nextcloud.deck.api.RequestHelper.request(RequestHelper.java:25)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.getCard(ServerAdapter.java:217)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.getAllFromServer(CardDataProvider.java:47)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doSyncFor(SyncHelper.java:34)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeper(StackDataProvider.java:63)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeper(StackDataProvider.java:19)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:58)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:34)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:56)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	... 6 more

```

**Comment by stefan-niedermann** [comment]
I am sorry, but i can't reproduce it. Even with an emulated low-end device (512 MB RAM, no hardware acceleration etc - much worse than your Galaxy S2).

I would tent to say this might be an issue of your custom rom. Are you able to reproduce this on any other device or in an emulator?

**Comment by desperateCoder** [comment]
I can reproduce this. I'll give @stefan-niedermann a stack trace as soon as possible, so no worries @niccokunzmann

**Comment by stefan-niedermann** [comment]
Jup, i recently also had it on an emulated device. Tricky one! Will have a deeper look at it.
