### ISSUE TITLE
Connection fails because "order" of a stack is null

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#465]
```
App Version: 1.1.0
App Version Code: 1001000
App Flavor: play

Files App Version Code: 30110190

---

OS Version: 4.4.153-perf+(V11.0.7.0.PFGEUXM)
OS API Level: 28
Device: lavender
Manufacturer: Xiaomi
Model (and Product): Redmi Note 7 (lavender_eea)

---

java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsInt(JsonElement.java:231)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseStack(JsonToEntityParser.java:391)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseBoard(JsonToEntityParser.java:138)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:42)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:36)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment]
@juliushaertl do you know how a stack `order` can be `null`? One of our users has a Deck instance which currently cannot get synced because one of the stacks has `order: null`. While we will try to fix this on the client (by catching the `null` and default it to `0`, this might be an issue you want to fix on the backend also?

**Comment by stefan-niedermann** [comment]
@desperateCoder your fix worked.

**Comment by juliushaertl** [comment]
Not sure why this could be the case, might be some PHP/Database magic and we do not use strict types in the deck app yet, so it is not forced to be an integer.

**Comment by stefan-niedermann** [comment]
hehe :laughing: 

```php
class Stack {
  $title: string;
  $order: surprise;
}
```

Guess we have a workaround for it, therefore no critical issue anymore. Though a little bittle tiny whiny typechecking isn't *that* bad after all :wink:

**Comment by juliushaertl** [comment]
I don't get how that could happen from the server code as the order should always be set to a numeric value from creating/updating the stack and the database mapper should not convert such a numeric value to null :see_no_evil:

**Comment by juliushaertl** [comment]
Ah the database column might be `null` so maybe it is some old table row from before the check was added.
