### ISSUE TITLE
Due date not saved when creating new cards

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#479]
Server: `1.0.0`
Client: `1.2.1`

**Comment by stefan-niedermann** [comment]
The due date is confirmed to be present in the `SyncManager` and seems to be present in the request also:

```
2020-05-10 16:55:37.624 23178-24092/it.niedermann.nextcloud.deck.dev D/com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod: invoke call to api using observable class it.niedermann.nextcloud.deck.model.full.FullCard
2020-05-10 16:55:37.626 23178-24116/it.niedermann.nextcloud.deck.dev D/com.nextcloud.android.sso.api.NextcloudAPI: performRequest() called with: type = [class it.niedermann.nextcloud.deck.model.full.FullCard], request = [NextcloudRequest(method=POST, header={}, parameter={}, requestBody={"archived":false,"attachmentCount":0,"commentsUnread":0,"description":"","duedate":"2020-05-13T11:00:45.722Z","notified":false,"order":0,"overdue":0,"stackId":53,"title":"kkk","userId":4,"accountId":2,"localId":90,"status":2}, url=/index.php/apps/deck/api/v1.0/boards/15/stacks/53/cards, token=null, packageName=null, accountName=null, bodyAsStream=null, followRedirects=false)]
    
    --------- beginning of crash
2020-05-10 16:55:37.630 23178-24092/it.niedermann.nextcloud.deck.dev E/AndroidRuntime: FATAL EXCEPTION: Thread-32
    Process: it.niedermann.nextcloud.deck.dev, PID: 23178
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.toCardUpdate(CardDataProvider.java:78)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.updateOnServer(CardDataProvider.java:156)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.updateOnServer(CardDataProvider.java:28)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:93)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createFullCard$20$SyncManager(SyncManager.java:738)
        at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$MEPZX8q8wYD3alWT5IsyKZLrs-o.run(Unknown Source:12)
        at java.lang.Thread.run(Thread.java:919)
```

Not sure though, what the `IndexOutOfBoundsException` means or where it comes from. @desperateCoder ?

**Comment by desperateCoder** [comment]
It says, the card has no owner. Why? No clue. An update of a card requires an owner, otherwise the server will reject the call.

I suspect the server is not setting an owner in some cases, so i'd like to ask @juliushaertl, could you clarify this? Is it possible, that the owner isn't set in the `Card` response in some cases?

**Comment by stefan-niedermann** [comment]
Currently not reproducible.

Original reporter:

> Okay, sorry lets close it for now and I will comment in case it happens again
