### ISSUE TITLE
Crash after deleted column

### ISSUE THREAD

**Issue by niccokunzmann** [stefan-niedermann/nextcloud-deck#482]
I deleted a column and it did not go away. Then I swiped around. 

```
App Version: 1.0.2
App Version Code: 1000002
App Flavor: fdroid

Files App Version Code: com.nextcloud.client

---

OS Version: 3.0.101-lineage-g660d639(eng.rinand.20200320.082650)
OS API Level: 28
Device: GT-I9100
Manufacturer: samsung
Model (and Product): GT-I9100 (GT-I9100)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.full.FullStack.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$onStackDeleted$23$MainActivity(MainActivity.java:937)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$jfd9YfBqhN7CXqgSTD4yh6m9tCc.onChanged(Unknown Source:4)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.LiveDataHelper$2.onChanged(LiveDataHelper.java:79)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.Transformations$3.onChanged(Transformations.java:188)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by stefan-niedermann** [comment]
Thank you for the report. Do you have more information about the environment (How many accounts, how many boards, how many stacks, which of them were empty) and exact steps to reproduce this issue?

Unfortunately it's very hard to fix a bug which can not be reproduced. :slightly_frowning_face:

**Comment by stefan-niedermann** [comment]
Closing as not reproducible. Please reopen if you can reproduce this issue with the latest version and provide the requested information.

Thank you for the report though.
