### ISSUE TITLE
Display "create"-button for labels as last item in autocomplete

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#51]
When typing in the `EditText` to search for labels, 
- [x] the last item should always be a "+ Create", so one can directly create inline new labels.
- [x] Clicking it should create and directly assign the label to the current card.

**Comment by desperateCoder** [comment]
Here you go:
In syncManager:
``` JAVA
public MutableLiveData<Label> createAndAssignLabelToCard(long accountId, Label label, long localCardId) 
```

**Comment by stefan-niedermann** [comment]
First creation throws `405` status-code from Deck-API. Second time (different label text) i get `UNIQUE constraint failed`. When i pass the label into `createAndAssignLabelToCard`, the passed label has a local-id, a static variable (so i am able to distinguish between new and existing labels). Maybe the local id should be ignored when creating new labels.

```

2019-05-16 14:26:49.266 13718-13718/it.niedermann.nextcloud.deck D/deck: onError() (IResponseCallback.java:21) -> com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 405
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:149)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
        at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:98)
        at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
        at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.Throwable: 
        at com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:303)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:132)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:111)
        at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:86)
        at android.os.Binder.execTransact(Binder.java:731)
2019-05-16 14:26:49.268 13718-13718/it.niedermann.nextcloud.deck D/deck: onError() (IResponseCallback.java:21) -> com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 405
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:149)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
        at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:98)
        at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
        at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.Throwable: 
        at com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:303)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:132)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:111)
        at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:86)
        at android.os.Binder.execTransact(Binder.java:731)
```

```
2019-05-16 14:27:14.342 13718-13783/it.niedermann.nextcloud.deck E/AndroidRuntime: FATAL EXCEPTION: Thread-18
    Process: it.niedermann.nextcloud.deck, PID: 13718
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: Label.localId (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.LabelDao_Impl.insert(LabelDao_Impl.java:158)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.LabelDao_Impl.insert(LabelDao_Impl.java:26)
        at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.createLabel(DataBaseAdapter.java:151)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.LabelDataProvider.createInDB(LabelDataProvider.java:40)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.LabelDataProvider.createInDB(LabelDataProvider.java:12)
        at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:22)
        at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$createAndAssignLabelToCard$9$SyncManager(SyncManager.java:330)
        at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$r2d1su5MEdjKAQD0y9EWETo7xMg.run(Unknown Source:10)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by desperateCoder** [comment]
Master?

**Comment by stefan-niedermann** [comment]
yes

**Comment by desperateCoder** [comment]
Since i am waiting @juliushaertl to respond, i am blocked so far. If the error is on the server side, my implementation is complete.
However, the server says:

``` JSON
{"status":403,"message":"Permission denied"}
```
My commits are tagged with the wrong issue btw, i linked it above.
