### ISSUE TITLE
RuntimeException: Exception while computing database live data

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#515]
@desperateCoder this is from a customer, only information at this time is "happens often" (I'll try to get more infos).

Maybe you read something out of this stacktrace what the cause might be?

```
App Version: 1.4.4
App Version Code: 1004004
App Flavor: play
Files App Version Code: 30120053

---

OS Version: 3.18.120-perf+(1911042107)
OS API Level: 28
Device: OnePlus3
Manufacturer: OnePlus
Model (and Product): ONEPLUS A3003 (OnePlus3)

---

java.lang.RuntimeException: Exception while computing database live data.
at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:45)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed.
at android.database.CursorWindow.<init>(CursorWindow.java:136)
at android.database.CursorWindow.<init>(CursorWindow.java:114)
at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
at androidx.room.util.DBUtil.query(DBUtil.java:86)
at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CardDao_Impl$6.call(CardDao_Impl.java:1321)
at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CardDao_Impl$6.call(CardDao_Impl.java:1316)
at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
... 4 more

```

**Comment by stefan-niedermann** [comment]
More information: Happens on sync and crashes the app (not caught).

**Comment by desperateCoder** [comment]
This is a hard one... most likely a memory leak anywhere... can we ask the affected user, if the stacktrace is always the same? If yes, maybe pagination might help, see: 
https://stackoverflow.com/a/56554830/2355392

**Comment by desperateCoder** [comment]
Maybe there is too much data fetched by some cursors, how about pagination?

**Comment by stefan-niedermann** [comment]
I think we better should have a look about what we are fetching currently.

For example: We are loading a list of `FullStacks` in the `MainActivity` to display the titles. I believe that for each `FullStack` all child `Card`s are loaded alongside. And i also think this is not necessary, because each visible column contains one `StackFragment` which is itself capable of loading and actually displaying all the `Card`s.

Therefore some more specialized `Full***` classes were a better first step IMHO, in this very example it could be a

```java
public class StackWithCardCounter {
    @Embedded
    private  Stack stack;
    
    @Relation(******)
    private int cardCount;
}
```

This approach has also limitations (if one goes crazy and has simply too much data) but it will
- fix the issues probably in the short way without completely messing up the UI code and
- will be a speed benefit for *each* user, also the ones with less cards (instead of just preventing the crash)

Of course this was just a sample and i didn't test or code anything. The classes depend highly on what the UI needs, so this needs to be analyzed and modeled before backend can implement this.

**Comment by stefan-niedermann** [comment]
Actually in the mentioned sample a pure `LiveData<List<Stack>>` is absolutely enough.

I added PR (https://github.com/stefan-niedermann/nextcloud-deck/pull/609) since it was a more or less small change but might have a big impact.

**Comment by stefan-niedermann** [comment]
Closing this in favor of smaller splitted issues (see #627)
