### ISSUE TITLE
SQLiteConstraintException

### ISSUE THREAD

**Issue by GeneralLuzi** [stefan-niedermann/nextcloud-deck#521]
Error while linking app with cloud account. Therefore not possible to use app at all.
````
App Version: 1.4.4
App Version Code: 1004004

Deck Server Version: 0.6.4

Files App Version Code: 30110190

---

OS Version: 4.14.113-18242812(G975FXXU4CTC9)
OS API Level: 29
Device: beyond2
Manufacturer: samsung
Model (and Product): SM-G975F (beyond2lteeea)

---

android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY[787])
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:1127)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:114)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.BoardDao_Impl.insert(BoardDao_Impl.java:212)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.BoardDao_Impl.insert(BoardDao_Impl.java:33)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.createBoardDirectly(DataBaseAdapter.java:409)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.createInDB(BoardDataProvider.java:42)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.createInDB(BoardDataProvider.java:23)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:44)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:34)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:64)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

````

**To Reproduce**
1. Start app
2. Link with account
3. Accept linking with account

**Expected behavior**
no error message

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S10
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [x] F-Droid

**Comment by desperateCoder** [comment]
Well, this is a strange one. According to my code a Board has two foreign keys: Account and owner (user table). If we wouldn't have an account, the sync wouldn't even start, so there has to be a problem with the owner. 

@GeneralLuzi is the information about your deck server version correct? The stacktrace says you run 0.6.4. In this case you could be affected by a server bug, where the users aren't returned correctly. Could you try upgrading your server deck app version? Then, just reinstall our Android app and connect as usual.

If this is not an option, we could also try a test account on your server to determine whats wrong, or, we could build a special version for you, which is more verbose about what is happening in the background. For now, i think the update of the server app would be the easiest and most promising solution.

Sorry for the inconveniences by the way, this users-bug affected quite a lot of our users in very different constellations. We can't do anything about released server versions and we have no chance to work around that problem. As we noticed, we told the Nextcloud server developer who fixed that quite fast, but the released versions are still out there of course...

**Comment by stefan-niedermann** [comment]
@GeneralLuzi could you please try to clear the storage of **both** apps, Nextcloud Android **and** Nextcloud Deck Android and then readd your account?

If this doesn't help neither, can you please try to create a test account and try to connect to it yourself? In this case I suspect a defect dataset on your server Deck instance.

**Comment by GeneralLuzi** [comment]
Hey,

 

on last weekend, I found the issue. It was on the server side and independent to this app. Sorry for the inconvenience. 

 

Either the server restart or the user rights of the www directory was the issue…

 

Please close this thread.

 

Thanks and BR GL

 

Von: Niedermann IT-Dienstleistungen <notifications@github.com> 
Gesendet: Montag, 15. Juni 2020 09:44
An: stefan-niedermann/nextcloud-deck <nextcloud-deck@noreply.github.com>
Cc: GeneralLuzi <andreas@hahn.to>; Mention <mention@noreply.github.com>
Betreff: Re: [stefan-niedermann/nextcloud-deck] cannot connect to cloud (#521)

 

@GeneralLuzi <https://github.com/GeneralLuzi>  could you please try to clear the storage of both apps, Nextcloud Android and Nextcloud Deck Android and then readd your account?

If this doesn't help neither, can you please try to create a test account and try to connect to it yourself? In this case I suspect a defect dataset on your server Deck instance.

**Comment by stefan-niedermann** [comment]
Thank you very much for the update and let us know if you encounter any further issues!
