### ISSUE TITLE
Is there support for NextCloud v14?

### ISSUE THREAD

**Issue by rufferson** [stefan-niedermann/nextcloud-deck#522]
**Describe the bug**

Have NC server in Alpine LXC container with latest deck app. NC is installed from the alpine repo and is v14 it seems. Deck app on the server is installed from online NC repo so should be latest. I understand there's api incompstibility but is there a workaround without pulling latest NC from the git? 
```
App Version: 1.4.4
App Version Code: 1004004
App Flavor: play

Deck Server Version: 0.6.4

Files App Version Code: 30120090

---

OS Version: 4.9.186-perf+(05200010A002000102006556692)
OS API Level: 29
Device: H8314
Manufacturer: Sony
Model (and Product): H8314 (H8314)

---

it.niedermann.nextcloud.deck.exceptions.DeckException: deck node is missing in capabilities endpoint!
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseCapabilities(JsonToEntityParser.java:350)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:51)
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
**To Reproduce**
1. Go to google appstore
2. Purchase the app
3. Start the app and select account

**Expected behavior**

well, something similar to what i have in NC web gui
**Screenshots**

**Smartphone (please complete the following information):**
- Device: (e.g. Samsung Galaxy S10)
- Android-Version: (e.g. 8)
- App-Store:
  - [x] Google Play Store
  - [ ] F-Droid

**Stacktrace**

**Comment by stefan-niedermann** [comment]
@desperateCoder this is one of the cases i also experienced with the Notes app: Under some circumstances the `capabilities` endpoint does not return any theming stuff or (more important) any installed apps.

@rufferson did you try with an admin account or with an user account?

**Comment by stefan-niedermann** [comment]
wtf just read - nextcloud 14? *fourteen*?

Honestly: No support. [Even NC 16 is officially end of support from Nextcloud GmbH](https://nextcloud.com/blog/minor-releases-18-0-5-17-0-7-and-16-0-11-are-here-end-of-support-for-16/).

So sorry, but no.

I can offer you to refund your app purchase, but don't get me wrong: We cannot support a version which is end of life for over a year now.

If you want a refund, send me the Play Store order ID via info@niedermann.it

**Comment by rufferson** [comment]
No need to get emotional, just asking :) Good luck in your effort, no need for refund, let consider it a donation for opensource project.

**Comment by stefan-niedermann** [comment]
Thank you 😄

Wasn't emotional though, just incredibly surprised that it seems like this version is really the latest version distributed by Alpine repositories 😳. Have you considered to open this as a bug in their issue tracker?

**Comment by rufferson** [comment]
Thanks for the tip, that's actually a solution, browsing over their git repo I realised the latest tip is using v18.0.6, it's just lxc profile is pinned at alpine v3.8. Switching to `latest-stable` repo moved me to the v18

**Comment by desperateCoder** [comment]
Asking the real questions: does it work now?

**Comment by stefan-niedermann** [comment]
Interesting. Let us know if you experiencing the sign up issue with v18 :)

**Comment by rufferson** [comment]
Yes I've graduallt upgraded to 17th version now (alpine v3. 11) and it started working. now just latest-stable remains

**Comment by stefan-niedermann** [comment]
Really glad to hear, thanks for the update :)

And sorry again for "getting emotional", i think my self-defense-mode was activated when i thought that this will result in another "App is shit"-rating at Play Store :smile:
