### ISSUE TITLE
Error after initial start

### ISSUE THREAD

**Issue by drissner** [stefan-niedermann/nextcloud-deck#523]
After the installation and adding my account, I got the following error message. Nonetheless, the app works fine so far. Maybe it helps you to debug
```
App Version: 1.4.4
App Version Code: 1004004
App Flavor: play

Files App Version Code: 30110190

---

OS Version: 4.9.210-g28c696160049-ab6386370(6416773)
OS API Level: 29
Device: sargo
Manufacturer: Google
Model (and Product): Pixel 3a (sargo)

---

java.lang.NullPointerException: Attempt to invoke interface method 'io.reactivex.Observable it.niedermann.nextcloud.deck.api.NextcloudServerAPI.getCapabilities()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.lambda$getCapabilities$1$ServerAdapter(ServerAdapter.java:150)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.-$$Lambda$ServerAdapter$JxOr-sUP0YarkCFN1spO6raKzxM.getObservableFromCall(Unknown Source:2)
	at it.niedermann.nextcloud.deck.api.RequestHelper.request(RequestHelper.java:33)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.getCapabilities(ServerAdapter.java:150)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$refreshCapabilities$3$SyncManager(SyncManager.java:294)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$Vcf6ydVMiyEEKL4zi0xZ8EzxGXE.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Thanks @drissner !

I will have a look, but this kind of errors are generally hard to debug and most likely caused by some kind of server hickup.

If you want to test, it would be interesting whether or not you are able to reproduce this issue after clearing the storage if the Deck Android App (Android settings -> Apps -> Deck -> Storage -> Clear storage).

In this case a test-account would be useful for debugging.

Otherwise i will close this issue as it seems to work properly for you know and i cannot reproduce it 🤷‍♀️ ..?

**Comment by drissner** [comment]
Thanks for your quick reply! I could not reproduce the error - the app works very well. Thanks a lot! You can close the issue.

**Comment by stefan-niedermann** [comment]
Great, let us know if you encounter any other issues or have a feature request 🙁 and thanks for the kind words in your rating ❤️
