### ISSUE TITLE
One account may not be synchronized with nextcloud deck, but others do

### ISSUE THREAD

**Issue by drumdum** [stefan-niedermann/nextcloud-deck#528]
**Describe the bug**
Synchronisation with my main account's deck is not possible after upgrading Nextcloud to version 17. I've already upgraded to version 18.0.6 with no success. Synchronisation with other accounts on the same Nextcloud is no problem. 

As described in another issue I deleted storage of both the Nextcloud app and the Nextcloud Deck app on android. But the problem persists. My impression is, that some information in my main account's deck let's the json parser fail, but I have no idea how to debug this.

**To Reproduce**
1. Install Nextcloud Deck app on Android freshly
2. Add an account to the app
3. "There was an issue with synchronisation. Click more"

**Expected behavior**
Synchronisation takes place and I can see and edit my deck's contents.

**Smartphone (please complete the following information):**
- Device: Motorola Z2
- Android-Version: 4.4.78
- App-Store:
  - [ ] Google Play Store
  - [x] F-Droid

**Stacktrace**
```
App Version: 1.4.4
App Version Code: 1004004
App Flavor: fdroid

Deck Server Version: 1.0.2

Files App Version Code: 30110190

---

OS Version: 4.4.78-perf-g43d884e(11)
OS API Level: 26
Device: nash
Manufacturer: motorola
Model (and Product): Moto Z (2) (nash)

---

java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsBoolean(JsonElement.java:153)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseAcl(JsonToEntityParser.java:201)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseBoard(JsonToEntityParser.java:149)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:41)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:36)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment]
@drumdum 

are you able to do the following `curl` requests for the non-working and for a working account?

`curl "https://username:password@example.com/ocs/v2.php/cloud/capabilities?format=json" -H 'OCS-APIRequest: true'`

Can you categorize which of the accounts are Admins or Non-Admins? e. g: "All working users are Admin, the non-working user is not an admin"?

@desperateCoder I noticed in an issue in the Notes app (https://github.com/stefan-niedermann/nextcloud-notes/issues/854#issuecomment-640090791) that the `capabilities` endpoint seems to return shit if the user is not an Admin. Maybe this is the cause here, too...

**Comment by desperateCoder** [comment]
The stacktrace states there is a problem parsing the ACL of a board, the capabilities have to be fine here. A deep dive in the code brought me to this line:
```java
acl.setPermissionShare(aclJson.get("permissionShare").getAsBoolean());
```
Looks to me like a very weird response, since EDIT and MANAGE worked well before, but not the SHARE. I'd suggest catching all exceptions while parsing and include them in a single stacktrace including the json, which we weren't able to parse. this might make thins much easier.

@drumdum please check the rights-constellation of your boards via web-app, maybe there is something broken there? I'll definitely enhance the error message here, so we can easily see where the problem exactly is. But for now i have to admit, that we are almost blind here.

**Comment by drumdum** [comment]
@stefan-niedermann thank you for the new version. The debug messages now are very informative. I could find the board causing the error and was able to get it to work afterwards. First I removed the share and reshared it then. The Android app now synchronizes as aspected. Although I use the circles app this share was with one user only.

Thank you for your good work with this app as it really eases the use of Nextcloud Deck a lot.

**Comment by stefan-niedermann** [comment]
You're welcome, credits to @desperateCoder :wink:

@drumdum Is it possible that you give us more information about the nature of the error? I mean: Was it a fault of the Android app or was there a defect dataset on your server instance?

**Comment by desperateCoder** [comment]
@drumdum glad, it worked out for you! 

To prevent such errors in the future, could you give us a hint, what exactly was wrong with this share? 

The nextcloud ecosystem is so huge, so we never could test any constellation out there, so this kind of feedback is very valuable to us!

**Comment by drumdum** [comment]
As it started after upgrading my Nextcloud instance, I think it was an issue within the server/database migration and not the Android app. Unfortunately I cannot give proof of that.

**Comment by stefan-niedermann** [comment]
Thank you though for your time and help. Let us know if you encounter any further issues 🙂
