### ISSUE TITLE
crash when the internet connection is bad

### ISSUE THREAD

**Issue by yodatak** [stefan-niedermann/nextcloud-deck#542]
I got this error

```
App Version: 1.4.2
App Version Code: 1004002
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 4.9.225-perf-gdea22eb(0015d53511)
OS API Level: 29
Device: dipper
Manufacturer: Xiaomi
Model (and Product): MI 8 (dipper)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:22)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:12)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:96)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$updateCard$24$SyncManager(SyncManager.java:838)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$HXBzSTFFA-x5MF2RNN27crL5qIM.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Please update to the latest version.

If the error persists [follow those steps](https://github.com/stefan-niedermann/nextcloud-deck/wiki/FAQ#i-have-experienced-an-error) and provide a few more information than "I got this error".

- Does the app crash completely or only show a snackbar?
- Does it happen always after open the app, or when you pull down to refresh or when creating a card or what?
- Which connection do you have? Edge / UMTS / LTE?  Wi-Fi?
- Does it only happen when you switch between the networks or when you are connected to a network?
- Describe exactly what you are doing and when you are doing it.
- Tell us something about your environment, how much signal strength do you have?
- Did it happen on the train or did you change your location quickly?

With this little information we will not be able to find any error.

**Comment by stefan-niedermann** [comment]
PS.: We have [issue templates](https://github.com/stefan-niedermann/nextcloud-deck/issues/new/choose) for a reason :wink: Please make use of them if you open issues.
