### ISSUE TITLE
Synchronization Error

### ISSUE THREAD

**Issue by llucax** [stefan-niedermann/nextcloud-deck#547]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

I just open the app and I got some synchronization error.

**To Reproduce**

I'm not really sure what triggered this. It might be related to trying to attach a file in the past that failed (unfortunately I didn't save the stacktrace for that one). It was working fine but at some point it just got the sync error.

1. Not sure
2. Just open the app or tap-down to force a sync
3. See Error "Synchronization Failed <MORE>"

**Expected behavior**

Sync works

**Screenshots**

Not applicable

**Versions**
 - Nextcloud: 18.0.6
 - Nextcloud Deck: 1.0.2
 - Nextcloud Android: 3.12.0
 - Nextcloud Android Deck: 1.4.4 / 1.5.0 (I upgraded after I got the stacktrace but it's still happening)

**Smartphone (please complete the following information):**
- Device: LG G6
- Android-Version: 9
- App-Store:
  - [ ] Google Play Store
  - [x] F-Droid

**Stacktrace**
```
App Version: 1.4.4
App Version Code: 1004004
App Flavor: fdroid

Deck Server Version: 1.0.2

Files App Version Code: 30120090

---

OS Version: 3.18.120-perf+(1930916292597)
OS API Level: 28
Device: lucye
Manufacturer: LGE
Model (and Product): LG-H870 (lucye_global_com)

---

java.lang.IllegalStateException: failed to build request-body
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.bodyToStream(NextcloudRetrofitServiceMethod.java:218)
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.invoke(NextcloudRetrofitServiceMethod.java:164)
	at retrofit2.NextcloudRetrofitApiBuilder.lambda$create$0$NextcloudRetrofitApiBuilder(NextcloudRetrofitApiBuilder.java:30)
	at retrofit2.-$$Lambda$NextcloudRetrofitApiBuilder$U6rJlQEKMLSg7zB4KqSP_SBh3BM.invoke(Unknown Source:2)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy2.uploadAttachment(Unknown Source)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.lambda$uploadAttachment$26$ServerAdapter(ServerAdapter.java:282)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.-$$Lambda$ServerAdapter$uu8p1FGbrAMZqv7noZNb699-7WM.getObservableFromCall(Unknown Source:12)
	at it.niedermann.nextcloud.deck.api.RequestHelper.request(RequestHelper.java:33)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.ServerAdapter.uploadAttachment(ServerAdapter.java:282)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:68)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:18)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:96)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:268)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:116)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:126)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:100)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$3$1.lambda$onResponse$0(SyncManager.java:188)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3$1$3iKicNZlgWASgTHun34YoNfq7LQ.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.FileNotFoundException: /sdcard/Android/media/com.nextcloud.client/nextcloud/luca@cloud.llucax.com/Documents/Papeletas/Envivas/2020-03-16-factura-pediatra-PART_ 20254301141_015_00003_00000297.pdf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at okio.Okio.source(Okio.java:168)
	at okhttp3.RequestBody$3.writeTo(RequestBody.java:170)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
	at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
	at com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod.bodyToStream(NextcloudRetrofitServiceMethod.java:214)
	... 21 more

```

**Comment by llucax** [comment]
In case it helps, I see the failed attachments were still sort of shown in the app (in the cards view there was a clip symbol with a 4 but there were really only 2 attachments on that card). What I did was adding the attachments with the web interface after it failed in the App, so I think the sync error really comes from there.

Now I reset the App data, so all the information was downloaded again from the server and I get the card with only 2 attachments and no sync error.

**Comment by desperateCoder** [comment]
Hi @llucax, thanks for your report!
The reason it initially failed is, that the app failed to read your locally attached file. Maybe it was deleted in the meantime or the app has no more permissions to access it. (thumbnail might be still visible in app due to caching) 

You did the very right thing to fix this issue quickly.

@stefan-niedermann should we handle `FileNotFoundException`s somehow to inform the user about the missing file? Or should i remove the unsyced attachment silently? @llucax whats your opinion about this?

**Comment by llucax** [comment]
Hi @desperateCoder. I have very little idea of how these kind of situations should be handled. I think the root cause for this was the failure when attaching a file. I'll see if I can reproduce and send the trace. Once that type of *corruption* happened, is hard to decide which approach is best, but I guess it is always good to inform the users something unexpected happened and ask them to review their board to see if anything is missing. Is better to know as soon as possible about these kind of weirdness as there are more chances of recovery (for example I could have now the files to re-upload, but if I find out in a month that a file is missing it might be already gone).

**Comment by stefan-niedermann** [comment]
Hey there :wave:

Thanks for the report. Yes, we are cloning files to our own storage before we upload a file (starting with version `1.5.0` i think). In error case, we should delete this cloned file in each case, not only in case the attachment already exists on the server.

I think this `if` cause the corrupted state: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/helpers/providers/AttachmentDataProvider.java#L86

@desperateCoder can you verify?

**Comment by stefan-niedermann** [comment]
We will clean up attachments which failed to upload. Starting with version `1.5.3` this should no longer cause a corrupt state.

**Comment by llucax** [comment]
I found an easy workaround for this, just go back to the card, attachments, long tap on the failed (0 sized) attachment, click delete. Now sync works again.
