### ISSUE TITLE
I started the application but there is a crash happened 

### ISSUE THREAD

**Issue by michaelsam94** [stefan-niedermann/nextcloud-deck#572]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**
 - Nextcloud: 
 - Nextcloud Deck: 
 - Nextcloud Android: 
 - Nextcloud Android Deck: 

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] F-Droid

**Stacktrace**
```
App Version: 1.5.6
App Version Code: 1005006
App Flavor: dev

Deck Server Version: 0.6.4

Files App Version Code: 30120090

---

OS Version: 4.14.98-perf+(1589772775)
OS API Level: 28
Device: OP4B80L1
Manufacturer: OPPO
Model (and Product): CPH1937 (CPH1937)

---

it.niedermann.nextcloud.deck.exceptions.DeckException: deck node is missing in capabilities endpoint!
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseCapabilities(JsonToEntityParser.java:417)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:54)
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by desperateCoder** [comment]
Hi @michaelsam94, thanks for your report!

Can you confirm, that the Deck app is installed on your nexcloud instance? Seems like it is not installed on the server side...

**Comment by michaelsam94** [comment]
I don't installed anything on serverside just choose server and create new account on nextcloud application is there a server you work with it on this development can I change the server from nextcloud app after creating account and has chosen the server already

**Comment by stefan-niedermann** [comment]
Hi @michaelsam94 

as in the [README](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/README.md#-requirements) mentioned, you need to install [Nextcloud Deck](https://apps.nextcloud.com/apps/deck) on your server first.
Please try to use a few punctuation marks, so we can better understand your issues :slightly_smiling_face: 

Thank you in advance

**Comment by stefan-niedermann** [comment]
Feel free to open a new issue filling the complete issue template in case the error still happens after installing the required server side app.
