### ISSUE TITLE
SSO:  "Invalid If-Modified-Since header provided."

### ISSUE THREAD

**Issue by tobiasKaminsky** [stefan-niedermann/nextcloud-deck#58]
In order to test/fix problems with SSO I checked out lastest SSO and integrated into deck, but after authenticated I do get:
```
2019-03-18 11:37:43.164 15554-15591/com.nextcloud.client E/InputStreamBinder: {"status":500,"message":"Invalid If-Modified-Since header provided."}
2019-03-18 11:37:43.165 15554-15591/com.nextcloud.client E/InputStreamBinder: Error during Nextcloud request
    java.lang.IllegalStateException: CE_5
        at com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:304)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:133)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:112)
        at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:86)
        at android.os.Binder.execTransact(Binder.java:731)
```

Deck: master
SSO: master
Files app: master
Nextcloud server: master

**Comment by tobiasKaminsky** [comment]
It happens on this path:
/nc/index.php/apps/deck/api/v1.0/boards

Header is: If-Modified-Since: Do., 01 Jan. 1970 12:00:00 GMT \r\n

**Comment by desperateCoder** [comment]
Have a look at a log message titled "lastSync", there should be a date. Please post it, in theory it should work...

**Comment by desperateCoder** [comment]
Interesting... For me it works... @stefan-niedermann could you create a user for @tobiasKaminsky on your server? If the problem persists, we should have a closer look

**Comment by stefan-niedermann** [comment]
@tobiasKaminsky please write me an email, i will tell you credentials as soon as i have your mal address

**Comment by tobiasKaminsky** [comment]
It seems that the date string for if-modified-since header is localized.
This needs always be english.

**Comment by tobiasKaminsky** [comment]
https://github.com/stefan-niedermann/nextcloud-deck/blob/b5615bdb42a9cdf94d9eabe72e474f93b766c126/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/ServerAdapter.java#L77-L86

**Comment by desperateCoder** [comment]
Oops. You're right. I can fix that at the evening, but you can make a PR as well, should be fixed in the date until or the Dateiformat (API_FORMAT)

**Comment by tobiasKaminsky** [comment]
Already done in #59
