### ISSUE TITLE
Error message and blank board on Android app

### ISSUE THREAD

**Issue by petrisch** [stefan-niedermann/nextcloud-deck#585]
I have a issue with one of my two instances, where the Android App doesn't sync anymore and shows this output.

```
App Version: 1.5.6
App Version Code: 1005006
App Flavor: fdroid

Deck Server Version: 1.0.4

Files App Version Code: 30120090

---

OS Version: 3.18.120-perf(00WW_6_19D)
OS API Level: 28
Device: PLE
Manufacturer: HMD global
Model (and Product): TA-1033 (TA-1033_00WW)

---

it.niedermann.nextcloud.deck.exceptions.TraceableException: Sorry, a wild error appeared!
### If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ###
Failed to run traceable code with arguments:
```
```json
{
    "title": "IT Stuff",
    "owner": {
        "primaryKey": "Patrick",
        "uid": "Patrick",
        "displayname": "Patrick",
        "type": 0
    },
    "color": "000000",
    "archived": false,
    "labels": [
        {
            "title": "Important",
            "color": "03dcc7",
            "boardId": 1,
            "cardId": null,
            "lastModified": 1588756333,
            "id": 33
        }
    ],
    "acl": [
        {
            "participant": "17d46b1e46f590",
            "type": 7,
            "boardId": 1,
            "permissionEdit": true,
            "permissionShare": true,
            "permissionManage": true,
            "owner": false,
            "id": 4
        }
    ],
    "permissions": {
        "PERMISSION_READ": true,
        "PERMISSION_EDIT": true,
        "PERMISSION_MANAGE": true,
        "PERMISSION_SHARE": true
    },
    "users": [
        {
            "primaryKey": "Patrick",
            "uid": "Patrick",
            "displayname": "Patrick",
            "type": 0
        }
    ],
    "shared": 0,
    "stacks": [
        {
            "title": "To do",
            "boardId": 1,
            "deletedAt": 0,
            "lastModified": 1593699480,
            "order": 1,
            "id": 1
        },
        {
            "title": "Doing",
            "boardId": 1,
            "deletedAt": 0,
            "lastModified": 1593699382,
            "order": 1,
            "id": 2
        },
        {
            "title": "Done",
            "boardId": 1,
            "deletedAt": 0,
            "lastModified": 1593268665,
            "order": 1,
            "id": 3
        }
    ],
    "deletedAt": 0,
    "lastModified": 1593699480,
    "id": 1
}
```
```
Cause: Sorry, a wild error appeared!

### If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ###

Failed to run traceable code with arguments:
```
```json
{
    "participant": "17d46b1e46f590",
    "type": 7,
    "boardId": 1,
    "permissionEdit": true,
    "permissionShare": true,
    "permissionManage": true,
    "owner": false,
    "id": 4
}
```
```
Cause: Not a JSON Object: "17d46b1e46f590"
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseBoard(JsonToEntityParser.java:129)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:42)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:36)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: it.niedermann.nextcloud.deck.exceptions.TraceableException: Sorry, a wild error appeared!

### If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ###

Failed to run traceable code with arguments:
```
```json
{
    "participant": "17d46b1e46f590",
    "type": 7,
    "boardId": 1,
    "permissionEdit": true,
    "permissionShare": true,
    "permissionManage": true,
    "owner": false,
    "id": 4
}
```
```
Cause: Not a JSON Object: "17d46b1e46f590"
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseAcl(JsonToEntityParser.java:208)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseBoard$3(JsonToEntityParser.java:164)
	at it.niedermann.nextcloud.deck.api.-$$Lambda$JsonToEntityParser$z6Sr6vZr0UOchjvDfMmd9RtUHBo.run(Unknown Source:6)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	... 21 more
Caused by: java.lang.IllegalStateException: Not a JSON Object: "17d46b1e46f590"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseAcl$4(JsonToEntityParser.java:209)
	at it.niedermann.nextcloud.deck.api.-$$Lambda$JsonToEntityParser$tykdczKbqskF2uwnsxaRM-yHiyo.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	... 25 more
```

I have that since like 3 Versions back. I since deleted the account and even removed the Nextcloud App, with the same result.
My second instance has "the same" setup, but is on a arm64 machine. Sure not everything will be the same. But there is no such issue, it works fine.

So the output is just a blank board, where there should be cards. The app in Nextcloud itself works fine and is up to date as well.
I posted it already in the forum and just see, that I should have checked if there is confidential information in this error message. Well other than my prename i don't see any, hopefully I'm not wrong :-)

**Comment by stefan-niedermann** [comment]
You are using the [circles](https://apps.nextcloud.com/apps/circles app, aren't you?

Is it possible that this is the difference? In one account you shared the board "IT stuff" with a circle. Can you try to remove it via web interface to see whether this prevents the crash?

**Comment by petrisch** [comment]
Oh, thanks for that, I will try.
I am using Circles on both, but yes, on that instance i fiddeled around with that one.

**Comment by stefan-niedermann** [comment]
> I am using Circles on both

But have you shared boards with a complete circle on both instances or only on the defect one?

It might be enough to remove the share of the "IT stuff" with the circle. You should start with testing this.

When we tracked down the root cause we can start implementing the missing parts for supporting for the circle app.

**Comment by petrisch** [comment]
Yes that did it, works again.
The circle i shared this board with looked empty on the web interface sharing page where i deleted it now.
It came to my mind that i might have been trying out a federated circle from one machine to the other, and then trying to share it with that one. That didn't work and i might have deleted the federated circle leaving the share behind... or something similar

**Comment by stefan-niedermann** [comment]
Glad to hear everything is working for you now 🙂 

I have two more questions:

- Do you have another board which is shared with a circle and does this work well in combination with the Android app?
- Did the app completly crash or was there just a popup dialog which showed the error?

**Comment by petrisch** [comment]
- Yes i have another Circle which has no federation tests in it, that works well. Also when i look at the share it has the circle name in it, which wasn't the case with the above.
- No the app didn't crash, it showed the error message at the bottom and I was able to copy it. As it should be :-)
thanks a lot.
