### ISSUE TITLE
Make card movement more robust

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#592]
Steps to reproduce **i think**:

1. Delete card via web UI
2. Move this card using the android app while sync has not yet been completed
3. Watch the world burn

Is it possible that *while* one tries to move a card (e. g. while picking the target stack) the card has been deleted?
If the card is no longer present, throw new `IllegalStateException` with a meaningful message like "Could not move card because it has been deleted", so i can display a good error dialog instead of just the generic exception dialog fragment

# ToDo

- [ ] catch this case and throw `IllegalStateException` with meaningful message
- [ ] catch `IllegalStateException` in UI (`StackFragment#move`) and display appropriate message in dialog

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.full.FullBoard.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$moveCard$32$SyncManager(SyncManager.java:1071)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$af3K4WGRUlUdA0v4KpkbZe5Sltc.getData(Unknown Source:12)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.LiveDataHelper$LiveDataWrapper.postResult(LiveDataHelper.java:28)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.LiveDataHelper.lambda$wrapInLiveData$6(LiveDataHelper.java:90)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.-$$Lambda$LiveDataHelper$5uylSY4vndjuycAu_-pJfOpoy90.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Well, closing as not reproducible with the mentioned steps.

After some analyze from @desperateCoder a card which has been deleted remotely and gets moved, will be restored automatically (which is actually a good behavior).
