### ISSUE TITLE
nicht erreichbar, obwohl alles in Ordnung 

### ISSUE THREAD

**Issue by ThomasKujawa** [stefan-niedermann/nextcloud-deck#596]
```
App Version: 1.7.0
App Version Code: 1007000
App Flavor: fdroid

Deck Server Version: 1.0.4

Files App Version Code: 30120190

---

OS Version: 4.14.141-gc9d6863(V11.0.3.0.QGGEUXM)
OS API Level: 29
Device: begonia
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8 Pro (begonia_eea)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'it.niedermann.nextcloud.deck.model.Stack it.niedermann.nextcloud.deck.model.full.FullStack.getStack()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:242)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:120)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:126)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:100)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:80)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$3$1.lambda$onResponse$0(SyncManager.java:205)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3$1$3iKicNZlgWASgTHun34YoNfq7LQ.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by desperateCoder** [comment]
Oops, ein wunder, dass der Fehler so lange nicht aufgefallen ist.... Danke für die Meldung @ThomasKujawa!!

@stefan-niedermann: Did you already release 1.8.0? If not, please ship this fix, too!

**Comment by stefan-niedermann** [comment]
Fix will be shipped with `1.8.1`. Next time please use the [issue template](https://github.com/stefan-niedermann/nextcloud-deck/issues/new/choose).
