### ISSUE TITLE
Handle unknown project types

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#619]
Adding a chat room of the "Talk" app to an existing project breaks the sync:
```
it.niedermann.nextcloud.deck.exceptions.TraceableException: Sorry, a wild error appeared!

⚠️ If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ⚠️

Failed to run traceable code with arguments:
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":[{"id":3,"name":"Project 1","resources":[{"type":"deck-card","id":"605","name":"Artur is great!: llkkll","link":"/index.php/apps/deck/#/board/98/card/605","iconUrl":"/core/img/actions/toggle-pictures.svg"},{"type":"file","id":"46589","name":"2019_Glocken.mp4","path":"files/2019_Glocken.mp4","link":"https://example.com/index.php/f/46589","mimetype":"video/mp4","preview-available":false},{"type":"room","id":"so763ats","name":"sample","call-type":"group","iconUrl":"https://example.com/apps/spreed/img/app-dark.svg","link":"https://example.com/index.php/call/so763ats"}]},{"id":4,"name":"Sample Project","resources":[{"type":"deck","id":"135","name":"BoardWithoutAnything","link":"/index.php/apps/deck/#/board/135","iconUrl":"/apps/deck/img/deck-dark.svg"},{"type":"deck-card","id":"605","name":"Artur is great!: llkkll","link":"/index.php/apps/deck/#/board/98/card/605","iconUrl":"/core/img/actions/toggle-pictures.svg"}]},{"id":5,"name":"Another project","resources":[{"type":"deck-card","id":"558","name":"Deck Android: Test","link":"/index.php/apps/deck/#/board/99/card/558","iconUrl":"/core/img/actions/toggle-pictures.svg"},{"type":"deck-card","id":"605","name":"Artur is great!: llkkll","link":"/index.php/apps/deck/#/board/98/card/605","iconUrl":"/core/img/actions/toggle-pictures.svg"}]},{"id":6,"name":"llkkll","resources":[{"type":"deck","id":"135","name":"BoardWithoutAnything","link":"/index.php/apps/deck/#/board/135","iconUrl":"/apps/deck/img/deck-dark.svg"},{"type":"deck-card","id":"605","name":"Artur is great!: llkkll","link":"/index.php/apps/deck/#/board/98/card/605","iconUrl":"/core/img/actions/toggle-pictures.svg"}]},{"id":7,"name":"Project 2","resources":[{"type":"deck-card","id":"537","name":"Artur is great!: trester","link":"/index.php/apps/deck/#/board/98/card/537","iconUrl":"/core/img/actions/toggle-pictures.svg"},{"type":"deck-card","id":"605","name":"Artur is great!: llkkll","link":"/index.php/apps/deck/#/board/98/card/605","iconUrl":"/core/img/actions/toggle-pictures.svg"},{"type":"file","id":"6963","name":"Gnome Wallpaper.jpg","path":"files/Dokumente/Gnome Wallpaper.jpg","link":"https://example.com/index.php/f/6963","mimetype":"image/jpeg","preview-available":true}]}]}}
Cause: Sorry, a wild error appeared!

⚠️ If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ⚠️

Failed to run traceable code with arguments:
{"type":"room","id":"so763ats","name":"sample","call-type":"group","iconUrl":"https://example.com/apps/spreed/img/app-dark.svg","link":"https://example.com/index.php/call/so763ats"}
Cause: For input string: "so763ats"
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseOcsProjectList(JsonToEntityParser.java:97)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:65)
	at it.niedermann.nextcloud.deck.api.NextcloudDeserializer.deserialize(NextcloudDeserializer.java:30)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: it.niedermann.nextcloud.deck.exceptions.TraceableException: Sorry, a wild error appeared!

⚠️ If you want to tell us about the following issue, please make sure to censor sensitive data beforehand! ⚠️

Failed to run traceable code with arguments:
{"type":"room","id":"so763ats","name":"sample","call-type":"group","iconUrl":"https://example.com/apps/spreed/img/app-dark.svg","link":"https://example.com/index.php/call/so763ats"}
Cause: For input string: "so763ats"
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseOcsProjectResource(JsonToEntityParser.java:131)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseOcsProjectList$1(JsonToEntityParser.java:113)
	at it.niedermann.nextcloud.deck.api.-$$Lambda$JsonToEntityParser$QCh1Pf-C4m8nxLa8sWB94eGRxtA.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	... 20 more
Caused by: java.lang.NumberFormatException: For input string: "so763ats"
	at java.lang.Long.parseLong(Long.java:594)
	at java.lang.Long.parseLong(Long.java:636)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.lambda$parseOcsProjectResource$2(JsonToEntityParser.java:132)
	at it.niedermann.nextcloud.deck.api.-$$Lambda$JsonToEntityParser$frO1oWvHO9S9GYM74W9rpTjE4bU.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.exceptions.TraceableException.makeTraceableIfFails(TraceableException.java:13)
	... 24 more

```

**Comment by stefan-niedermann** [comment]
Quickfix: Filter resources with a `String` id.
Long solution: Make sync being able to handle `String` ids.

**Comment by desperateCoder** [comment]
Branch: 619-project-ids-string

@stefan-niedermann I've gone for the long solution. Seems to work fine. If you can't break it, please check if you have to change something in the UI for this. The `OcsProjectResource` now has a field `idString`. If you need the ID anywhere, check which one of them is filled (`id` or `idString`)

**Comment by stefan-niedermann** [comment]
Ah, so we have two fields and depending of the type one is filled and the other one not?
Wouldn't it be easier if we always mapped the id into a `String`?

**Comment by desperateCoder** [comment]
maybe easyier, but this way i fully preserve the current sync functionality. trust me, this is the best you can get with the current rest of the application. The more extrawöschd, the more bugs.
