### ISSUE TITLE
Can't choose account

### ISSUE THREAD

**Issue by romevi** [stefan-niedermann/nextcloud-deck#625]
I started using Deck on the web version and it works great. I went to download the Android app but when I choose my account I get this error back:

```
App Version: 1.9.1
App Version Code: 1009001
App Flavor: fdroid

Files App Version Code: 30130051

---

OS Version: 4.4.153-17146873(N950USQS7DTA5)
OS API Level: 28
Device: greatqlte
Manufacturer: samsung
Model (and Product): SM-N950U (greatqltesq)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String it.niedermann.nextcloud.deck.model.Account.getUserName()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.accountswitcher.AccountSwitcherDialog.onCreateDialog(AccountSwitcherDialog.java:50)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:419)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1484)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

I'm not able to choose my account as the app just resets after giving me that error.

**Comment by romevi** [comment]
And just like that it started working. :/

**Comment by stefan-niedermann** [comment]
F-Droid or Play Store Beta Channel?

Did you do an upgrade from a previous version?

`1.9.1` is known to have a heavy bug. You should wait for `1.9.2` or use an older version.

Regards.
