### ISSUE TITLE
bug on card deletion

### ISSUE THREAD

**Issue by dberardo** [stefan-niedermann/nextcloud-deck#640]
steps to reproduce:

1. create a card on any board
2. synchronise with server (swipe down)
3. delete that card

 log:
```
App Version: 1.9.5
App Version Code: 1009005
App Flavor: play

Deck Server Version: 1.0.5

Files App Version Code: 30120190

---

OS Version: 4.4.111-16983991(N950FXXSADTC4)
OS API Level: 28
Device: greatlte
Manufacturer: samsung
Model (and Product): SM-N950F (greatltexx)

---

java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.disposables.Disposable.dispose()' on a null object reference
	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:109)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:98)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$HPzOdi9LOc_f-wA9GNnhc9LKQSM.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment]
Confirmed and reproducable. It actually happens on each card one tries to delete (any card, no need for the manual pull to refresh).

**Comment by desperateCoder** [comment]
Sorry for the delay, see the issue in Android SSO above... That's the explanation to this behavior.

**Comment by desperateCoder** [comment]
oh and @stefan-niedermann an alternative would be reverting the SSO version to an older one i guess? Would be a quickfix, but at least people can delete their cards again... or what feature relys on the currently used version?

**Comment by stefan-niedermann** [comment]
ETag handling relies on it, don't know how much work it is to disable it.

**Comment by stefan-niedermann** [comment]
As a quick fix we can be optimistic and temporarily catch and hide `NullPointerException`s in those cases (we even can limit it to this exact message).

I identified "Delete card" and "Delete board" so far.
@desperateCoder is there an easy way to give me a list of all methods where this can happen?

**Comment by desperateCoder** [comment]
Yep, have a look at NextcloudServerAPI and DeckAPI. Wherever a void is defined as return value, we have this problem (most likely any delete operation)

**Comment by stefan-niedermann** [comment]
Workaround implemented, releasing....

**Comment by stefan-niedermann** [comment]
So, @dberardo you shouldn't see this error message with version `1.9.6`, thank you for reporting it!

Closing this in favor of https://github.com/nextcloud/Android-SingleSignOn/issues/231
