### ISSUE TITLE
List wiget: crash on 'clicking' on a list entry

### ISSUE THREAD

**Issue by splashote** [stefan-niedermann/nextcloud-deck#655]
The following message appears when I click on an entry of the list widget.

nextcloud 18.0.6
Deck app on server: 1.0.4

```
Full Crash:

App Version: 1.9.7
App Version Code: 1009007
App Flavor: play

Files App Version Code: 30130054

---

OS Version: 3.18.71-perf-g0f5ce2e(ABT975)
OS API Level: 27
Device: bbb100
Manufacturer: BlackBerry
Model (and Product): BBB100-2 (bbb100emea)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.nextcloud.deck.play/it.niedermann.nextcloud.deck.ui.card.EditActivity}: java.lang.IllegalArgumentException: account must not be null.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2899)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6558)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
Caused by: java.lang.IllegalArgumentException: account must not be null.
	at it.niedermann.nextcloud.deck.ui.card.EditActivity.loadDataFromIntent(EditActivity.java:116)
	at it.niedermann.nextcloud.deck.ui.card.EditActivity.onCreate(EditActivity.java:87)
	at android.app.Activity.performCreate(Activity.java:7256)
	at android.app.Activity.performCreate(Activity.java:7247)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2774)
	... 9 more

```

**Comment by stefan-niedermann** [comment]
Thank you for the report.

**Please fill the [issue template](https://github.com/stefan-niedermann/nextcloud-deck/issues/new?labels=bug&template=bug_report.md)** - it's there for a reason 😉 

We need exact steps to reproduce. Does it happen always? Did you edit another card recently? If yes: From the same account or from another? Does it still happen if you remove and readd the widget?

Literally **every** piece of information you can provide is extremely valuable to solve the issue.

**Comment by dan0xii** [comment]
Hello @splashote, I'm having trouble reproducing this with the versions you have given. More information as per Stefan's post would be appreciated.

**Comment by splashote** [comment]
As I fail to reproduce the crash myself I close the bug. 
It only happened with one instance of nextcloud (=not with the other one I'm using) and re-creating the widget with the same list solved the issue. Now I can click on the same entries that caused the crash and they open up as they should.


Thanks for your commitment! :)

**Comment by stefan-niedermann** [comment]
Great to hear! Thank you for the feedback and let us know if it occurs again.
