### ISSUE TITLE
Add workaround for known issue in FAQ.md

### ISSUE THREAD

**Issue by HelplessFool** [stefan-niedermann/nextcloud-deck#660]
On selecting account and allowing access the following error is received:

```
App Version: 1.9.7
App Version Code: 1009007
App Flavor: fdroid

Deck Server Version: 0.6.4

Files App Version Code: 30120190

---

OS Version: 3.18.120-perf-gd60e12b6-dirty(TB-X705F_USR_S210120_191029_Q00332_ROW)
OS API Level: 28
Device: X705F
Manufacturer: LENOVO
Model (and Product): Lenovo TB-X705F (LenovoTB-X705F)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
        at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:168)
        at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
        at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$HPzOdi9LOc_f-wA9GNnhc9LKQSM.subscribe(Unknown Source:6)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

Deck works with two other devices running the same version of the app.  I can see files on the cloud using the nextcloud app.  No errors occur there.

What further information would help you debug this?

**Comment by stefan-niedermann** [comment]
@HelplessFool can you please install the "Nextcloud Notes" app on your server abd on your phone and try to connect? This way we might able to detect whether the problem is in the Deck app itself or in the lib (or files app).

**Comment by HelplessFool** [comment]
Nice idea.

I've installed notes on the server and on my phone (Deck works) and tablet (Deck doesn't work).

- Notes worked straight away on the phone, no issues.
- Notes doesn't work on the tablet.  Looks like a very similar error message to the one at the top of this thread.
    - Only difference I can see by eye-balling is that the line about Deck version is missing.

So, I'm guessing the issue is not directly with the Deck app, but somewhere nearer the main Nextcloud app or communication between them.

**Comment by David-Development** [comment]
It does indeed look like an issue with the communication between the single sign on library and the nextcloud app. If you have disabled all power saving features (if available) I'm kinda running out of ideas as well. It is really difficult to debug this problem deeper as you would need to build the app yourself (including the single-sign-on library) and try to debug it. However I'm not sure if this will bring any new insights since I guess the service that we connect to is just not binding correctly. I'm wondering if this is somehow connected to the custom rom that you are running.. 🤔 

@HelplessFool Do you have more logcat output for us? (not just error output)
@stefan-niedermann do you know if debug and info logs are suppressed in your production builds? We should be able to see some debugging logs from the nextcloud sso library ([Ref](https://github.com/nextcloud/Android-SingleSignOn/blob/9c93c872daa51b67bee9a7402e0c637fc2fab561/src/main/java/com/nextcloud/android/sso/api/AidlNetworkRequest.java#L102))

**Comment by HelplessFool** [comment]
@David-Development How would I find more logcat output?  What I provided initially was the error message that you can copy from the app.  I'm happy to provide if I know how to get at it.

**Comment by stefan-niedermann** [comment]
> do you know if debug and info logs are suppressed in your production builds? We should be able to see some debugging logs from the nextcloud sso library (Ref)

@David-Development According to [this medium article](https://medium.com/mobile-app-development-publication/debug-messages-your-responsible-to-clear-it-before-release-1a0f872d66f) not :man_shrugging:

**Comment by David-Development** [comment]
@HelplessFool you should be able to find the logs by using an app (for example https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=de_CH) or by connecting your tablet to your computer and by running the `adb logcat` command (however if you don't have adb yet the app I mentioned before might be the easiest option - otherwise you can find a tutorial on how to install adb here: https://www.xda-developers.com/install-adb-windows-macos-linux/).  

@stefan-niedermann that's good! 😅

**Comment by HelplessFool** [comment]
@David-Development I've got adb working so will have a look.  Is the best thing to do to try the app, have it fail and then plug in and use adb?  Anything particular that I should look for to know whether I'm looking at useful stuff or just random goings on on the device?

**Comment by David-Development** [comment]
@HelplessFool Would be good if you close both apps (nextcloud files app and deck app) and then start "recording" the log. Then start the deck app and try to login. Make sure that no sensitive data is in the log before sending it to us 🙂 Thank you!

**Comment by HelplessFool** [comment]
I think this is it:  Tell me if you need more context.
I've cut out a bit in the middle that looks like it's another app trying to do stuff.
```
08-26 21:22:31.121 14102 14168 D com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod: NextcloudRetrofitServiceMethod() called with: apiEndpoint = [/ocs/v2.php/], method = [public abstract io.reactivex.Observable it.niedermann.nextcloud.deck.api.NextcloudServerAPI.getCapabilities(java.lang.String)]
08-26 21:22:31.121 14102 14168 D com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod: WARNING: Header not set - key or value missing! Key: If-None-Match | Value: null
08-26 21:22:31.121 14102 14168 D com.nextcloud.android.sso.api.NextcloudRetrofitServiceMethod: invoke call to api using observable com.nextcloud.android.sso.api.ParsedResponse<it.niedermann.nextcloud.deck.model.ocs.Capabilities>
08-26 21:22:31.124 14102 14169 D com.nextcloud.android.sso.api.NetworkRequest: [connectApiWithBackoff] connectApiWithBackoff() called from Thread: [Thread-7]
08-26 21:22:31.125 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connectApiWithBackoff] trying to connect..
08-26 21:22:31.125 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService for type [nextcloud]
08-26 21:22:31.125 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connect] connect() called [main] Account-Type: [nextcloud]
08-26 21:22:31.125 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Component name is: [com.nextcloud.client]
08-26 21:22:31.127   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:31.131  1008  4039 D ActivityManager: TabletMaster Service: not allowed start service : Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } callingUid 10179 callingPackage it.niedermann.nextcloud.deck
08-26 21:22:31.131  1008  4039 W ActivityManager: Unable to start service Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } U=0: not found
08-26 21:22:31.128   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:31.131 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService returned false
08-26 21:22:31.131 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] Error: [Binding to AccountManagerService returned false]
08-26 21:22:31.131 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] retrying in: [1742ms]
08-26 21:22:31.133 14102 14172 V com.nextcloud.android.sso.api.AidlNetworkRequest: [waitForApi] - api not ready yet.. waiting [RxNewThreadScheduler-1]
08-26 21:22:31.143   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:31.143   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:31.155  1388  1388 D NavigationBar: sjj ---- onTaskStackChanged
08-26 21:22:31.160   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:31.262   562   562 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 12 lines
08-26 21:22:31.263   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:31.279   562   649 W SurfaceFlinger: Attempting to set client state on removed layer: com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity#0
08-26 21:22:31.280   562   649 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=2211#0
08-26 21:22:31.280   562   649 W SurfaceFlinger: Attempting to destroy on removed layer: com.nextcloud.client/com.owncloud.android.ui.activity.SsoGrantPermissionActivity#0
08-26 21:22:31.280   562   649 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=2211#0
08-26 21:22:31.351  8619  8785 D ClClient: Not sending keepalive.  Current connection state=STOPPED
08-26 21:22:32.874 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connectApiWithBackoff] trying to connect..
08-26 21:22:32.874 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService for type [nextcloud]
08-26 21:22:32.874 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connect] connect() called [main] Account-Type: [nextcloud]
08-26 21:22:32.874 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Component name is: [com.nextcloud.client]
08-26 21:22:32.878  1008  4039 D ActivityManager: TabletMaster Service: not allowed start service : Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } callingUid 10179 callingPackage it.niedermann.nextcloud.deck
08-26 21:22:32.878  1008  4039 W ActivityManager: Unable to start service Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } U=0: not found
08-26 21:22:32.878 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService returned false
08-26 21:22:32.879 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] Error: [Binding to AccountManagerService returned false]
08-26 21:22:32.879 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] retrying in: [2881ms]
08-26 21:22:35.761 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connectApiWithBackoff] trying to connect..
08-26 21:22:35.761 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService for type [nextcloud]
08-26 21:22:35.761 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connect] connect() called [main] Account-Type: [nextcloud]
08-26 21:22:35.761 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Component name is: [com.nextcloud.client]
08-26 21:22:35.764  1008  4039 D ActivityManager: TabletMaster Service: not allowed start service : Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } callingUid 10179 callingPackage it.niedermann.nextcloud.deck
08-26 21:22:35.764  1008  4039 W ActivityManager: Unable to start service Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } U=0: not found
08-26 21:22:35.765 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService returned false
08-26 21:22:35.765 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] Error: [Binding to AccountManagerService returned false]
08-26 21:22:35.765 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] retrying in: [3048ms]
```


```
08-26 21:22:38.816 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connectApiWithBackoff] trying to connect..
08-26 21:22:38.817 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService for type [nextcloud]
08-26 21:22:38.817 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connect] connect() called [main] Account-Type: [nextcloud]
08-26 21:22:38.817 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Component name is: [com.nextcloud.client]
08-26 21:22:38.820  1008  1525 D ActivityManager: TabletMaster Service: not allowed start service : Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } callingUid 10179 callingPackage it.niedermann.nextcloud.deck
08-26 21:22:38.820  1008  1525 W ActivityManager: Unable to start service Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } U=0: not found
08-26 21:22:38.820 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService returned false
08-26 21:22:38.820 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] Error: [Binding to AccountManagerService returned false]
08-26 21:22:38.820 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] retrying in: [2979ms]
08-26 21:22:41.137 14102 14172 E DeckLog : onError() (IResponseCallback.java:24) -> com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
08-26 21:22:41.137 14102 14172 E DeckLog : 	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:168)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$HPzOdi9LOc_f-wA9GNnhc9LKQSM.subscribe(Unknown Source:6)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at io.reactivex.Observable.subscribe(Observable.java:12284)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-26 21:22:41.137 14102 14172 E DeckLog : 	at java.lang.Thread.run(Thread.java:764)
08-26 21:22:41.138 14102 14172 D DeckLog : Rolling back account creation for 4
08-26 21:22:41.139 14102 14172 D DeckLog : --- Remove: shared_preference_last_account | 4
08-26 21:22:41.157 14102 14172 I DeckLog : --- Restoring sync on wifi only setting
08-26 21:22:41.181 14102 14102 E VersionCheckHelper: Version Code: 30130090
08-26 21:22:41.183 14102 14102 E DeckLog : onCreateDialog() (ExceptionDialogFragment.java:60) -> com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
08-26 21:22:41.183 14102 14102 E DeckLog : 	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:168)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$HPzOdi9LOc_f-wA9GNnhc9LKQSM.subscribe(Unknown Source:6)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at io.reactivex.Observable.subscribe(Observable.java:12284)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-26 21:22:41.183 14102 14102 E DeckLog : 	at java.lang.Thread.run(Thread.java:764)
08-26 21:22:41.310   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:41.310   562  1037 D SurfaceFlinger: duplicate layer name: changing it.niedermann.nextcloud.deck/it.niedermann.nextcloud.deck.ui.ImportAccountActivity to it.niedermann.nextcloud.deck/it.niedermann.nextcloud.deck.ui.ImportAccountActivity#1
08-26 21:22:41.310   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:41.311   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:41.351  8619  8785 D ClClient: Not sending keepalive.  Current connection state=STOPPED
08-26 21:22:41.430   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:41.529   562   562 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 12 lines
08-26 21:22:41.529   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:41.544   562  1036 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=8529a87 it.niedermann.nextcloud.deck/it.niedermann.nextcloud.deck.ui.ImportAccountActivity)/@0x1ab1db4 - animation-leash#0
08-26 21:22:41.545   562  1036 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=Dim Layer for - Task=2211)/@0x6d18d52 - animation-leash#0
08-26 21:22:41.545   562  1036 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=8529a87 it.niedermann.nextcloud.deck/it.niedermann.nextcloud.deck.ui.ImportAccountActivity)/@0x1ab1db4 - animation-leash#0
08-26 21:22:41.545   562  1036 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=Dim Layer for - Task=2211)/@0x6d18d52 - animation-leash#0
08-26 21:22:41.545   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:41.680   562   562 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 10 lines
08-26 21:22:41.681   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-26 21:22:41.801 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connectApiWithBackoff] trying to connect..
08-26 21:22:41.801 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService for type [nextcloud]
08-26 21:22:41.801 14102 14102 D com.nextcloud.android.sso.api.NetworkRequest: [connect] connect() called [main] Account-Type: [nextcloud]
08-26 21:22:41.801 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Component name is: [com.nextcloud.client]
08-26 21:22:41.806  1008  1525 D ActivityManager: TabletMaster Service: not allowed start service : Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } callingUid 10179 callingPackage it.niedermann.nextcloud.deck
08-26 21:22:41.806  1008  1525 W ActivityManager: Unable to start service Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } U=0: not found
08-26 21:22:41.807 14102 14102 D com.nextcloud.android.sso.api.AidlNetworkRequest: [connect] Binding to AccountManagerService returned false
08-26 21:22:41.807 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] Error: [Binding to AccountManagerService returned false]
08-26 21:22:41.807 14102 14102 D com.nextcloud.android.sso.helper.ExponentialBackoff: [notifyFailed] retrying in: [3282ms]
08-26 21:22:42.862   562   562 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
```

**Comment by desperateCoder** [comment]
> 08-26 21:22:38.820  1008  1525 D ActivityManager: TabletMaster Service: not allowed start service : Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } callingUid 10179 callingPackage it.niedermann.nextcloud.deck
08-26 21:22:38.820  1008  1525 W ActivityManager: Unable to start service Intent { cmp=com.nextcloud.client/com.owncloud.android.services.AccountManagerService } U=0: not found

I guess that's what we're looking for. Who or what the hell is TabletMasterService?

**Comment by desperateCoder** [comment]
See this, below the post there is a guide you could try regarding "memory usage"

**Comment by HelplessFool** [comment]
That sorts it!!!!!  

Thank you.  I've been struggling with the memory usage stuff. 

I've done some further debugging so that the exact issue can be identified.  The results are as follows:

- Memory usage isn't the issue.
- Auto-start apps restrictions is.
    - Auto-start apps doesn't need to be permitted for Nextcloud.
    - Linked start-up apps does need to be permitted for Nextcloud (and appears to be blocked by default).

Right.  So, it wasn't anything to do with the app directly, but was that the Nextcloud app was being blocked.

Is that enough info to update the FAQ?

**Comment by stefan-niedermann** [comment]
Absolutely! Thank you very much for the great research! Let's keep this issue open until i found some time to update our README.md and maybe @David-Development wants to add some kind of "known issues" section in the SSO README.md?

**Comment by desperateCoder** [comment]
@HelplessFool your nick name seems to be a lie to me. Thanks for the badass research, your responsiveness and your cooperation, that helps you, us, and other users! Great job buddy!! ❤️

**Comment by stefan-niedermann** [comment]
Pull Request for updating the README.md of SSO: https://github.com/nextcloud/Android-SingleSignOn/pull/258
