### ISSUE TITLE
302

### ISSUE THREAD

**Issue by digitalrevisor** [stefan-niedermann/nextcloud-deck#661]
```
App Version: 0.6.0
App Version Code: 6000
App Flavor: fdroid

Files App Version Code: 30130090

---

OS Version: 4.14.117-perf-g85cd9ce(V12.0.1.0.QFDMIXM)
OS API Level: 29
Device: tucana
Manufacturer: Xiaomi
Model (and Product): Mi Note 10 (tucana)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP forespørsel feilet med status kode: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:202)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:98)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:366)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:169)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:146)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:109)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes
- [ ] No

**Expected behavior**

**Screenshots**

**Versions**
 - Nextcloud: 
 - Nextcloud Deck: 
 - Nextcloud Android: 
 - Nextcloud Android Deck: 

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [ ] No

**Stacktrace**

**Comment by stefan-niedermann** [comment]
[Why this issue has been closed](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed)

**Comment by digitalrevisor** [comment]
Deck sidemenu doesnt work well on android browser chrome.

Fix it pleace.

Same issue on android mobile app Deck as last time. I dont fix to connect
my account. It should be easier to log in for users!!!

Med vennleg helsing

Roger Hopland

Dagleg leiar - partner

[image: RG_logoikon_e-post (2)]

Revisorgruppen Fjordane AS

Naustdalsvegen 1B, 6800 Førde | Avdelinger - Bergen | Nordfjordeid | Stryn |
Måløy
*S:* +47 57824090 | *M:* +47 90077351 | *E:* roger@r-r.no | *W:* www.rg.no

[image: felles:Kunder:Revisorgruppen:UHY logos:UHY logo.eps]

Medlem av UHY International, en sammenslutning av uavhengige revisjons- og
konsulentselskaper


ons. 26. aug. 2020 kl. 13:26 skrev Niedermann IT-Dienstleistungen <
notifications@github.com>:

**Comment by digitalrevisor** [comment]
The issue is here.

```
App Version: 0.6.0
App Version Code: 6000
App Flavor: fdroid

Files App Version Code: 30130190

---

OS Version: 4.14.117-perf-gc3a294c(V12.0.2.0.QFDMIXM)
OS API Level: 29
Device: tucana
Manufacturer: Xiaomi
Model (and Product): Mi Note 10 (tucana)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException:
HTTP forespørsel feilet med status kode: 302
at
com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequest(AidlNetworkRequest.java:202)
at
com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequest(NextcloudAPI.java:119)
at
com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:98)
at
com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
at
com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown
Source:6)
at
io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
at
io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at
io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException:
at
com.nextcloud.android.sso.InputStreamBinder.processRequest(InputStreamBinder.java:366)
at
com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStream(InputStreamBinder.java:169)
at
com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequest(InputStreamBinder.java:146)
at
com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:109)
at android.os.Binder.execTransactInternal(Binder.java:1021)
at android.os.Binder.execTransact(Binder.java:994)

```

Med vennleg helsing

Roger Hopland

Dagleg leiar - partner

[image: RG_logoikon_e-post (2)]

Revisorgruppen Fjordane AS

Naustdalsvegen 1B, 6800 Førde | Avdelinger - Bergen | Nordfjordeid | Stryn |
Måløy
*S:* +47 57824090 | *M:* +47 90077351 | *E:* roger@r-r.no | *W:* www.rg.no

[image: felles:Kunder:Revisorgruppen:UHY logos:UHY logo.eps]

Medlem av UHY International, en sammenslutning av uavhengige revisjons- og
konsulentselskaper


fre. 21. aug. 2020 kl. 21:30 skrev Niedermann IT-Dienstleistungen <
notifications@github.com>:

**Comment by stefan-niedermann** [comment]
> Deck sidemenu doesnt work well on android browser chrome.

Let me quote the Guidelines for submitting bug reports: 

> * This repository is *only* for issues within the Nextcloud Deck Android app

Please open issues regarding the deck server app in the [correct repository](https://github.com/nextcloud/deck/issues/new?template=Bug_report.md).

>  I dont fix to connect my account. It should be easier to log in for users!!!

You are using version `0.6.0` of the Deck Android app. The current version is `1.9.7` (Yes, a few months and a new major version have passed in the meantime).

If you want support from us, i suggest you to

1. Update the Android app and read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) if you are experiencing troubles
2. Answer our questions
3. Fill in the complete issue template
4. Read the bug reporting guideline before posting any nonsense stuff

Last not least: Yelling with 3 `!!!` at us will not make us work quicker nor solve your troubles.
