### ISSUE TITLE
NPE (reported via E-Mail)

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#683]
```
App Version: 1.9.7
App Version Code: 1009007
App Flavor: play

Deck Server Version: 1.0.5

Files App Version Code: 30130090

---

OS Version: 4.14.116(10.0.0.177C432)
OS API Level: 29
Device: HWBKL
Manufacturer: HUAWEI
Model (and Product): BKL-L09 (BKL-L09)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Card.getStackId()' on a null object reference
 at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:194)
 at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:120)
 at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:146)
 at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:105)
 at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:85)
 at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$3$1.lambda$onResponse$0$SyncManager$3$1(SyncManager.java:236)
 at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$3$1$_pEMrPKc-nDkeuO3bebb8hu3RB0.run(Unknown Source:6)
 at java.lang.Thread.run(Thread.java:929)

```

**Comment by desperateCoder** [comment]
I'm pretty sure this is fixed with the clone cards feature. We just need to verify that after a release

**Comment by stefan-niedermann** [comment]
> tritt sporadisch auf. 
Sobald ich die Startseite von Deck öffne mit dem zuletzt geöffneten Board mit der zuletzt angesehenen Liste

**Comment by stefan-niedermann** [comment]
Should be fixed in the latest releases. If occurs again, open issue.

**Comment by thw26** [comment]
I'm not sure if this is the exact issue as referenced in this issue, but I am seeing the following error in the Nextcloud app when trying to add an account in the Deck app. Let me know if I can provide other information.

```
App Version: 1.13.5
App Version Code: 1013005
Server App Version: 1.2.3
App Flavor: fdroid
Files App Version Code: 30140190

---

OS Version: 4.14.191-g1960f4e93c00-ab6924778(6943376)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Card.getStackId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:208)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:129)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:179)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:122)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:101)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$2$1.lambda$onResponse$0$SyncManager$2$1(SyncManager.java:237)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$2$1$B5Glge0jtjic-sLIZD8UEHJ-hfQ.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by desperateCoder** [comment]
@thw26 well? that's really odd... In theory, it shouldn't be even possible to run into this error. But anyways, I added a null check to prevent this error. Should be fixed now.
