### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by bspire** [stefan-niedermann/nextcloud-deck#699]
I do repeatedly get the following synchronization error on Nextcloud Deck.

Is there anything I can do to get rid of this error?

````
App Version: 1.9.7
App Version Code: 1009007
App Flavor: play

Deck Server Version: 1.1.0

Files App Version Code: 30130190

---

OS Version: 4.14.113-19530501(G970FXXU8DTH7)
OS API Level: 29
Device: beyond0
Manufacturer: samsung
Model (and Product): SM-G970F (beyond0lteeea)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:168)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$HPzOdi9LOc_f-wA9GNnhc9LKQSM.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: {"status":500,"message":"An exception occurred while executing 'INSERT INTO `oc_deck_cards` (`title`, `stack_id`, `type`, `order`, `owner`, `description`, `created_at`, `last_modified`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params [\"https:\\\/\\\/www.bild.de\\\/bild-plus\\\/sparfochs\\\/2020\\\/sparfochs\\\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html\", 12, \"plain\", 0, \"stefan\", \"\", 1602410031, 1602410031]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1","exception":{"\u0000Doctrine\\DBAL\\Exception\\DriverException\u0000driverException":{"errorInfo":["22001",1406,"Data too long for column 'title' at row 1"]},"\u0000*\u0000message":"An exception occurred while executing 'INSERT INTO `oc_deck_cards` (`title`, `stack_id`, `type`, `order`, `owner`, `description`, `created_at`, `last_modified`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params [\"https:\\\/\\\/www.bild.de\\\/bild-plus\\\/sparfochs\\\/2020\\\/sparfochs\\\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html\", 12, \"plain\", 0, \"stefan\", \"\", 1602410031, 1602410031]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1","\u0000Exception\u0000string":"","\u0000*\u0000code":0,"\u0000*\u0000file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","\u0000*\u0000line":106,"\u0000Exception\u0000trace":[{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"-\u003E","args":["An exception occurred while executing 'INSERT INTO `oc_deck_cards` (`title`, `stack_id`, `type`, `order`, `owner`, `description`, `created_at`, `last_modified`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params [\"https:\\\/\\\/www.bild.de\\\/bild-plus\\\/sparfochs\\\/2020\\\/sparfochs\\\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html\", 12, \"plain\", 0, \"stefan\", \"\", 1602410031, 1602410031]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1",{"errorInfo":["22001",1406,"Data too long for column 'title' at row 1"]}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{},{"errorInfo":["22001",1406,"Data too long for column 'title' at row 1"]},"An exception occurred while executing 'INSERT INTO `oc_deck_cards` (`title`, `stack_id`, `type`, `order`, `owner`, `description`, `created_at`, `last_modified`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params [\"https:\\\/\\\/www.bild.de\\\/bild-plus\\\/sparfochs\\\/2020\\\/sparfochs\\\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html\", 12, \"plain\", 0, \"stefan\", \"\", 1602410031, 1602410031]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":1063,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{},{"errorInfo":["22001",1406,"Data too long for column 'title' at row 1"]},"INSERT INTO `oc_deck_cards` (`title`, `stack_id`, `type`, `order`, `owner`, `description`, `created_at`, `last_modified`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)",{"1":"https:\/\/www.bild.de\/bild-plus\/sparfochs\/2020\/sparfochs\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html","2":12,"3":"plain","4":0,"5":"stefan","6":"","7":1602410031,"8":1602410031}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/DB\/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"-\u003E","args":["INSERT INTO `oc_deck_cards` (`title`, `stack_id`, `type`, `order`, `owner`, `description`, `created_at`, `last_modified`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)",["https:\/\/www.bild.de\/bild-plus\/sparfochs\/2020\/sparfochs\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html",12,"plain",0,"stefan","",1602410031,1602410031],[2,1,2,1,2,2,1,1]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php","line":203,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"-\u003E","args":["INSERT INTO `oc_deck_cards` (`title`, `stack_id`, `type`, `order`, `owner`, `description`, `created_at`, `last_modified`) VALUES(:dcValue1, :dcValue2, :dcValue3, :dcValue4, :dcValue5, :dcValue6, :dcValue7, :dcValue8)",{"dcValue1":"https:\/\/www.bild.de\/bild-plus\/sparfochs\/2020\/sparfochs\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html","dcValue2":12,"dcValue3":"plain","dcValue4":0,"dcValue5":"stefan","dcValue6":"","dcValue7":1602410031,"dcValue8":1602410031},{"dcValue1":2,"dcValue2":1,"dcValue3":2,"dcValue4":1,"dcValue5":2,"dcValue6":2,"dcValue7":1,"dcValue8":1}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php","line":216,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"-\u003E","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/QBMapper.php","line":129,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"-\u003E","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Db\/CardMapper.php","line":70,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"-\u003E","args":[{"title":"https:\/\/www.bild.de\/bild-plus\/sparfochs\/2020\/sparfochs\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html","description":"","stackId":12,"type":"plain","lastModified":1602410031,"lastEditor":null,"createdAt":1602410031,"labels":null,"assignedUsers":null,"attachments":null,"attachmentCount":null,"owner":"stefan","order":0,"archived":false,"duedate":null,"deletedAt":0,"commentsUnread":0,"id":null,"overdue":0}]},{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Service\/CardService.php","line":203,"function":"insert","class":"OCA\\Deck\\Db\\CardMapper","type":"-\u003E","args":[{"title":"https:\/\/www.bild.de\/bild-plus\/sparfochs\/2020\/sparfochs\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html","description":"","stackId":12,"type":"plain","lastModified":1602410031,"lastEditor":null,"createdAt":1602410031,"labels":null,"assignedUsers":null,"attachments":null,"attachmentCount":null,"owner":"stefan","order":0,"archived":false,"duedate":null,"deletedAt":0,"commentsUnread":0,"id":null,"overdue":0}]},{"file":"\/var\/www\/nextcloud\/apps\/deck\/lib\/Controller\/CardApiController.php","line":83,"function":"create","class":"OCA\\Deck\\Service\\CardService","type":"-\u003E","args":["https:\/\/www.bild.de\/bild-plus\/sparfochs\/2020\/sparfochs\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html",12,"plain",0,"stefan","",null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"create","class":"OCA\\Deck\\Controller\\CardApiController","type":"-\u003E","args":["https:\/\/www.bild.de\/bild-plus\/sparfochs\/2020\/sparfochs\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html","plain",0,"",null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"-\u003E","args":[{},"create"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"-\u003E","args":[{},"create"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Deck\\Controller\\CardApiController","create",{},{"boardId":"3","stackId":"12","_route":"deck.card_api.create"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"-\u003E","args":[{"boardId":"3","stackId":"12","_route":"deck.card_api.create"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{},{"boardId":"3","stackId":"12","_route":"deck.card_api.create"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1012,"function":"match","class":"OC\\Route\\Router","type":"-\u003E","args":["\/apps\/deck\/api\/v1.0\/boards\/3\/stacks\/12\/cards"]},{"file":"\/var\/www\/nextcloud\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"\u0000Exception\u0000previous":{"errorInfo":["22001",1406,"Data too long for column 'title' at row 1"]}}}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1056)
	at android.os.Binder.execTransact(Binder.java:1029)

````

**Comment by stefan-niedermann** [comment]
This seems to be an issue of the recently released server app version `1.1.0`.
@juliushaertl can you have a look please?

**Comment by stefan-niedermann** [comment]
Can you try to delete the card with the link to bild.de? `\\\/bild-plus\\\/sparfochs\\\/2020\\\/sparfochs\\\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html`

**Comment by desperateCoder** [comment]
> Data too long for column 'title' at row 1"

Guess we should limit the title length @stefan-niedermann 
Guess you should validate that, too @juliushaertl 

@bspire shortening the title or renaming the card might already do the trick. If nothing works: try deleting the card as @stefan-niedermann stated

**Comment by stefan-niedermann** [comment]
@desperateCoder we **have** limited the title length (to `100` characters until server version `1.0.0` and to `255` characters bginning with server version `1.0.0`) :thinking: (see [1](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/model/ocs/Version.java#L163) and [](https://github.com/stefan-niedermann/nextcloud-deck/blob/88df72060dfc1d08d881577392cf711547760280/app/src/main/java/it/niedermann/nextcloud/deck/ui/card/EditActivity.java#L238)), so this should not even be possible. Guess i have to check whether this limitation works correctly for

- [ ] Pasting stuff from the clipboard
- [ ] Attach to new card via share menu

@bspire i guess you copy & pasted this url?

**Comment by bspire** [comment]
> Can you try to delete the card with the link to bild.de? `\\\/bild-plus\\\/sparfochs\\\/2020\\\/sparfochs\\\/mit-der-richtigen-strategie-klappt-es-ausgesorgt-haben-sie-wenn-73025862.bild.html`

The card does not exist anymore. I already deleted it on the mobile app. However, synchronization error still occurs.

**Comment by bspire** [comment]
> @bspire i guess you copy & pasted this url?

If I remember correctly, I created a new card via the Share functionality on Android.

**Comment by desperateCoder** [comment]
> The card does not exist anymore. 

Weird. Then please try to wipe the app data and reconnect to your account afterwards. This should definitely fix it. But make sure, any other changes are already synced to the server first.

**Comment by bspire** [comment]
> > The card does not exist anymore.
> 
> Weird. Then please try to wipe the app data and reconnect to your account afterwards. This should definitely fix it. But make sure, any other changes are already synced to the server first.

Clearing app data resolves the issue. 

Still weird how the problem could arise.

**Comment by stefan-niedermann** [comment]
Glad to hear the problem is solved for you :) I guess we maybe are missing a check when sharing into a new note. I will have a look.

Though it's strange that the sync error still happened after you deleted the card - maybe @desperateCoder has an idea about this behavior?

**Comment by bspire** [comment]
I can reproduce the issue when sharing a link from BILD app into a new deck card. On first synchronization the loading indicator in the app does not disappear. It seems like synchronization does not finish.

**Comment by juliushaertl** [comment]
>  Guess you should validate that, too @juliushaertl

See server app issue https://github.com/nextcloud/deck/issues/1923 for that

**Comment by stefan-niedermann** [comment]
Okay then: I just opened an issue to check whether the validations are correctly in the Android app (which i believe): https://github.com/stefan-niedermann/nextcloud-deck/issues/702

I strongly believe that the Android app checks it correctly (255 characters), but you are missing a database migration in the server app, as @juliushaertl described in the linked issue https://github.com/nextcloud/deck/issues/1923#issuecomment-633412233

There is a possible fix mentioned (https://github.com/nextcloud/deck/issues/1923#issuecomment-667698605) but i would be careful and do a backup before trying it!!

I suggest to subscribe the linked issue and talk to the server apps developer about a proper fix of the server apps database - there is nothing we can do on the Android Apps side (except double checking that we are doing the validations really correctly as mentioned im my first paragraph).

Sorry for the trouble.
