### ISSUE TITLE
Exception After Selecting Account (FileDescriptor)

### ISSUE THREAD

**Issue by binaryatrocity** [stefan-niedermann/nextcloud-deck#748]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
After selecting an account to use, and allowing the app access the the account in question an exception is immediately thrown at which point I'm presented an error detail window. Closing this detail window takes me back to the Login/Select Account view.

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes
- [X] No

1. Open App
2. Select Account
3. Allow permission to use selected Account

**Expected behavior**
I'd expect the account association to finish successfully and the boards for that account visible.

**Versions**
 - Nextcloud: 20.0.2
 - Nextcloud Deck: 1.2.2
 - Nextcloud Android: 3.6.0
 - Nextcloud Android Deck: 1.12.1

**Smartphone (please complete the following information):**
- Device: Pixel 1 XL
- Android-Version: 10
- App-Store:
  - [X] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [X] No

**Stacktrace**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
 at android.os.ParcelFileDescriptor$AutoCloseInputStream.<init>(ParcelFileDescriptor.java:941)
 at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:166)
 at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
 at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
 at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
 at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)
```

**Comment by desperateCoder** [comment]
Hi @binaryatrocity, thanks for your report!
Sorry to hear that you have these issue. Reading the Stacktrace, it seems to be a problem in the communication between the Nextcloud Files app and our Deck app. 

Have you tried clearing the local storage of both apps as described [here](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error)? Just make sure you have your credentials for your Nextcloud account, since you will have to re-login in the Files app after storage deletion. 

If even that doesn't help, please tell us!

**Comment by binaryatrocity** [comment]
I had tried that, and it didn't help, tried it again just to be sure. It did seem like the Nextcloud Android app was having issues clearing its storage, as it was never asking me to login...

I uninstalled the base Nextcloud app entirely, then re-installed which did force a re-authentication. After this process the Nextcloud Deck app is functioning as expected.

**Comment by desperateCoder** [comment]
Oh wow, good job on reading the hints! And thanks for the feedback! 
We're glad it worked out for you, feel free to open an issue here any time, if you encounter further issues :smiley:
