### ISSUE TITLE
Nullpointerexception

### ISSUE THREAD

**Issue by droogi** [stefan-niedermann/nextcloud-deck#798]
Hallo Herr Niedermann
Diese Fehlermeldung hab ich beim Start der Android App bekommen.
Gruß Ralf

```
Full Crash:

App Version: 1.13.5
App Version Code: 1013005
App Flavor: fdroid

Files App Version Code: 30140190

---

OS Version: 4.14.117-perf-gaf11d57(V12.0.1.0.QCXEUXM)
OS API Level: 29
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_eea)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'void it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentAdapter.applyBrand(int)' on a null object reference
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment.applyBrand(CardAttachmentsFragment.java:518)
	at it.niedermann.nextcloud.deck.ui.branding.BrandedFragment.onStart(BrandedFragment.java:19)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:2731)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1206)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2595)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:258)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:550)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at it.niedermann.nextcloud.deck.ui.branding.BrandedActivity.onStart(BrandedActivity.java:22)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
	at android.app.Activity.performStart(Activity.java:7946)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3334)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

!-
Guidelines for submitting bug reports:

* Bug reports which do not fill the complete issue template will be closed.
* Please have a look at our [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
* Please search the existing issues first, it's likely that your issue was already reported or even fixed.
* This repository is *only* for issues within the Nextcloud Deck Android app
-->
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes
- [ ] No

**Expected behavior**

**Screenshots**

**Versions**
 - Nextcloud: 
 - Nextcloud Deck: 
 - Nextcloud Android: 
 - Nextcloud Android Deck: 

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [ ] No

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Danke fürs Bescheid geben! Das scheint ein Duplikat von #782 zu sein.

Wir werden das Thema in #782 weiter verfolgen.
