### ISSUE TITLE
Move to new created board: NPE in CardPropagationDataProvider

### ISSUE THREAD

**Issue by droogi** [stefan-niedermann/nextcloud-deck#831]
When moving a card into a new created board

```
App Version: 1.14.0
App Version Code: 1014000
App Flavor: fdroid

Files App Version Code: 30140390

---

OS Version: 4.14.117-perf-g847c8aa(V12.0.2.0.QCXEUXM)
OS API Level: 29
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_eea)

---

java.lang.RuntimeException: unable to create card in moveCard target
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$18.onError(SyncManager.java:1384)
	at it.niedermann.nextcloud.deck.api.IResponseCallback.onError(IResponseCallback.java:31)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:60)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$moveCard$33$SyncManager(SyncManager.java:1373)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$SBastKzuS5p-UBPyMLNRlcRv948.getData(Unknown Source:12)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.LiveDataHelper$LiveDataWrapper$-CC.$default$postResult(LiveDataHelper.java:28)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$SBastKzuS5p-UBPyMLNRlcRv948.postResult(Unknown Source:0)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.LiveDataHelper.lambda$wrapInLiveData$6(LiveDataHelper.java:90)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.-$$Lambda$LiveDataHelper$Uzgp_OpCAeh6OBPcAsI_KtzEV6A.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:22)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardPropagationDataProvider.createOnServer(CardPropagationDataProvider.java:12)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:38)
	... 7 more

**Comment by desperateCoder** [comment]
This is already fixed by https://github.com/stefan-niedermann/nextcloud-deck/commit/b72131984a60982e3b59d8deb773b6dffe8e4ce9

@stefan-niedermann is this commit already released? (committed on Feb 7, 2021)

Maybe all @droogi needs to do is update Deck?
