### ISSUE TITLE
Konto neu angelegt, offline

### ISSUE THREAD

**Issue by droogi** [stefan-niedermann/nextcloud-deck#832]
```
App Version: 1.14.0
App Version Code: 1014000
Server App Version: 0.6.4
App Flavor: fdroid

Files App Version Code: 30140390

---

OS Version: 4.14.117-perf-gaf11d57(V12.0.1.0.QCXEUXM)
OS API Level: 29
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_eea)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to myserver (port 443) from /100.101.203.26 (port 37297) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by stefan-niedermann** [comment]
> Connection timed out

This error happens when your server does not respond within 1 minute. Sorry, but i am afraid, there is nothing we can do on the apps side unfortunately. You should check your server logs for further investigations.
