### ISSUE TITLE
phone was offline

### ISSUE THREAD

**Issue by droogi** [stefan-niedermann/nextcloud-deck#833]
```
App Version: 3.1.0
App Version Code: 3001000
App Flavor: fdroid

Files App Version Code: 30140390

---

OS Version: 4.14.117-perf-gaf11d57(V12.0.1.0.QCXEUXM)
OS API Level: 29
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_eea)

---

java.lang.IllegalStateException: FragmentManager has been destroyed
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1737)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:181)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$19$MainActivity(MainActivity.java:813)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$7QY_vC2-nmSxaAA_GFfRH1ajclg.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by stefan-niedermann** [comment]
This is not about the Nextcloud Deck app.
