### ISSUE TITLE
collected error #4

### ISSUE THREAD

**Issue by droogi** [stefan-niedermann/nextcloud-deck#834]
```
App Version: 1.14.0
App Version Code: 1014000
Server App Version: 1.0.5
App Flavor: fdroid

Files App Version Code: 30140390

---

OS Version: 4.14.117-perf-gaf11d57(V12.0.1.0.QCXEUXM)
OS API Level: 29
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_eea)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment.lambda$uploadNewAttachmentFromUri$10$CardAttachmentsFragment(CardAttachmentsFragment.java:447)
	at it.niedermann.nextcloud.deck.ui.card.attachments.-$$Lambda$CardAttachmentsFragment$x_W-6COTfOk7tPW7y-Zoi9uS3Iw.onChanged(Unknown Source:8)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.LiveDataHelper$2.onChanged(LiveDataHelper.java:79)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:70)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:19)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:38)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:22)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$addAttachmentToCard$45$SyncManager(SyncManager.java:1886)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$KD-Ecr8weWP1qwzO8ewm3qWgFFw.run(Unknown Source:12)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Hallo @droogi vielen herzlichen Dank für das Sammeln der Fehler und das zusenden dieser. Das hilft uns, Fehler zu finden, die in Umgebungen auftreten, die wir so nicht vorhersehen konnten. Ein paar Kleinigkeiten möchte ich dir jedoch mit auf den Weg geben:

1. Du hast kein einziges mal das Issue-Template verwendet. Dieses ist aus einem Grund da. Eine blanke Fehlermeldung hilft uns leider nicht sehr viel, wenn wir nicht Schritte bekommen, wie diese zu reproduzieren sind. Ich frage mich daher, was dich dazu veranlasst hat, das Template aus dem Issue zu entfernen, bevor du es eröffnet hast?
2. Würde ich dich bitten, hier auf englisch zu schreiben. Nicht alle Beitragenden sprechen Deutsch und für andere User, die über die selbe Fehlermeldung via Google stolpern, sind deutsche Tickets nicht hilfreich
3. Hast du ja bereits bemerkt, dass ich einige der Issues geschlossen hatte. Dies geschieht nicht aus bösem Willen, sondern weil offensichtlich ein Problem auf deiner Seite vorliegt (Server, Infrastruktur, ...), das *wir* nicht beheben können.
4. Update bitte auf die letzte verfügbare Version (die bei F-Droid mindestens `1.14.4` ist)!
5. Bitte lies dir den folgenden Abschnitt durch, bevor du weitere Issues öffnest: [Why has my bug report been closed?](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed)

Für diesen konkreten Fall hier kann ich z. B. ohne Schritte zum Nachstellen leider nicht weiterhelfen. So hatten wir in [`1.14.2`](https://github.com/stefan-niedermann/nextcloud-deck/releases/tag/1.14.2) einen Fehler behoben, wenn ein Anhang direkt aus Nextcloud hinzugefügt wurde, der sich identisch ausgewirkt hat. Hast du das getan? Wenn nicht, was dann?

**Comment by droogi** [comment]
Hallo Stefan,
Ich hatte in der letzten Mail dich geschrieben, das ich die Fehler gesammelt hatte, als das Telefon offline war. Ich hab leider nicht aufgepasst, was ich genau gemacht hatte. Deswegen auch die "falschen Templates" und auf Deutsch.
Bitte wieder schließen falls nicht hilfreich.
War nicht bös gemeint. Ich probier das nächste Mal richtige Reporte auf Englisch zu schreiben.
Gruß Ralf

Am 16. Februar 2021 09:07:25 MEZ schrieb Niedermann IT-Dienstleistungen <notifications@github.com>:
>Hallo @droogi vielen herzlichen Dank für das Sammeln der Fehler und das
>zusenden dieser. Das hilft uns, Fehler zu finden, die in Umgebungen
>auftreten, die wir so nicht vorhersehen konnten. Ein paar Kleinigkeiten
>möchte ich dir jedoch mit auf den Weg geben:>
>>
>1. Du hast kein einziges mal das Issue-Template verwendet. Dieses ist
>aus einem Grund da. Eine blanke Fehlermeldung hilft uns leider nicht
>sehr viel, wenn wir nicht Schritte bekommen, wie diese zu reproduzieren
>sind. Ich frage mich daher, was dich dazu veranlasst hat, das Template
>aus dem Issue zu entfernen, bevor du es eröffnet hast?>
>2. Würde ich dich bitten, hier auf englisch zu schreiben. Nicht alle
>Beitragenden sprechen Deutsch und für andere User, die über die selbe
>Fehlermeldung via Google stolpern, sind deutsche Tickets nicht
>hilfreich>
>3. Hast du ja bereits bemerkt, dass ich einige der Issues geschlossen
>hatte. Dies geschieht nicht aus bösem Willen, sondern weil
>offensichtlich ein Problem auf deiner Seite vorliegt (Server,
>Infrastruktur, ...), das *wir* nicht beheben können.>
>4. Update bitte auf die letzte verfügbare Version (die bei F-Droid
>mindestens `1.14.4` ist)!>
>5. Bitte lies dir den folgenden Abschnitt durch, bevor du weitere
>Issues öffnest: [Why has my bug report been
>closed?](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed)>
>>
>Für diesen konkreten Fall hier kann ich z. B. ohne Schritte zum
>Nachstellen leider nicht weiterhelfen. So hatten wir in
>[`1.14.2`](https://github.com/stefan-niedermann/nextcloud-deck/releases/tag/1.14.2)
>einen Fehler behoben, wenn ein Anhang direkt aus Nextcloud hinzugefügt
>wurde, der sich identisch ausgewirkt hat. Hast du das getan? Wenn
>nicht, was dann?>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/stefan-niedermann/nextcloud-deck/issues/834#issuecomment-779660988

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by stefan-niedermann** [comment]
Alles klar, danke für die Infos. Für diesen konkreten Fall bin ich mir ziemlich sicher, dass er sich mit Version `1.14.2` bereits behoben wurde.

Die weiteren Issues habe ich wie gesagt geschlossen und ein Issue (das beim Verschieben von Karten) werden wir näher untersuchen.

Viele Grüße

Stefan

**Comment by stefan-niedermann** [comment]
PS.: Bitte auch die Nextcloud App updaten, die ist ebenfalls veraltet. Auf F-Droid ist mindestens version `3.15.x` vorhanden. :wink:

**Comment by droogi** [comment]
Das war nochmal ein Bedien Fehler von mir, die Paket Quellen waren nicht aktuell, das musste ich händisch machen, deswegen wurden alle  Apps als aktuell angezeigt

Am 16. Februar 2021 09:26:13 MEZ schrieb Niedermann IT-Dienstleistungen <notifications@github.com>:
>PS.: Bitte auch die Nextcloud App updaten, die ist ebenfalls veraltet.
>Auf F-Droid ist mindestens version `3.15.x` vorhanden. :wink: 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/stefan-niedermann/nextcloud-deck/issues/834#issuecomment-779670478

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
