### ISSUE TITLE
Unexpected error? 

### ISSUE THREAD

**Issue by MediaPlusPL** [stefan-niedermann/nextcloud-deck#849]
```
Full Crash:

App Version: 1.14.6
App Version Code: 1014006
App Flavor: play

Files App Version Code: 30150090

---

OS Version: 4.4.23+(354(C432))
OS API Level: 26
Device: HWRNE
Manufacturer: HUAWEI
Model (and Product): RNE-L21 (RNE-L21)

---

android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DeckComment.accountId, DeckComment.id (Sqlite code 2067), (OS error - 0:Success)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:770)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:769)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(FrameworkSQLiteStatement.java:46)
	at androidx.room.EntityDeletionOrUpdateAdapter.handleMultiple(EntityDeletionOrUpdateAdapter.java:108)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CommentDao_Impl.update(CommentDao_Impl.java:261)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CommentDao_Impl.update(CommentDao_Impl.java:28)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.DataBaseAdapter.updateComment(DataBaseAdapter.java:1044)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.DeckCommentsDataProvider.updateInDB(DeckCommentsDataProvider.java:99)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.DeckCommentsDataProvider.updateInDB(DeckCommentsDataProvider.java:17)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper$1.lambda$onResponse$0$DataPropagationHelper$1(DataPropagationHelper.java:48)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.-$$Lambda$DataPropagationHelper$1$ZLB9lqGVaRAjfS24BuCbRIzxzUk.run(Unknown Source:16)
	at java.lang.Thread.run(Thread.java:784)

```

**Comment by desperateCoder** [comment]
Hi @MediaPlusPL,
thanks for your report.  I can see from the stacktrace that you tried to create a comment. The error is, that the ID for the comment returned by the server already exists on your device, this shouldn't be possible to happen. 

Can you please describe the steps you made to get this error? Can you reproduce the error? How many accounts have you connected to your Deck app?

Also, please fill the issue template the next time, so I don't have to ask you so much stuff afterwards. I already told you so here: https://github.com/stefan-niedermann/nextcloud-deck/issues/782#issuecomment-751883710 and if you keep ignoring this, we'll not further investigate your problems and just close your tickets due to lack of willing to cooperate.

**Comment by stefan-niedermann** [comment]
Ping @MediaPlusPL please have a look at [the comment](https://github.com/stefan-niedermann/nextcloud-deck/issues/849#issuecomment-784995762) written by @desperateCoder and answer his questions.

**Comment by stefan-niedermann** [comment]
[Why this issue has been closed](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
