### ISSUE TITLE
I met the next error

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#874]
```
App Version: 1.15.4
App Version Code: 1015004
Server App Version: 1.2.5
App Flavor: play

Files App Version Code: 30150190

---

OS Version: 4.14.116(10.0.0.221C10)
OS API Level: 29
Device: HWHRY-H
Manufacturer: HUAWEI
Model (and Product): HRY-LX1 (HRY-LX1RU)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Card.getStackId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.goDeeperForUpSync(CardDataProvider.java:290)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.StackDataProvider.goDeeperForUpSync(StackDataProvider.java:129)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.BoardDataProvider.goDeeperForUpSync(BoardDataProvider.java:179)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:122)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper.doUpSyncFor(SyncHelper.java:101)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$2$1.lambda$onResponse$0$SyncManager$2$1(SyncManager.java:243)
	at it.niedermann.nextcloud.deck.persistence.sync.-$$Lambda$SyncManager$2$1$B5Glge0jtjic-sLIZD8UEHJ-hfQ.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:929)

```

**Comment by desperateCoder** [comment]
Hi @neerro, I'm a little confused, did you close this issue on purpose?

**Comment by neerro** [comment]
Hi @desperateCoder, I've just forwarded this issue to mobile app, as I have the problem with it. If it will be correct I re invoke the issue here.

**Comment by neerro** [comment]
Thanks god and @stefan-niedermann of course :) The issue has gone. Thanks! I've just installed the new app version and all work well.

**Comment by neerro** [comment]
Hi! I met the same issue again after the server version of nextcloud was updated from 20 to 21.
Installed app version on mobile device is 1.15.9, server version of Deck is 1.3.1.
Help please!

**Comment by desperateCoder** [comment]
Ok, thanks for the report, I'll have a look!

**Comment by desperateCoder** [comment]
This seems to be a very weird constellation... logically this schouldn't be possible to happen, but somehow it seems there is a way the data can get corrupted this way, so it fails at that point.

I added a check on this, the error shouldn't occur any more. The fix will be shipped with the next update.

I'm closing this, because it should be bulletproof now. If you encounter any further issues, feel free to reopen it!
