### ISSUE TITLE
Analyze 404 in OcsProjectDataProvider

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-deck#897]
I recently noticed that i got a few `404` logs in my logcat in the `OcsProjectDataProvider`. I am not entirely sure what causes this, but my assumption is, that we previously had a project which might have been deleted in the meantime.

I also left a `ToDo` in `OcsProjectDataProvider#getAllFromServer` → This issue is about analyzing whether my theory is correct and the problem is reproducible and to find a solution. In this case we should maybe catch `NextcloudHttpException` and check whether the status is `404` and delete this project locally?

```
2021-03-25 16:59:18.441 27168-27657/it.niedermann.nextcloud.deck.dev E/DeckLog: onError() (OcsProjectDataProvider.java:37) -> com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 404
        at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
        at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
        at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
        at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.IllegalStateException: {"ocs":{"meta":{"status":"failure","statuscode":404,"message":"Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services.\n"},"data":[]}}
    
        at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
        at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
        at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
        at android.os.Binder.execTransactInternal(Binder.java:1177)
        at android.os.Binder.execTransact(Binder.java:1141)
```

**Comment by stefan-niedermann** [comment]
Closing because of https://help.nextcloud.com/t/deck-android-1-17-upcoming-cards/113286#regarding-project-relationships

(The longer i think about this, it might also have been caused by [a dead account](https://github.com/stefan-niedermann/nextcloud-deck/issues/923))
