### ISSUE TITLE
Switching accounts crashes the app

### ISSUE THREAD

**Issue by q-wertz** [stefan-niedermann/nextcloud-deck#933]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
When trying to switch the account, the app crashes. The reason why I tried to switch it is because I think I could not see a newly shared Deck and thought I might get a resync when switching between the accounts (maybe related to https://github.com/stefan-niedermann/nextcloud-deck/issues/694).
Maybe important: The apps says `Letzte Hintergrundsynchronisierung: Vor 5 Stunden` 
I don't know if the not synced board caused the issue…

1. Go to 'Profile Picture' and try to change the account
2. App crashes completely
3. Account sometimes seems to be changed, sometimes not

**Expected behavior**
Account is switched

**Versions**
 - Nextcloud: 20.0.8
 - Nextcloud Deck: 1.2.6
 - Nextcloud Android: 3.15.1
 - Nextcloud Android Deck: 1.16.2

**Smartphone (please complete the following information):**
 - Device: Nokia 7 plus
- Android-Version: 10
- App-Store: F-Droid

**Stacktrace**

```

Full Crash:

App Version: 1.16.2

App Version Code: 1016002

App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.4.192-perf+(00WW*4*16G)

OS API Level: 29

Device: B2N_sprout

Manufacturer: HMD Global

Model (and Product): Nokia 7 plus (Onyx_00WW)

---

java.lang.ExceptionInInitializerError

	at f.a.a.c.d$a.a(Unknown Source:0)

	at f.a.a.c.d.c(Unknown Source:27)

	at androidx.viewpager2.widget.b.c(Unknown Source:18)

	at androidx.viewpager2.widget.b.c(Unknown Source:18)

	at androidx.viewpager2.widget.e.d(Unknown Source:4)

	at androidx.viewpager2.widget.e.m(Unknown Source:23)

	at androidx.viewpager2.widget.ViewPager2.k(Unknown Source:84)

	at androidx.viewpager2.widget.ViewPager2.j(Unknown Source:6)

	at it.niedermann.nextcloud.deck.ui.MainActivity.J0(Unknown Source:8)

	at it.niedermann.nextcloud.deck.ui.MainActivity.K0(Unknown Source:0)

	at it.niedermann.nextcloud.deck.ui.f1.run(Unknown Source:8)

	at android.app.Activity.runOnUiThread(Activity.java:6904)

	at it.niedermann.nextcloud.deck.ui.MainActivity.z1(Unknown Source:140)

	at it.niedermann.nextcloud.deck.ui.MainActivity.A1(Unknown Source:0)

	at it.niedermann.nextcloud.deck.ui.e1.a(Unknown Source:4)

	at androidx.lifecycle.LiveData.d(Unknown Source:29)

	at androidx.lifecycle.LiveData.e(Unknown Source:44)

	at androidx.lifecycle.LiveData.p(Unknown Source:14)

	at androidx.lifecycle.x.p(Unknown Source:0)

	at androidx.lifecycle.f0$c.a(Unknown Source:27)

	at androidx.lifecycle.v$a.a(Unknown Source:20)

	at androidx.lifecycle.LiveData.d(Unknown Source:29)

	at androidx.lifecycle.LiveData.e(Unknown Source:44)

	at androidx.lifecycle.LiveData.p(Unknown Source:14)

	at androidx.lifecycle.LiveData$a.run(Unknown Source:18)

	at android.os.Handler.handleCallback(Handler.java:883)

	at android.os.Handler.dispatchMessage(Handler.java:100)

	at android.os.Looper.loop(Looper.java:214)

	at android.app.ActivityThread.main(ActivityThread.java:7397)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: com.google.android.material.tabs.TabLayout.selectTab [class com.google.android.material.tabs.TabLayout$g, boolean]

	at f.a.a.c.d$a.b(Unknown Source:12)

	at f.a.a.c.d$a.<clinit>(Unknown Source:17)

	... 32 more

Caused by: java.lang.NoSuchMethodException: com.google.android.material.tabs.TabLayout.selectTab [class com.google.android.material.tabs.TabLayout$g, boolean]

	at java.lang.Class.getMethod(Class.java:2072)

	at java.lang.Class.getDeclaredMethod(Class.java:2050)

	at f.a.a.c.d$a.b(Unknown Source:0)

	... 33 more

```

**Comment by stefan-niedermann** [comment]
Please see this issue: https://github.com/stefan-niedermann/nextcloud-deck/issues/930#issuecomment-818025817

**Comment by q-wertz** [comment]
Sorry didn't see that one :facepalm: 
Maybe I should not try to open bug reports late at night

Thanks for the fix :)

**Comment by stefan-niedermann** [comment]
Oh boy, until now i have closed [3 issues](https://github.com/stefan-niedermann/nextcloud-deck/issues?q=is%3Aissue+is%3Aclosed) in this repository, [4 issues](https://github.com/nextcloud/deck/issues?q=is%3Aissue+is%3Aclosed) in the server repository, [20 issues](https://github.com/stefan-niedermann/nextcloud-notes/issues?q=is%3Aissue+is%3Aclosed) in the notes repository, i was [called douchebag](https://github.com/stefan-niedermann/nextcloud-notes/issues/1133#issuecomment-818193090) and i have answered round about 40 e-Mails, so for sure you are my least problem :smile: 

Thank you for your understanding and have a nice week :wave:
