### ISSUE TITLE
Deck don't want to start

### ISSUE THREAD

**Issue by fraengii** [stefan-niedermann/nextcloud-deck#939]
```
Full Crash:

App Version: 1.17.2
App Version Code: 1017002
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 3.18.60-SHIFT-00389-gae8e9feb3f67(1592466613)
OS API Level: 26
Device: SHIFT6m
Manufacturer: SHIFT
Model (and Product): SHIFT6m (SHIFT6m_EEA)

---

java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteException: table "Board" already exists (code 1): , while compiling: CREATE TABLE "Board" (`localId` INTEGER PRIMARY KEY AUTOINCREMENT, `accountId` INTEGER NOT NULL, `id` INTEGER, `status` INTEGER NOT NULL, `lastModified` INTEGER, `lastModifiedLocal` INTEGER, `title` TEXT, `ownerId` INTEGER NOT NULL, `color` INTEGER, `archived` INTEGER NOT NULL, `shared` INTEGER NOT NULL, `deletedAt` INTEGER, `permissionRead` INTEGER NOT NULL, `permissionEdit` INTEGER NOT NULL, `permissionManage` INTEGER NOT NULL, `permissionShare` INTEGER NOT NULL, `etag` TEXT, FOREIGN KEY(`ownerId`) REFERENCES `User`(`localId`) ON UPDATE NO ACTION ON DELETE CASCADE , FOREIGN KEY(`accountId`) REFERENCES `Account`(`id`) ON DELETE CASCADE )
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:905)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:516)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1703)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1633)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.migration.Migration_30_31.migrate(Migration_30_31.java:43)
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:99)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:299)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:276)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:273)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	... 3 more

```

**Comment by desperateCoder** [comment]
Hi, thanks for the report.

This issue is known and already fixed, see here: https://github.com/stefan-niedermann/nextcloud-deck/issues/936#issuecomment-820216729
