### ISSUE TITLE
Ability to archive cards

### ISSUE THREAD

**Issue by stalker314314** [stefan-niedermann/nextcloud-deck#94]
Seems that only thing missing for my use case is ability to archive cards on mobile:) Let's narrow this issue down to *only* implement archiving action (and not go into showing[1]/unarchiving...)

I am sorry if this exists, but I see menu item and I get "not implemented yet".

[1] When I archive card from Web, I still see it in Android app

**Comment by desperateCoder** [comment]
Hi @stalker314314,
thanks for your request! I'd say this one is a low hanging fruit, since it is just an update call, which in fact sould already work. Just some missing wiring. I'll have a look at this as soon as possible.

**Comment by desperateCoder** [comment]
Hi @stalker314314 
I played around a little, i think it should work already, but there is still some work left.

Would be great if you could confirm it with the latest master!

**Comment by stalker314314** [comment]
I tried with master, but I am not sure what to expect. I create item **test item** from web and try to archive from Android. I do not get any feedback on Android (item is still there, no toast), this is what I get in logcat:
```
2019-06-17 21:45:14.324 6532-7442/it.niedermann.nextcloud.deck D/deck: parseCard() (JsonToEntityParser.java:133) -> {"title":"test item","description":"","stackId":3,"type":"plain","lastModified":1560800716,"lastEditor":null,"createdAt":1560800689,"labels":[],"assignedUsers":null,"attachments":null,"attachmentCount":null,"owner":{"primaryKey":"username","uid":"username","displayname":"my name"},"order":999,"archived":false,"duedate":null,"deletedAt":0,"commentsUnread":0,"id":28,"overdue":0}
2019-06-17 21:45:14.328 6532-6532/it.niedermann.nextcloud.deck D/deck: onError() (IResponseCallback.java:21) -> java.lang.UnsupportedOperationException: JsonNull
        at com.google.gson.JsonElement.getAsInt(JsonElement.java:244)
        at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseCard(JsonToEntityParser.java:177)
```

so I refresh on Android (pull to refresh), this is in logcat:
```
2019-06-17 21:47:45.957 6532-7487/it.niedermann.nextcloud.deck D/deck: parseStack() (JsonToEntityParser.java:231) -> {"title":"За урадити","boardId":2,"deletedAt":0,"lastModified":1560800716,"cards":[...bunch of other...{"title":"test item","description":"","stackId":3,"type":"plain","lastModified":1560800716,"lastEditor":"username","createdAt":1560800689,"labels":[],"assignedUsers":[],"attachments":null,"attachmentCount":0,"owner":{"primaryKey":"username","uid":"username","displayname":"my name"},"order":999,"archived":false,"duedate":null,"deletedAt":0,"commentsUnread":0,"id":28,"overdue":0}],"order":0,"id":3}
... bunch of other
2019-06-17 21:47:45.962 6532-7487/it.niedermann.nextcloud.deck D/deck: parseCard() (JsonToEntityParser.java:133) -> {"title":"test item","description":"","stackId":3,"type":"plain","lastModified":1560800716,"lastEditor":"username","createdAt":1560800689,"labels":[],"assignedUsers":[],"attachments":null,"attachmentCount":0,"owner":{"primaryKey":"username","uid":"username","displayname":"my name"},"order":999,"archived":false,"duedate":null,"deletedAt":0,"commentsUnread":0,"id":28,"overdue":0}
2019-06-17 21:47:45.963 6532-7487/it.niedermann.nextcloud.deck D/deck: parseUser() (JsonToEntityParser.java:222) -> {"primaryKey":"username","uid":"username","displayname":"my name"}

```

and on web refresh, I get this:

![slika](https://user-images.githubusercontent.com/188751/59631681-ee5fdf00-9137-11e9-958f-d86b8099ad69.png)

This item seems to be gone. It is not in archived items, it is not in deleted items either.

**Comment by stalker314314** [comment]
wait...they are not gone, I found them:) They are just somehow _moved_ to completely different board? My board was ID=3, and they are now in ID=2:) Hope this helps:)

**Comment by desperateCoder** [comment]
holy cow... i was aware of the errors in logcat, i had less than 45 minutes and just hacked it down, i saw the card was gone so i assumed it worked... sorry for that fail! :laughing: 

I'll give it another try maybe tomorrow, thank you very much for testing my crappy code! and sorry again!

**Comment by stalker314314** [comment]
so, I am continuing to debug, seems that `stackId` was wrong when trying to update card...I will try to track that down too. Don't be sorry, no worries, this is best to-do manager I have, I am just missing Android version, so this is my way of helping:)

**Comment by desperateCoder** [comment]
Oh, and i am also aware of the fact that the UI doesn't refresh. I'll fix that asap.

And yes, you are right! the StackID is most likely wrong, since we have a local and a remote ID. The update should also set the Stack(remote)ID, since the DB reads the local one. let me fix that real quick...

**Comment by desperateCoder** [comment]
I guarantee, this does only work better, but is buggy as hell. Didn't test it either... I'll have a further look next time, i hope tomorrow evening. Hope it helps so far...

**Comment by desperateCoder** [comment]
*cough* :man_shrugging:

**Comment by desperateCoder** [comment]
Sorry, I think this needs some more attention... Just tested it, sounds good, doesn't work. I'll handle that as soon as i can.

**Comment by stalker314314** [comment]
no problem, whenever, there is no rush!

**Comment by desperateCoder** [comment]
Hi @stalker314314, 

as promised I had a deeper look into this this evening, the error log should be gone now.

But archiving a card seems to be a problem right now on the server side: https://github.com/nextcloud/deck/issues/1095 

I'll have to wait for a fix, but as soon as a new server app version is available, our app should start working without further development on the Android app.

Feel free to reopen this issue in case that it still doesn't work out for you then!
