### ISSUE TITLE
bug mi9 sync

### ISSUE THREAD

**Issue by ndj888** [stefan-niedermann/nextcloud-deck#945]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

```
App Version: 1.15.7
App Version Code: 1015007
Server App Version: 1.3.2
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.117-perf+(V12.0.5.0.QFXCNXM)
OS API Level: 29
Device: crux
Manufacturer: Xiaomi
Model (and Product): Mi9 Pro 5G (crux)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud文件应用api无响应。请反馈这个问题。
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Expected behavior**

**Screenshots**

**Versions**
 - Nextcloud: 
 - Nextcloud Deck: 1.3.2
 - Nextcloud Android: 3.15.1
 - Nextcloud Android Deck: 1.15.7

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed

**Comment by stefan-niedermann** [comment]
And also read the section above the linked one which will solve your issue.
