### ISSUE TITLE
sync errror when I update cards in app and nextcloud

### ISSUE THREAD

**Issue by kosatchev** [stefan-niedermann/nextcloud-deck#973]
Can not sync when i make changes in app and on site.
When I reset the app it works until app not closed
Also I use Tasks app with DAVx5.
```
App Version: 1.18.2
App Version Code: 1018002
Server App Version: 1.4.2
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.116(10.1.0.151C10)
OS API Level: 29
Device: HWVOG
Manufacturer: HUAWEI
Model (and Product): VOG-L29 (VOG-L29RU)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Не получен ответ от API приложения Файлы для Nextcloud. Сообщите об этой проблеме.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```

**Comment by stefan-niedermann** [comment]
Please disable all battery "opzimizations" [as described in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) and fill out the complete issue template next time. [It is there for a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
